### ISSUE TITLE
Server wont launch correctly

### ISSUE THREAD

**Issue by Hakluzak** [EnderMediaDev/The-1.7.10-Pack#1000]
Im not sure if this is a normal issue that has come up since this is my first time trying to play the modpack but im not sure whats wrong here. 
![error](https://cloud.githubusercontent.com/assets/16964605/12687990/3ff436c8-c6a1-11e5-955a-56d48da2566e.png)

Mediafire link to latest log:
http://www.mediafire.com/download/hv6rev38s1boy2v/fml-server-latest.log

**Comment by xJon** [comment]
> Set "eula.txt" to true

**Comment by Hakluzak** [comment]
rofl ty... my b

**Comment by xJon** [comment]
Also, congratulations for being issue #1000!
