### ISSUE TITLE
Ender IO Conduit Facades

### ISSUE THREAD

**Issue by BurgerGamer** [EnderMediaDev/The-1.7.10-Pack#1002]
I am unable to place conduit facades on conduits. I have only played on the newest version, so I don't know if this is a new bug with .8.2, an old bug or even a bug at all.

**Comment by xJon** [comment]
Works perfectly on v0.8.3, should release soon:
![image](https://cloud.githubusercontent.com/assets/8945347/12698400/1daee6b8-c7a4-11e5-94d0-72c96d8f1b81.png)
