### ISSUE TITLE
Single player crashes.

### ISSUE THREAD

**Issue by random-jackal** [EnderMediaDev/The-1.7.10-Pack#1003]
i was playing this pack with a friend and we added a few mods, in multiplayer everything worked fine but once i tried starting a single player world it got to the point where it starts loading the world and generating terrain before CTD. i took away the mods and reset the pack, but the issue still persisted. im going to delete and redownload it right now before i sleep but i suspect the issue may still persist.

here is the link to the latest crash log: http://paste.ubuntu.com/14730984/

any help would be greatly appreciated, thanks in advance.

**Comment by xJon** [comment]
Go to the modpack's folder -> configs and delete a folder named "machinemuse" or something like that.
It should reset and fix your issue.
