### ISSUE TITLE
Suggestion - Modular Systems

### ISSUE THREAD

**Issue by sgdc3** [EnderMediaDev/The-1.7.10-Pack#1004]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291862-modular-systems-formally-modular-furnace

**Comment by xJon** [comment]
Same as the other suggested mods, the Modular Systems mod is very interesting but it doesn't really fit the theme of the modpack. With so many mods, we would like to add just necessary stuff.
