### ISSUE TITLE
Suggestion - DivineRPG

### ISSUE THREAD

**Issue by sgdc3** [EnderMediaDev/The-1.7.10-Pack#1007]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2455655-divinerpg-8-new-dimensions-115-new-mobs-bosses

**Comment by xJon** [comment]
Not going to be added, thanks anyway for reporting.

**Comment by sgdc3** [comment]
Yeah, it's cool but maybe not appropriate ;)
