### ISSUE TITLE
Suggestion - Super Massive Tech

### ISSUE THREAD

**Issue by sgdc3** [EnderMediaDev/The-1.7.10-Pack#1008]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2105190-super-massive-tech-harness-the-power-of-the-stars
(Ok this is the last one for now, i promise! xD)

**Comment by xJon** [comment]
With so much tech mods already in the modpack, an addition is really not needed. Thanks anyway for all the suggestions, @sgdc3, all of them are welcomed at any time.
