### ISSUE TITLE
qCraft

### ISSUE THREAD

**Issue by xJon** [EnderMediaDev/The-1.7.10-Pack#1010]
qCraft is an amazing mod which released an official 1.7.10 version just two weeks ago.
What do _you_ think?

**Comment by sgdc3** [comment]
"The mod is very interesting but it doesn't really fit the theme of the modpack" XD

**Comment by sgdc3** [comment]
My question is: what's the theme of the pack? xD

**Comment by xJon** [comment]
@sgdc3 Just a bunch of mods that makes a complete pack, can't really explain it, but that's what we want :)

**Comment by sgdc3** [comment]
Lol ok

**Comment by Ukelelechris** [comment]
I don't know if this is open for everyone or not, but as a long time player of this pack I think this mod would be a fantastic addition. Hadn't heard about it till now, but after looking into it it definitely has some astounding and exciting applications that could change the way I do things permanently.
