### ISSUE TITLE
MagiCrops Breaking Problem

### ISSUE THREAD

**Issue by apotvin96** [EnderMediaDev/The-1.7.10-Pack#1011]
While playing last night I encountered a glitch that makes magicrops unuseable. Creation of a weak infusion stone works as it should but using a weak infusion stone to make the next tier of dust destroys the stone. Therefore each time you use the weak infusion stone it is removed and disappears. I was able to replicate this multiple times to confirm the problem. I was specifically using the project bench at first but this occurred in the vanilla table also. This did not occur for me until the most recent update 0.8.3  I am using OptiFine as the posting rules require mentioning (Although I doubt this is the problem) Any help would be greatly appreciated.

**Comment by xJon** [comment]
The stone should be used if you're crafting a higher tier stone. It shouldn't be used if you're crafting a seed or something like that.

**Comment by apotvin96** [comment]
Yes. I have used this in the past. The stone when surrounded with essence dust (North South East West) in the past would return a weak essence and the stone would be returned to the inventory or stay in the table. Now when using the stone to go to the next tier of essence the stone is removed and no longer exists

**Comment by xJon** [comment]
But it's supposed to do that when you're crafting the next tier stone.

**Comment by apotvin96** [comment]
Well this is not when crafting the next tier stone but rather when making the next tier of essence. So when using the stone to go from essence dust to weak essence the recipe in the past would result in weak essence and the stone would return to the inventory. Instead the stone is now removed and no longer exists. Which then requires a new stone to be made each time one would want to create weak essence from essence dust.

**Comment by apotvin96** [comment]
Update: Got back into minecraft and created a new creative file. Tested with the weak infusion stone and essence dust. The occurrence happens only on the project bench and not the default minecraft table. This did not occur for the previous update

**Comment by xJon** [comment]
Uh huh, I see. So I suppose it's a direct problem with the Project Bech. It should be reported directly to the mod author, there's nothing much I can do unfortunately. Thanks anyway for reporting.
