### ISSUE TITLE
v0.8.3 Diferent world gen? Cant find Stronghold

### ISSUE THREAD

**Issue by martinegui** [EnderMediaDev/The-1.7.10-Pack#1012]
I updated the modpack then when I went to look for the stronghold for the first time, I noticed that the map tha I knew before the update is not the same as the new map loaded after the update. It was broken ( Like different heights ) when I got o places that the chucks never loaded.. And the Pearls that should me show where is the stronghold, only point to one place that doesnt have any stronghold, doesnt matter how far I Go. I checked with Voxel map cave mode when digging to breadrock.
Any ideas how to fix or find a stronghold? 

EDIT: Tryed to correct some english to better understanding.

**Comment by martinegui** [comment]
I dont know if is a 0.8.3 problem or a 0.8.2 problem. I created the world and generate a lot of chunks at 0.8.2 before the upgrade.

**Comment by martinegui** [comment]
I tried to use AMIDST to version 1.7.10 from minecraft and no luck.

**Comment by xJon** [comment]
Do you mean that you can't find the end portal?

**Comment by martinegui** [comment]
Yes, sorry for the english, im not a natural english speaker.

**Comment by xJon** [comment]
Found this with v0.8.3 world-gen.
![image](https://cloud.githubusercontent.com/assets/8945347/13028870/83ba3dbe-d284-11e5-83db-1e1bafbd22e1.png)
