### ISSUE TITLE
I look on a special place and the game crash.

### ISSUE THREAD

**Issue by Dominik345** [EnderMediaDev/The-1.7.10-Pack#1016]
I build something with redstoneconduits from EnderIO and drawbridges and when I look on this, the game crash.
Sorry for my bad English.

**Comment by xJon** [comment]
Crash log? please use a paste-tool.

**Comment by Dominik345** [comment]
http://pastebin.com/yiYG6GxV

**Comment by xJon** [comment]
Remove Optifine.

**Comment by Dominik345** [comment]
Okey thanks
