### ISSUE TITLE
v0.8.2/0.8.3 Multiplayer missing books + crafting issue

### ISSUE THREAD

**Issue by LogMull** [EnderMediaDev/The-1.7.10-Pack#1021]
In multiplayer, characters spawning in for the first time are not given their HQM or Tinkers' Construct books, but in single player it works as expected.  Similarly, in multiplayer when trying to craft Tinkers' Construct's Crafting Station, the item immediately snaps back to the crafting grid, not allowing us to actually craft the item.  Once again, it works fine in single player.  These issues appear both 0.8.3 and 0.8.2.  I was running both server and clients OOTB.

Edit : There is nothing abnormal in the logs.

**Comment by xJon** [comment]
It doesn't happen in my tests. Probably the server that you played in disabled the option.
