### ISSUE TITLE
Server Issues

### ISSUE THREAD

**Issue by zorowinegar** [EnderMediaDev/The-1.7.10-Pack#1024]
I have been trying all afternoon to get a server working for this mod pack. The server skips loading mods. Any single player map I make works just fine. I used the server download that is provided onthe technic website. What can I do fix this issue? I even tried manually making a server and copying the mods from the technic files into it. I can't get anything to work.

**Comment by xJon** [comment]
You need to click "LaunchServer.bat".

**Comment by zorowinegar** [comment]
I have done that, that was one of the first things I did.

**Comment by xJon** [comment]
Then be sure you set eula.txt to true or try to reinstall. The server files come as a package, they should  always work.
