### ISSUE TITLE
Problem with one of ender io machines and with one of Graviation Suite recepture on server. 

### ISSUE THREAD

**Issue by Ersztek** [EnderMediaDev/The-1.7.10-Pack#1025]
Hi. 
The problem as the topic. 
1. When I use the alloy smelter with ender and I can not put it ender pearls.
2. I can not create itemMagnetron.name id: 6543: 4. When I put the right materials in the right way and  there is the object to take I can not pick it up.
Both problems relate to the server. In the game for the single player two things working properly.
Regards

**Comment by xJon** [comment]
Is it a private server? if so, for 2, try to install [that]() both client side and server side. Tell me if it fixed anything.
About 1, what modpack version are you playing with?

**Comment by Ersztek** [comment]
Yes, this is local server. one of my frend host server from his computer. 
2. We will try this.
1. It's v0.8.2.
We noticed that the errors occur only in a particular world. When we created a completely new all began to act. How can we fix the world?

**Comment by xJon** [comment]
Not sure. You can try to update to v0.8.3.

**Comment by Ersztek** [comment]
We updated the package and server. The problems have not disappeared.

**Comment by xJon** [comment]
Did you try to add the fixer though for the GraviSuite problem?

**Comment by xJon** [comment]
I tested it myself and it works. So issue 2 will fix next update, and for issue 1 I'd as for help from the mod directly. Thanks anyway for reporting!
