### ISSUE TITLE
Inventory Wiped upon relog

### ISSUE THREAD

**Issue by ericfussell** [EnderMediaDev/The-1.7.10-Pack#1029]
So I was playing the latest version of this pack and my inventory was wiped upon logging in. I have logged in several times since and it is still gone other than the books you start with. Any ideas on what caused this?

**Comment by xJon** [comment]
Singel-player?

**Comment by ericfussell** [comment]
Yes. Well actually on a lan world. My girlfriend's inventory is fine though.

**Comment by xJon** [comment]
We can't really give too much support for LAN worlds unfortunately, they are unpredictable with modded clients. I'd recommend you download the server files.
