### ISSUE TITLE
Stuck on Installing Screen?

### ISSUE THREAD

**Issue by lazydinosuars** [EnderMediaDev/The-1.7.10-Pack#1030]
I have all the requirements for the pack..I have 64 bit Java and i can run 7 GB of ram. But i cant seem to play the mod pack..I also might mention that I've played this mod pack before and it ran fine. But now it wont load :/.. Does it just take a long time to load or..? Is there something wrong with my lancher..? Please help? Thank you..

**Comment by lazydinosuars** [comment]
FIXED.. :))

**Comment by xJon** [comment]
:+1:
