### ISSUE TITLE
add 4Space please :) #Suggestion

### ISSUE THREAD

**Issue by Mangouste57** [EnderMediaDev/The-1.7.10-Pack#1032]
Hello !
 I know it's complicated to make mods compatible, but if you can add this mod, it would be perfect !

[4Space_Link](http://forum.micdoodle8.com/index.php?threads/4space.4715/)
Thanks you ! :+1:

**Comment by Chuckkid** [comment]
this mod sounds cool

**Comment by xJon** [comment]
Hi, 4Space is a very cool addon but as we decided it doesn't really fit the modpack.
Thanks anyway for suggesting!
