### ISSUE TITLE
java

### ISSUE THREAD

**Issue by ksnowball156** [EnderMediaDev/The-1.7.10-Pack#1035]
When the update happened our server broke. I know it wasnt the update so i am trying to get it fixed, when i lunched it the first time after the update a message popped up saying that i needed to update to 1.8 Java, but it didnt show up in the java tab on the launcher...so my question is do i need to download Java 8? or do i keep with Java 7? I know that the Java 8 made it to where it would crash just as it lunched, but now its doing the same with java 7... 
 i am out of ideas on how to fix this any suggestions???

**Comment by xJon** [comment]
You need to have Java 7 or 8, 64 bit.
