### ISSUE TITLE
Server works but the mods don't

### ISSUE THREAD

**Issue by JelySnow** [EnderMediaDev/The-1.7.10-Pack#1036]
I have set eula to true
![capture2](https://cloud.githubusercontent.com/assets/17296838/13113993/8f4fa5b4-d55f-11e5-8671-878ba3c5ac95.PNG)
I have tried running the LaunchServer.bat file and only get this
![capture](https://cloud.githubusercontent.com/assets/17296838/13114018/a8ecb886-d55f-11e5-8f19-6f35e3b8ba4e.PNG)
The only way I am able to get the server running is by using the minecraft server.jar which then means none of the mods work, I am able to see vanilla mobs with hats, but can not collect them, the morph and inventory mods UI are there but are not able to be clicked on and there are all the NEI items on the right, and when i go to creative i am able to spawn modded items in but not place or use them. I saw another article where the guy had a similar problem but gave up. https://github.com/EnderMediaDev/The-1.7.10-Pack/issues/409
I have downloaded and reinstalled 3 times now I tried 8.2 twice since it was recommended and 8.3 once. http://the-1710-pack.com/repo
![capture1](https://cloud.githubusercontent.com/assets/17296838/13114190/6462e4b4-d560-11e5-92c0-ed978a2527e8.PNG)

**Comment by xJon** [comment]
In the launch server file you have by default `forge-1.7.10-10.13.4.1614-1.7.10-universal.jar` and not `server.jar`. I don't know who edited that but that's what causing your error.

**Comment by JelySnow** [comment]
Thank you, sorry to bother you, i appreciate it. Also I really enjoy your modpack I could't get enough of single player and decided i needed to play with a group of friends thanks again.

**Comment by xJon** [comment]
:+1:

**Comment by j2ghz** [comment]
@xJon I encountered the same problem
#1024 #1023 You talk about modifying, but download the original zip: http://solder.endermedia.com/repository/downloads/the-1710-pack/the-1710-pack_0.8.2.zip
the scripts link to nonexisting server.jar
Could they be fixed?

**Comment by xJon** [comment]
@j2ghz I'll have a look at it, it might be due to the re-upload of all the server .zip files before v0.8.3.
