### ISSUE TITLE
Mystcraft causing errors as i try to enter an already existing world or a new world.

### ISSUE THREAD

**Issue by Ruthless-One** [EnderMediaDev/The-1.7.10-Pack#1037]
Cant load a new world or an already working world.

**EDITED: Please use a paste-tool: http://pastebin.com/CbQbe0cA**

**Comment by xJon** [comment]
This is quoted out of the log, but what actually happens in your client?

**Comment by Ruthless-One** [comment]
I click the window in the book and it would turn from black window to a gradient blue but nothing would happen, and clicking the gradient blue nothing would happen.  It would produce the error the first click and every click after.

**Comment by xJon** [comment]
Did you try just waiting beyond 2 minutes?

**Comment by Ruthless-One** [comment]
Correct. And nothing.

**Comment by Ruthless-One** [comment]
Now im trying to load a loaded world, and no error is being displayed and nothing happens after 5 minutes.

**Comment by xJon** [comment]
So basically you're saying you can't create new Mystcraft worlds?
What modpack version are you playing with?

**Comment by Ruthless-One** [comment]
I did for 1 book, but then i went about playing minecraft like normal for about an hour or two and then tried making a second one and then thats when it all happened. Version 0.12.3.01

**Comment by xJon** [comment]
Modpack version, not mod.

**Comment by Ruthless-One** [comment]
Oh sorry. 0.8.2

**Comment by xJon** [comment]
Try to update to v0.8.3, then.

**Comment by Ruthless-One** [comment]
Didnt see a new one came out, will try that one. Thanks.

**Comment by Ruthless-One** [comment]
Same thing with the new update. And its a fresh server with no plugins or anything. just shows a bunch of the same stuff, and sits and does nothing, but i do see that it is making the worlds, Under the world folder there are 3 new worlds that i have tried to join. And when i make the book. its a linking panel and any where from 1 to 20 blank sheets to make the book. Could that be part of the problem?

**Comment by xJon** [comment]
I have no problem creating new Mystcraft ages myself using v0.8.3:
![image](https://cloud.githubusercontent.com/assets/8945347/13202846/1081ee40-d8b1-11e5-832e-803ecf72032d.png)
Did you try to reinstall the modpack?

**Comment by Ruthless-One** [comment]
Correct. And yeah single  single player I don't have a problem. Only serve4.

**Comment by xJon** [comment]
So I'm not sure what's your problem. Maybe just try to let it load.

**Comment by Ruthless-One** [comment]
I can give you the ip and see. I have plugging now. But it did this with
fresh install as well.
