### ISSUE TITLE
NEI Mekanism, lots of lag

### ISSUE THREAD

**Issue by Richard-001** [EnderMediaDev/The-1.7.10-Pack#1038]
Whenever I search up Mekanism, or anything that brings up the page of  "portable tanks", the game lags A LOT and most of the time crashes the game and occasionally my computer. I try my best to avoid bringing the page up in NEI but it is rather annoying. Any idea on what's going on, or how I can fix it?

**Comment by xJon** [comment]
What version of the modpack are you playing with?
Do you have any additional mods?
Do you play in SSP or SMP?

**Comment by Richard-001** [comment]
The latest version. No additional mods and just single player.

**Comment by xJon** [comment]
It may took the client an extra second to bring up all the portable tanks but my game didn't lag "a lot" and of course didn't crash. Can you provide any crash-report maybe?

**Comment by Richard-001** [comment]
Unfortunately I cannot, there wasn't any crash report because the one time it did crash my computer went along with it, the other times windows automatically ended the process. And I don't think it's a problem with RAM, I do have 4GB allocated for the modpack.
