### ISSUE TITLE
Unable tu use turning table

### ISSUE THREAD

**Issue by TheFamousPG** [EnderMediaDev/The-1.7.10-Pack#1039]
How can I disable the design menu. I can't use the turning table with that.

**Comment by xJon** [comment]
What do you mean by the "design menu"?

**Comment by TheFamousPG** [comment]
There is nothing when I click, I concluded that from it it is bound to the design which replaces the usual buttons.
http://image.noelshack.com/fichiers/2016/07/1456010797-sans-titre.png

**Comment by xJon** [comment]
Does it has the required supply of energy?

**Comment by TheFamousPG** [comment]
of course.


*Mathieu Lescaudron*
47C rue marietton
69009 LYON

2016-02-21 5:51 GMT+01:00 Jon <notifications@github.com>:

**Comment by xJon** [comment]
Works with v0.8.3. You may just be doing it wrong.
![image](https://cloud.githubusercontent.com/assets/8945347/13202768/8181097a-d8af-11e5-9e35-dcd6b27bf8f7.png)

**Comment by TheFamousPG** [comment]
Can you show me your entire configuration ?
I do not understand....

**Comment by xJon** [comment]
You need kinetic energy outputting the power into the machine.

**Comment by TheFamousPG** [comment]
![image](https://cloud.githubusercontent.com/assets/9129639/13202959/40c422c2-d8ab-11e5-8cad-f84980f3efe9.png)

Why that is'nt work....

**Comment by xJon** [comment]
The output of the kinetic generator might not be next to the input of the turning table.

**Comment by TheFamousPG** [comment]
Can you show me, I do not understand?
thank you for your attention.

**Comment by xJon** [comment]
Try to rotate the machines.

**Comment by TheFamousPG** [comment]
But the turning table is red. If I turn, the turning table is off.

**Comment by TheFamousPG** [comment]
![image](https://cloud.githubusercontent.com/assets/9129639/13203008/d693d4ea-d8ac-11e5-8730-3f0191a36ad2.png)
Not working. Same thing.

**Comment by TheFamousPG** [comment]
Please, I really need help.

**Comment by xJon** [comment]
I'm not sure these cables can transfer kinetic energy.

**Comment by TheFamousPG** [comment]
I'm on 0.82.
Can you send me a wodl map with a functionnal turning table ?

**Comment by xJon** [comment]
I see, then you should try to update to v0.8.3.

**Comment by TheFamousPG** [comment]
yes. finally. the problem is in 0.82. Thanks for your attention and your greatful help !

**Comment by xJon** [comment]
:+1:
