### ISSUE TITLE
After loading world Crash 

### ISSUE THREAD

**Issue by TweezY1105** [EnderMediaDev/The-1.7.10-Pack#1040]
Hi I have a problem when my world then load at some point its crash
My crash report

**Comment by xJon** [comment]
Please post your crash report using a [paste-tool](http://pastebin.com).

**Comment by TweezY1105** [comment]
http://pastebin.com/AWtLR2wU

**Comment by xJon** [comment]
If trying to reset the settings.txt file didn't help, try to completely (backup your saves) and delete the modpack's folder, then install it again.

**Comment by xJon** [comment]
Closed due to inactivity.
