### ISSUE TITLE
Dimension Doors and Mo Creatures???

### ISSUE THREAD

**Issue by DisengagedSoul** [EnderMediaDev/The-1.7.10-Pack#1041]
I was wondering if Dimension Doors and/or Mo creatures could maybe added to the mix of mods since they are both updated to 1.7.10

But mostly just would like Dimension Doors :) 

Thanks for your time :)

**Comment by DisengagedSoul** [comment]
I would love to have some new areas to explore and more mobs to shoot :P so I thought it maybe an idea :) but I don't really know how hard it is to get most mods working soo :) no big deal if you cant :)
just an idea

**Comment by xJon** [comment]
Dimension Doors for Minecraft 1.7.10 is not stable enough, and Mo' Creatures don't give permissions for public modpacks, unfortunately.
Thanks anyway for suggesting the mods!
