### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Riyuki** [EnderMediaDev/The-1.7.10-Pack#1042]
[img]http://i.imgur.com/BknPzcG.jpg[/img]
Once I got to the link it downloads the reliquary mod, so then I deposite the files into C:\Users\Simon-PC\AppData\Roaming\.technic\modpacks\the-1710-pack\mods
And launch the installation again. 
It deletes the reliquary mod and pops the error again,
Please help

**Comment by Invineron** [comment]
I'm having the same issue as well.

**Comment by xJon** [comment]
Someone changed things in our FTP. Does it work now?

**Comment by Riyuki** [comment]
Another problem occurred can i somehow sent you the link and not via pastebin? (I don't wanna pay the fee for exceeding 512 kb.

**Comment by xJon** [comment]
http://paste.ubuntu.com/

**Comment by Riyuki** [comment]
http://paste.ubuntu.com/15174084/
Says its from the forge mod loader

**Comment by xJon** [comment]
Can you provide a screenshot or say what exactly happens? I can't find any error in the end of your log.

**Comment by Riyuki** [comment]
http://imgur.com/2u6ne7j there you go

**Comment by Riyuki** [comment]
If you can't find a solution can you please nicely send me the appropriate files (files that work)
so i can replace the folder and insert the new ones.

**Comment by xJon** [comment]
[Here's](http://minecraft.curseforge.com/projects/baubles/files/2224857/download) a direct download for the specific mod, but I'd recommend you to completely reinstall the modpack so no other pieces will be missing.
