### ISSUE TITLE
Sticky problem

### ISSUE THREAD

**Issue by askl001** [EnderMediaDev/The-1.7.10-Pack#1043]
Extention part randomly loss sticky augmentation

**Comment by xJon** [comment]
Can you please provide a bit more details?

**Comment by askl001** [comment]
At this scheme http://imgur.com/vyft3Pm extention part at random time (may work a lot of cycles, or break  after 1 cycle) loss sticky augmentation

**Comment by xJon** [comment]
So what mods are involved in this?

**Comment by askl001** [comment]
In this scheme
>Pistronics2
>ProjectRed
>OpenBlock

In all modpack: http://pastebin.com/MPRCGFst

**Comment by xJon** [comment]
If the problem is related to the Pistronics 2 mod there's not much I can do, it's not a mod included in the modpack by default.

**Comment by xJon** [comment]
Closed due to inactivity.
