### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by narutofan90** [EnderMediaDev/The-1.7.10-Pack#1044]
[techniclauncher_2016-02-23.zip](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/142555/techniclauncher_2016-02-23.zip)

**Comment by xJon** [comment]
> Right click on "This PC" -> choose "Properties" -> then on the left, click "Advanced system settings" -> then in the "Advanced" tab click "Environment Variables". Then scroll down on "System variables" to see if you have anything like `_JAVA_OPTIONS: -Xmx2G`. If so, delete it. Also be careful to not delete anything else.
