### ISSUE TITLE
The 1.7.10 pack crashes version 0.8.3

### ISSUE THREAD

**Issue by Brodyy** [EnderMediaDev/The-1.7.10-Pack#1045]
[crash-2016-02-23_22.36.50-client.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/143898/crash-2016-02-23_22.36.50-client.txt)

Help?

**Comment by xJon** [comment]
You'll have to delete the Flan's Mod entity yourself using a program of some sort.
