### ISSUE TITLE
A fatal error has occured, this connection is terminated

### ISSUE THREAD

**Issue by NoddyCzech** [EnderMediaDev/The-1.7.10-Pack#1048]
Everytime I start singeplayer world it just shuts down internal server and says this
Any help?
![screenshot - 2_25_2016 5_23_58 pm](https://cloud.githubusercontent.com/assets/17478568/13326164/0e809844-dbe5-11e5-9857-35408988aeab.png)

**Comment by xJon** [comment]
Please provide your latest client log, using a [paste-tool](http://paste.ubuntu.com/).

**Comment by NoddyCzech** [comment]
http://paste.ubuntu.com/15199064/

**Comment by xJon** [comment]
Try to remove the "Morph" mod, enter your world, and then re-add the mod.

**Comment by NoddyCzech** [comment]
Okey!

**Comment by NoddyCzech** [comment]
It works, thanks!

**Comment by xJon** [comment]
:+1:
