### ISSUE TITLE
Disable one mod

### ISSUE THREAD

**Issue by TheFamousPG** [EnderMediaDev/The-1.7.10-Pack#1050]
How to disable this mod. He destroy this mountain.
![screenshot_2](https://cloud.githubusercontent.com/assets/9129639/13345505/83d5ab82-dc5f-11e5-9bbb-3938219bf271.png)
![screenshot_1](https://cloud.githubusercontent.com/assets/9129639/13345506/83d6035c-dc5f-11e5-9309-f6c69b455e90.png)

**Comment by xJon** [comment]
That's a hungry node from Thaumcraft. I'd recommend you to not delete the entire mod, which is amazing, and:
 - Watch a tutorial to how to deal with hungry nodes
- Disable hungry nodes in Thaumcraft's configuration file.
