### ISSUE TITLE
INpureProjects website is down. Starting a fresh server is slow on 0.8.4

### ISSUE THREAD

**Issue by blindbox** [EnderMediaDev/The-1.7.10-Pack#1051]
I'm new to this pack first and foremost. I tried starting a fresh server on 0.8.4, on Ubuntu 14.04 LTS.

This error message seems to be the culprit:-
`[15:24:11] [main/INFO] [STDOUT]: [info.inpureprojects.core.API.Utils.Downloader:download:19]: Downloading: http://files.inpureprojects.info/libs/commons-compress-1.8.1.jar
`
inpureprojects.info and their mods have reached its EOL. 

See http://webcache.googleusercontent.com/search?q=cache:MpQfg3Bz9EUJ:inpureprojects.info/Minecraft/eos.html+&cd=2&hl=en&ct=clnk

**Comment by xJon** [comment]
You still should be able to start a server. Are you not able to?
