### ISSUE TITLE
Crash on Join

### ISSUE THREAD

**Issue by ThePotatoTom** [EnderMediaDev/The-1.7.10-Pack#1052]
Just wondering, my friend hosts a server for me through Akliz/Endermedia, And after a while of playing on the server fine with a bud, we both crash and continue to crash on rejoin. He made a new map and we stopped crashing but it happened again. I am waiting for him to return to see if it can be fixed with a simple server restart but i don't know. Do you know why this is happening? We are playing on 0.8.3 as i don't thing Akliz had 0.8.4 yet.

**Comment by ThePotatoTom** [comment]
[crash-2016-02-27_17.32.00-client.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/149801/crash-2016-02-27_17.32.00-client.txt)
That's the crash report, I also hear a mine cart noise whilst connecting

**Comment by xJon** [comment]
You noted that this happened to you *twice*.
After what you guys did, the server started crashing with this?

**Comment by ThePotatoTom** [comment]
Well he just restarted the server and it works fine again, it might just be a bug that's bearable, but i don't know what causes it and its crashed once per map so far

**Comment by xJon** [comment]
:+1:

**Comment by ThePotatoTom** [comment]
Never mind... The server works for a newcomer but for my friend and I it is still crashing

**Comment by xJon** [comment]
Same crash-log?

**Comment by ThePotatoTom** [comment]
[crash-2016-02-27_17.32.00-client.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/149830/crash-2016-02-27_17.32.00-client.txt)

**Comment by ThePotatoTom** [comment]
wait i might've sent the wrong one, hold on

**Comment by ThePotatoTom** [comment]
[crash-2016-02-28_01.21.58-client.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/149831/crash-2016-02-28_01.21.58-client.txt)

**Comment by xJon** [comment]
Do you have any additional mods?

**Comment by ThePotatoTom** [comment]
No I do not, although we are running0.8.3 both client and serverside

**Comment by xJon** [comment]
Did you disable any mods in server-side or change something in the modpack?

**Comment by ThePotatoTom** [comment]
I don't host the server or have console but I'm pretty sure nothing was changed, just downloaded the server file and ran it

**Comment by xJon** [comment]
Anyway this is something to do with the EnderZoo mod.
I'll suggest to try to:
- Update your server and clients to v0.8.4, and make sure you don't modify any configs or files.

If after that you still experience the same crash, then remove the EnderZoo mod manually. But I'm 99% sure that updating fresh to the new version in your clients and server will fix your problem.
