### ISSUE TITLE
Can't create rancher in multiplayer

### ISSUE THREAD

**Issue by TheFamousPG** [EnderMediaDev/The-1.7.10-Pack#1053]
Hi,

I can't create rancher in mutliplayer, do you know why ?
I'm on 0.83

In solo : 
https://gyazo.com/6a3c42b03472acf6d00f6bb6301108e9

In multi 
https://gyazo.com/7a135420ce60182ee0a029349c9f485c

**Comment by xJon** [comment]
This is the Thermal Expansion recipe for MFR. You can enable or disable them in the configuration files.
I don't know on what server do you play, but by default these recipes are enabled in The 1.7.10 Pack.

**Comment by TheFamousPG** [comment]
Ok thanks. 
I'm on the default 1.7.10 server.

**Comment by TheFamousPG** [comment]
The rancher is enable, but I can't create it : 
https://gyazo.com/3e29137b039d4360499c24e8976d84a5

**Comment by xJon** [comment]
The configuration file should in `the-1710-pack_0.8.4\config\powercrystals\minefactoryreloaded\common.cfg`.
The required line is in 330:
`RecipeSets {
    # If true, MFR will register its EnderIO-based recipes.
    B:EnderIO=true

    # If true, MFR will register its Thermal Expansion-based recipes.
    B:ThermalExpansion=true

    # If true, MFR will register its standard (vanilla-item-only) recipes.
    B:Vanilla=false
}`

**Comment by TheFamousPG** [comment]
I've never touch the config : 
https://gyazo.com/b3190d98583cd7bfed8be0c5acd5a1f4

**Comment by xJon** [comment]
This is indeed weird and I can confirm this. Please report this minor issue [there](https://github.com/skyboy/MineFactoryReloaded/issues) though, because there's nothing I can do about it, unfortunately.
