### ISSUE TITLE
Can't craft some items

### ISSUE THREAD

**Issue by DuckTheCow** [EnderMediaDev/The-1.7.10-Pack#1054]
Some items can't be crafted after 0.8.4 one know one is ender infused obsidian. The recipe does not appear on the list of uses for the ender pearl but on the recipe it says that it is the recipe. Extra utilities transfer node is another.
Thanks

**Comment by xJon** [comment]
Did they work before v0.8.4? Also, do you play on server or client?

**Comment by xJon** [comment]
Closed due to missing information.

**Comment by DuckTheCow** [comment]
It fix itself
