### ISSUE TITLE
Client crash upon server log in.

### ISSUE THREAD

**Issue by Starman245** [EnderMediaDev/The-1.7.10-Pack#1055]
I have been playing on this public dedicated server for a very short time, and I have already ran into an issue. I left the server so it could restart, and then when I tried to join back, I crashed. [Crash Log](http://paste.ubuntu.com/15231237/) I don't know if this is a server file issue, but I will posting to their forums as well.
I have been playing on v8.2 (its the only version the server supports). 
The following has been done to troubleshoot:
-Turn render distance down
-Increase RAM to 8
-Reinstalling the version used
But to no avail.

**Comment by xJon** [comment]
Same issue as in #1052. My comment:
> Anyway this is something to do with the EnderZoo mod.
I'll suggest to try to:

Update your server and clients to v0.8.4, and make sure you don't modify any configs or files.
If after that you still experience the same crash, then remove the EnderZoo mod manually. But I'm 99% sure that updating fresh to the new version in your clients and server will fix your problem.
