### ISSUE TITLE
Crash Report with Progressive Automation Chopper + Universal Cable

### ISSUE THREAD

**Issue by 82280zx** [EnderMediaDev/The-1.7.10-Pack#1056]
http://paste.ubuntu.com/15236991/

When one of the players put a Universal Cable on a Automation Chopper it brought down our server with a ticking entity loop.

Also when graphics is set to fast (with or without the texture pack) the AE2 crystals don't show in the chargers. Also a name problem with what used to be called the production table it is now called a relocator table (wrong name I believe unless the mod dev changed it).

**Comment by xJon** [comment]
Could you report the crash in the [mod's repository](https://github.com/Vanhal/ProgressiveAutomation/issues)?

**Comment by 82280zx** [comment]
Submitted.

**Comment by xJon** [comment]
:+1:
