### ISSUE TITLE
wont open

### ISSUE THREAD

**Issue by VvINFINITEvV** [EnderMediaDev/The-1.7.10-Pack#1057]
i click open and then it opens the icon but after that nothing happens

**Comment by xJon** [comment]
Please provide your latest client/launcher log using a [paste-tool](http://paste.ubuntu.com/).

**Comment by VvINFINITEvV** [comment]
im using mianite 1.4.1 and how to i get to the logs

**Comment by xJon** [comment]
This is not the place for Mianite support. Go [there](https://github.com/EnderMediaDev/Realm-Of-Mianite/issues).
