### ISSUE TITLE
Mod Suggestion: Food Plus Mod

### ISSUE THREAD

**Issue by NerdCraftUK** [EnderMediaDev/The-1.7.10-Pack#1058]
Hello,
I was wondering if you have ever heard from the Food Plus Mod. It's a very cool mod that adds a LOT of food. It has experimental Sphax PureBDcraft support. Here's the link to the MC forum page: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1288375-food-plus-mod-more-food-than-you-can-imagine-v3
Please add this, this is one of my favourite mods.

**Comment by NerdCraftUK** [comment]
ps: Don't click on the link, copy and paste it.

**Comment by xJon** [comment]
There are already tons of types of food from the Pam's Harvestcraft mod, there's really no need for another mod from that type. Thanks anyway for suggesting!
