### ISSUE TITLE
cant find ghost wood tree or some hives

### ISSUE THREAD

**Issue by missexo** [EnderMediaDev/The-1.7.10-Pack#1061]
hello sorry if i posted this on the wrong page but ive had a few issuse's i dont know if its to do with my world gen or what but i cant find ghost wood trees in the nether and ive not found rocky hives or water hives and ive searched for hours and hours on end =x any help would be very helpful ty oh ps ive also not found any of the magical crops foods :(

**Comment by xJon** [comment]
Magical Crops foods are mostly disabled due to the duplication with Pam's Harvestcraft foods.
About the hives, they shouldn't be disabled.

**Comment by missexo** [comment]
Thank you for the quick reply i was going insane looking for them haha as for the hives ill just keep looking i guess i spwaned in an unlucky part : (

**Comment by xJon** [comment]
:+1:
