### ISSUE TITLE
Enchantment Plus issue

### ISSUE THREAD

**Issue by rastamanfb** [EnderMediaDev/The-1.7.10-Pack#1062]
Since updating from 8.1 to 8.4 (skipped .2 and .3 due to binnie compatibility) the advanced enchantment table vanished. I have cheated a new one in as its available from NEI but It cannot be used to enchant new unenchanted items.

I briefly remember there being an issue with modID but cannot remember what i did to fix it which is probably why the item vanished in the update

Anything you can help with or verify?
Kind Regards

**Comment by rastamanfb** [comment]
ok actually its just a feature the new makers of eplus have done which imo is bad
https://github.com/Epoxide-MC/Enchanting-Plus/issues/13

apparently the ability to turn off the need for scrolls has been fixed but it seems it hasnt 

Kind Regards

**Comment by xJon** [comment]
Well with this you should get your help in the mod's repository. There's not much we can add.

**Comment by rastamanfb** [comment]
Hi, looks like one half of the dev team has abandoned it.
What was the reason for moving off the old one to this version? Were there
compatibility issues?

**Comment by xJon** [comment]
Dupe issues.

**Comment by rastamanfb** [comment]
Damn, seems a shame people keep jumping. There seemed like a future for
this mod.
