### ISSUE TITLE
Missing recipies

### ISSUE THREAD

**Issue by Zalson** [EnderMediaDev/The-1.7.10-Pack#1068]
Seeing how it is a known issue for magical crops to have uncraftable platinum seeds, is it possible for us to have MineTweaker added to the mod pack?There is a script available that fixes this. Even if it does not have the script to fix it automatically installed, having the option to have minetweaker scripts would be great I don't particularly like the idea of needing to have my players manually add it, I prefer that they just be able to run the pack and be able to play as not all of them are the savvy computer type.

https://gist.github.com/Choonster/6a8229b4ee1b410ac901

Edit: Added the link to the script

**Comment by xJon** [comment]
For this specific recipe we wouldn't like to add MineTweaker.
Thanks anyway for reporting though
