### ISSUE TITLE
Showcase

### ISSUE THREAD

**Issue by thebalck** [EnderMediaDev/The-1.7.10-Pack#376]
Can we make an area for a showcase, so can people show what they do with the pack ?

**Comment by The-1-7-10-Pack** [comment]
Amm, cool idea. Where do you think it should happen? Maybe a gallery?

**Comment by thebalck** [comment]
Yeah something like a gallery or a place where we can paste links for videos with showcases and galleries

**Comment by The-1-7-10-Pack** [comment]
I'll leave this suggestion open for a future plan, it is a good idea.
Thanks! :)

**Comment by TreePuncher9501** [comment]
I think this is a good idea, as it would allow people to show unique creations and multi-mod multi-functional machines.

**Comment by Voideon** [comment]
^^

**Comment by thebalck** [comment]
well until the official place i left here some of my server shots
http://imgur.com/a/IWcTE#1

Hope you guys like it 

PS:. if someone want one close view or one "how to build" of something just ask

**Comment by The-1-7-10-Pack** [comment]
@thebalck What an awesome base! I like the use of the Chisel mod.

**Comment by thebalck** [comment]
Yeah chisel is an awesome mod : D

But now im out of ideas for things to build because i like to do mecanical things, any ideas ??

**Comment by The-1-7-10-Pack** [comment]
@thebalck What do you need? Power? Resources?

**Comment by thebalck** [comment]
Nop im good in both i just build things because i can xD

**Comment by Alakatria** [comment]
shall we create a sub reddit for the modpack?

**Comment by The-1-7-10-Pack** [comment]
@Alakatria If you guys think it'll be active, sure!

**Comment by darktrek** [comment]
hey did anyone make a sub reddit in the end ? just checking for i do if not

**Comment by The-1-7-10-Pack** [comment]
@thebalck I don't think so.

**Comment by The-1-7-10-Pack** [comment]
We're planning to add new forums to the modpack's website :)

**Comment by xJon** [comment]
@thebalck, @TreePuncher9501, @Voideon, @Alakatria, @darktrek: **The forums of EnderPlay are officially out!**
http://forums.enderplay.com/forums/the-1710-pack/
You could post anything you'll want there, asking questions or posting buildings. Just be sure to keep the support for here :)
