### ISSUE TITLE
LookingGlass

### ISSUE THREAD

**Issue by The-1-7-10-Pack** [EnderMediaDev/The-1.7.10-Pack#618]
[LookingGlass](http://minecraft.curseforge.com/mc-mods/230541), what do you think guys?

**Comment by TheLegend714** [comment]
If it works well and fits in the mod pack I guess do it!

**Comment by mandm635** [comment]
Sure as long as it doesnt create lag

**Comment by RedGoblin** [comment]
I like it as well. As long it doesn't create much lag like mandm635 says.

**Comment by Grimdeath** [comment]
If it works well and fits in the mod pack I guess do it!

**Comment by mckulich** [comment]
I am already using this mod and it works fine

**Comment by xJon** [comment]
Currently won't be added, it gives less than it takes.
