### ISSUE TITLE
New Quest(s) Suggestion

### ISSUE THREAD

**Issue by Zorin419** [EnderMediaDev/The-1.7.10-Pack#778]
One thing that I see fit in the quest book, is a quest for becoming a [vampire](https://sites.google.com/site/witcherymod/vampirism) or [werewolf](https://sites.google.com/site/witcherymod/lycanthropy) from the Witchery mod. I imagine the required quest item for vampire would be ["blooded wool,"](https://sites.google.com/site/witcherymod/blood-stained-wool) because only vampires can make it. The required quest item for werewolf would obviously be the [moonstone.](https://sites.google.com/site/witcherymod/moon-charm)

My Idea for rewards, when completing the vampire quest, give them a ["Cane Sword."](https://sites.google.com/site/witcherymod/cane-sword)
For Werewolf, how about 30 ["Raw Lambchops,"](https://sites.google.com/site/witcherymod/raw-lambchop) because they need 30 of them to continue the werewolf questline.

If giving a Cane Sword is too overpowered for a quest reward, maybe give them 5 ["Woven Crour"](https://sites.google.com/site/witcherymod/woven-cruor) and a Golden Ingot.

I apologize if this was the incorrect way to suggest a quest, but your instructions on the update were admittedly a little vague.

Thank you for taking the time to read, whoever you may be.

**Comment by Zorin419** [comment]
Also... how do you feel about ducks? ( ͡° ͜ʖ ͡°)

**Comment by ModalTiger** [comment]
For some new quests, there should be a number of quests that can be re-done every few days or so in-game, with the task of slaying a different creature/monster each time and gaining a reward based of creature/monster stats/difficulty. For example slay something like an angry zombie would be rewarded with common/uncommon loot, whilst slaying a wither would reward epic/legendary loot. 

Also, in my opinion there should be an item counter in which when certain item is collected a certain amount of times it completes an item marker, and then a reward is given for each marker For example, diamonds:
10 diamonds- reward, 25 diamonds- reward, 50 diamonds- reward, 100 diamonds- reward
Each reward for an item increases in value after each marker, eventually completing the item quest at marker 100 or so, depending on the item.

**Comment by The-1-7-10-Pack** [comment]
@ModalTiger But then, people can make Wither farms (which they actually already make) and use the system, which would make it really OP. I don't think that currently we can make quests that would reset every few days.

**Comment by ModalTiger** [comment]
Hmm that is true

**Comment by Zorin419** [comment]
Are renewable quests even *possible* in HQM? Sorry I know nothing about its capabilities.

**Comment by The-1-7-10-Pack** [comment]
@Zorin419 It is.

**Comment by Zorin419** [comment]
HQM is an amazing mod. But, of course, you already knew that.

**Comment by Smalfinn** [comment]
What about quests for survival... Like survive a night without dying or sleeping... Traveling across all biomes and some more misc quests just for that early game boost? (Just a thought)

**Comment by CoolKarateMan** [comment]
What if there were quests for normal Minecraft-y stuff? Going into the Nether, enchanting an item, etc. Obviously the rewards wouldn't be all that great, but it would be something.

**Comment by The-1-7-10-Pack** [comment]
@CoolKarateMan It's not the theme of the quests that we want to provide. We don't want to give one torch for making a crafting table.

**Comment by Zorin419** [comment]
Why are people leaving suggestions here?
