### ISSUE TITLE
Werewolf is invisible for other players in server

### ISSUE THREAD

**Issue by Voideon** [EnderMediaDev/The-1.7.10-Pack#780]
So I'm back and i've opened a server and restarted playing "Minecraft" and i've still got the witchery issue...

When you're a werewolf and you've been transformed (Wolfman,Wolf) your "beast" skin is invis and you, nor any other players can see it, it's not just on the server, it's as well on singleplayer and it really defeats  the purpose of being a werewolf...

Note: I'm not using Optifine (yet) and I have no texture pack installed at the moment.

**Comment by The-1-7-10-Pack** [comment]
- Try to remove the "VoxelPlayer" litemod.
- Try to remove the "RenderPlayerAPI" mod.
Anyone of them helps?

**Comment by Voideon** [comment]
Neither helped, I've deleted them on the server, and on my client

**Comment by The-1-7-10-Pack** [comment]
Have any idea in which version of the pack did the issue start?

**Comment by The-1-7-10-Pack** [comment]
It's a conflict between Render Decorator (VoxelPlayer) and Witchery.
I reported it to the author of Render Decorator, but if we won't have any solution we might have to remove the VoxelPlayer.

**Comment by xJon** [comment]
Removing both mods from client side.
