### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by jacobdono** [EnderMediaDev/The-1.7.10-Pack#793]
Just updated to 0.7.9e now I can't run the pack at all on any versions, it just crashes after a minute or two of black window. Any ideas on how to fix?

**Comment by The-1-7-10-Pack** [comment]
Any logs? information?
Read [this](https://github.com/The-1-7-10-Pack/The-1.7.10-Pack/blob/master/README.md).

**Comment by jacobdono** [comment]
I'm using a mac and the log format is in .log so i can't attach it here, do you want me to just copy and paste the whole log?

**Comment by The-1-7-10-Pack** [comment]
I need your fml-latest-client.log file, paste it [here](http://paste.ubuntu.com/).

**Comment by ciak2009** [comment]
hi

**Comment by ciak2009** [comment]
heyo

**Comment by ciak2009** [comment]
i is derp

**Comment by jacobdono** [comment]
http://paste.ubuntu.com/11964464/

**Comment by xJon** [comment]
Do you have any additional mods?

**Comment by jacobdono** [comment]
Nope, just the pack

**Comment by xJon** [comment]
It's an issue with Chisel as I see it, but it doesn't make much sense as a lot of players can launch normally.
Try to remove the Chisel mod manually, are you able to launch? If you are, try then to put it back. Maybe it'll change something.

**Comment by jacobdono** [comment]
Still no luck with that

**Comment by xJon** [comment]
You're unable to launch even without the Chisel mod?

**Comment by jacobdono** [comment]
Nope, I'll try again once I get home from work

**Comment by jacobdono** [comment]
I just reinstalled the pack and it's working fine, thanks for help, i love pack and keep the great work up !

**Comment by xJon** [comment]
Probably something went wrong in the first installation. Happy you got it figured out :+1:
