### ISSUE TITLE
USE BOLL FOR POLLS BECAUSE ITS AWESOME

### ISSUE THREAD

**Issue by ciak2009** [EnderMediaDev/The-1.7.10-Pack#801]
http://www.boll.co

**Comment by xJon** [comment]
Do they pay you to suggest that?

**Comment by ciak2009** [comment]
Have you tried them? They are that good.

**Comment by xJon** [comment]
That's exactly what someone that gets paid would have say.

**Comment by ciak2009** [comment]
Would "have say", do you even english bro?

**Comment by ciak2009** [comment]
#shotsfired
