### ISSUE TITLE
Suggestion - Add Dynmap to the modpack maybe?

### ISSUE THREAD

**Issue by Smalfinn** [EnderMediaDev/The-1.7.10-Pack#802]
Dynmap is a web-based world map and I know for myself with 2 monitors it could be a god send to have the map up on one screen while I do other things on minecraft itself.

Just a thought :)

Information: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1286593-dynmap-dynamic-web-based-maps-for-minecraft

**Comment by xJon** [comment]
Dynmap is more used for servers and less for SSP. It doesn't really fit the modpack, also we have the VoxelMap which is great. Not for your specific use, but still :)
