### ISSUE TITLE
Server shutting down

### ISSUE THREAD

**Issue by Orlefanto** [EnderMediaDev/The-1.7.10-Pack#803]
Hello.

I have a bug in single game. I used worktable from Forestry and try to make a copper cable and if I clicked on this cable - game crushed (shutting down server).

![2015-07-30_17 50 41](https://cloud.githubusercontent.com/assets/13574693/8988410/a265cd82-36ee-11e5-9f06-7503b68da07a.png)

**Comment by xJon** [comment]
Please read [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/blob/master/README.md).

**Comment by xJon** [comment]
![image](https://cloud.githubusercontent.com/assets/8945347/9023348/0979aa80-38a1-11e5-80c5-6c0b9e52ad4f.png)
I'll reopen the issue with a crash report or something like that.
