### ISSUE TITLE
Perms if needed

### ISSUE THREAD

**Issue by cowboyup1987** [EnderMediaDev/The-1.7.10-Pack#805]
I have finally got my server running thanks to your help with the installation of KCauldron and I would like to know 1st if I needed your permission to post my server while using your modpack to sites like planetminecraft.com  or if it mattered. If I do need it..may I have it. and if I don't need it then please let me know. 2nd I wanted to know if I'm still able to use your modpack publicly after making a change to the pack by adding some flans content packs.

I'm just asking so that I don't violate your pack and of course credit will be given to you for the pack creation.

**Comment by xJon** [comment]
- No need to ask for permissions to post community servers, just be sure to post the pack's name and a link back to the download page
- If you add more content, people using the pack won't be able to login to your server, and they will all have to install the content manually, so I would'nt recommend it.
