### ISSUE TITLE
Sever Set-up problems

### ISSUE THREAD

**Issue by sweetbam** [EnderMediaDev/The-1.7.10-Pack#806]
I downloaded the 0.7.9f server to run, however after running the 1.7.10 minecraft cerver and creating world when i try to open the launchserver batch file the command box give an error reading : missing 'server' JVM at 'C:Program Files <x86>\Java\jre1.8.0_31\bin\server\jvm.dll 

I created my own batch file to run the forge-1.7.10-10.13.4.1492-1.7.10-universal.jar server however when it starts up after about 45 seconds of loading the mods the program becomes unresponsive and begins to use to much cpu. any advice would be appreciated.

the mod pack works fine in single player but i can not seem to get this server up and running. I have set up two other servers previous to this however none with such a large amount of mods.

thanks in advance,
sweetbam

**Comment by xJon** [comment]
You're sure you're using Java 64 bit?

**Comment by xJon** [comment]
Closed due to inactivity.
