### ISSUE TITLE
Carpenters Blocks : Chisel

### ISSUE THREAD

**Issue by Turtsfam** [EnderMediaDev/The-1.7.10-Pack#807]
There seems to be a bug in the Carpenters Block mod where the chisel can't be used to change blocks textures.

**Comment by xJon** [comment]
How can Chisel change the blocks texture if Carpenters Blocks' textures are based on others?

**Comment by xJon** [comment]
I tested it myself and it works good.
If you'd provide more information I might be able to help :)
