### ISSUE TITLE
HELP - A world leak?

### ISSUE THREAD

**Issue by Smalfinn** [EnderMediaDev/The-1.7.10-Pack#808]
fml-server-latest.log - http://paste.ubuntu.com/11973617/

Should I be worried about the console keep telling me about world leaks and the buildcraft error line?

**Comment by xJon** [comment]
It's not a world leak, it's just a warning due to the activity of ChickenChunks, it's like that in every modpack and every game save.
About the Buildcraft thing - You should report it [here](https://github.com/BuildCraft/BuildCraft/issues). It's not major but it should be fixed :)
