### ISSUE TITLE
Different ingots when smelting steel dust in an energized smelter

### ISSUE THREAD

**Issue by cornytrace** [EnderMediaDev/The-1.7.10-Pack#809]
It seems that each time the server is started, smelting mekanism steel dust in an mekanism energized smelter either results in mekanism steel ingots or ic2 refined iron ingots. This is very annoying when working with AE2, as it expects one or the other exclusively.

**Comment by xJon** [comment]
We can indeed see this recipe in the normal furnace:
http://i.imgur.com/GSLI5t3.png
![image](https://cloud.githubusercontent.com/assets/8945347/9023332/412f8c02-38a0-11e5-8754-fe3d13f691a3.png)
But in the Redstone Furnace we can see only the Mekanism's version:
![image](https://cloud.githubusercontent.com/assets/8945347/9023331/3d5d6f86-38a0-11e5-9d96-09d24dcd24d5.png)
Also they are both with the same Ore Dictionary, so they should work the same in every recipe.
If they're not, tell me and I'll reopen the issue.

**Comment by cornytrace** [comment]
I'm using a mekansim energized smelter, which uses the normal smelting recipes and not the redstone furnace recipes.
In applied energistics you must only specify one resulting ingot for automatically smelting dusts into ingots. As after a restart the ingot produced by the energized smelter may change from a steel ingot to a refined iron ingot, the applied energistics autocrafting system keeps waiting on ingots which never come, as they have a different itemid.
The solution is easy, as indeed the ingots are connected through the ore dictionary: simply eliminate one of the two smelting recipes. The ingots the energized smelter produces will then be consistent; Making AE autocrafting work and making the different ingots not take up two spaces in chests.

**Comment by xJon** [comment]
Well yes, it's not really an issue and there's nothing we can do about it :)
