### ISSUE TITLE
Ender IO Armor Enchanting

### ISSUE THREAD

**Issue by cvjones360** [EnderMediaDev/The-1.7.10-Pack#810]
I am not able to enchant or upgrade the Dark Helm with a night vision potion.  (it is NOT a splash potion) When I place both items in the anvil interface it does not recognize it as being an option. I haven't tested it on other pieces of the Dark Helm set, but I will soon.

**Comment by xJon** [comment]
The nightvision upgrade requires the "Empowered I" upgrade, do you have that?

**Comment by cvjones360** [comment]
I have empowered III on the helm.




![darkhelm](https://cloud.githubusercontent.com/assets/4058468/9023585/d1fcf3a4-386f-11e5-8c01-f4cc0382aa60.png)

**Comment by xJon** [comment]
What version of the modpack are you using?

**Comment by cvjones360** [comment]
v0.79f

**Comment by xJon** [comment]
Can you give a picture of the type of potion are you using?

**Comment by cvjones360** [comment]
Sure, just a second. I had to shutdown the game to get the version. (To be sure actually)

**Comment by cvjones360** [comment]
![potion1](https://cloud.githubusercontent.com/assets/4058468/9023656/fb2d0270-3872-11e5-8c02-51df0e1bb9b4.png)

**Comment by xJon** [comment]
Are you in client or server?

**Comment by cvjones360** [comment]
Client

**Comment by xJon** [comment]
How did you get the 8230 one?
I'm testing with the 8198 one, that you get from the brewing stand, and it works great
![image](https://cloud.githubusercontent.com/assets/8945347/9023706/aed0deaa-38af-11e5-861f-2b04369fde6d.png)

**Comment by cvjones360** [comment]
It was a mob drop.... I've used the dropped potion to upgrade the helm on FTB Infinity.  Maybe that's the problem. Seems it should work. I will brew one and go from there. Thanks.  BTW... BEST mod pack ever for me.  I really enjoy it. Thanks, very good job.

**Comment by xJon** [comment]
:+1:
