### ISSUE TITLE
Dark Helm Enchanment Issue

### ISSUE THREAD

**Issue by cvjones360** [EnderMediaDev/The-1.7.10-Pack#811]
You closed the problem without allowing me to respond.  The helm is empowered.  See below.

![darkhelm](https://cloud.githubusercontent.com/assets/4058468/9023599/c523f88e-3870-11e5-9fa8-412d5c22c676.png)

**Comment by xJon** [comment]
No need for 2 issues, also, I can always reopen one issue :)
