### ISSUE TITLE
Big Reactors crashing

### ISSUE THREAD

**Issue by lordracalas** [EnderMediaDev/The-1.7.10-Pack#813]
Hello.

I've been playin this pack like crazy and recently I discovered how easy and op those big reactor things are. So I've been using a very simple 3x3x3 model that I found on Youtube and it was working perfectly to power my quarry.

However when my first quarry site hit the bedrock I had to relocate the whole damn thing because my base in is the mountains surrounded by water, so I dismantled the multiblock reactor to assemble it on the new quarry site.

Now here comes the problem: ever since I reassembled the reactor, every time I go into the control panel interface (forgot the name of the block, it's where you check heat and turn on and off the reactor) my game crashes. After some crashes I managed to turn it on and it worked just as before, but every time I go into the interface it crashes. The first time I assembled it (in the first site), it did not crash.

I'm using the latest version of the pack (0.7.9f I think?) and my resource pack is Sphax PureBDcraft 128x for 1.7.10 (don't know if this influences or not).

As far as I experienced, this is the first time I got game crashes playing this pack.

Thanks and forgive my bad English. =)

**Comment by xJon** [comment]
We need more information, can you please read [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/blob/master/README.md)?

**Comment by lordracalas** [comment]
Checklist:
*Latest version of the pack;
*Java 8 64bits
*8GB RAM in my system, 6GB to the game
*Yes original technic platform
*Double checked.

About the log, I got it, but this "Ubuntu Pastebin" freezes every time I paste the log in it, right now it's been loading for 10min or so. Is there any other paste tool that I can use?

**Comment by xJon** [comment]
It's just loads a lot if you paste there full logs, but if you're crashing, you can just post the crash log :)

**Comment by lordracalas** [comment]
Alright, I think I got it. Thanks for the help.

Link:

http://pastebucket.com/88423

**Comment by xJon** [comment]
Can you try to open it with an empty hand? Does it work then?

**Comment by lordracalas** [comment]
uhh, you mean with no items in my character hand?

**Comment by xJon** [comment]
Yes.

**Comment by lordracalas** [comment]
Problem solved. LoL

Thanks a lot.

**Comment by xJon** [comment]
Press 'M' and then you can see at the bottom left the waypoints button.
Your issue is a (reported) bug in Big Reactors, a crash that causes by right clicking with a TC tool.
Closing this one :)
