### ISSUE TITLE
Modpack crashes upon joining server

### ISSUE THREAD

**Issue by Jardyn** [EnderMediaDev/The-1.7.10-Pack#815]
OK. So first of all, I believe that I should warn you that I'm not using EXACTLY this modpack. I'm using http://www.technicpack.net/modpack/the-1710-pack-ars-magica-2.607164 because I really wanted to play with the Ars Magica mod. 

That out of the way, if you're still willing to help me I'll continue. 

For a while, maybe the last week, I've been playing on my server just fine, my cousin, and a couple friends joined in as well. However last night the server crashed once and I was unable to re-join it due to an error. I'll include the logs from when I try to join the server.

If this is just because he added Ars Magica, and I'm an idiot for trying to use this, please let me know.

I'm not using optifine right now, and the server remains online. The client disconnects but the server remains running.

2015-08-03-7.log contents selection

http://paste.ubuntu.com/11995008/
 
fml-server-lastest

http://paste.ubuntu.com/11995016/

**Comment by xJon** [comment]
The logs doesn't give enough information. I may have to see the crash report of something like that, but in general you **REALLY** shouldn't use the version above.
It's out of date, buggy, laggy and doesn't have a lot of new content.
I recommend you to download the latest version of the real modpack, and add to it manually the mods that you want, things would be much better.

**Comment by Jardyn** [comment]
Alright, is there a thread floating around somewhere that gives an idea of how to add mods manually?

I've considered the idea before but I didn't believe it would be practical, considering that I want to be able to play with some other people.

Also, if I were to add some mods to it, would it be alright, so long as I give proper links and credit to the original, to post it onto the technic modpack list so that my friends could download / use it?

**Comment by xJon** [comment]
Just download Ars Magica 2, and its core mods (I'm pretty sure it requires at least one more mod).
Put the .jar files in the mods folder, of the server and the client, and it should be installed :)

**Comment by Jardyn** [comment]
Hey, sorry for the delayed response, had to go to work. Just wanted to say thanks for the quick responses. Also, what do I need to do, if anything, with the client modpack to get the mods working?

Thanks again for all the help.

**Comment by xJon** [comment]
What do you mean by that?

**Comment by Jardyn** [comment]
Sorry, I guess it was a tad unclear.

Unless I'm horribly mistaken about how modpacks work, they have to be installed on both the server and the client for the player to connect and play.

**Comment by xJon** [comment]
That's right, that's why I said:
> Put the .jar files in the mods folder, of the **server and the client**, and it should be installed

**Comment by Jardyn** [comment]
Woops, sorry about that.


I was just about to write up a whole other problem I was having, and post the log and everything. Right up until I looked at the log and realized it wasn't working because I hadn't read the EULA. So yea. I should probably work on reading more carefully.

In any case, thank you for all the help, and taking the time to reply to all of my comments. Even though some of them were just because I wasn't being entirely attentive.

**Comment by xJon** [comment]
It's okay, enjoy your game :)
