### ISSUE TITLE
Issues moving structures

### ISSUE THREAD

**Issue by joshosh34** [EnderMediaDev/The-1.7.10-Pack#816]
Hi!
 I downloaded this modpack, oh, say 8 months ago. It is really awesome!
 I have a giant Wizard Tower, Ender Quarries, the whole shabang. Only problem is, some stuff has changed in the meantime. 

I wanted to update my base a bit, and I hit a snag. I copied my base over (via mcEdit) and tried to paste it in a new world, but the game instantly crashes. 
I decided it was a bad idea to do the whole thing at the same time, so I just copied my ME System over with a solar panel.

 It turned it into granite and creative energy cells. 

So you have any idea how to copy an older base into a newer world? Clearly some number system changed during the past 8 months. I just want my stuff base to be relocated, that all. Thank you.

**Comment by xJon** [comment]
Did you think about just moving the region files that your base is located in?

**Comment by xJon** [comment]
Closed due to inactivity.
