### ISSUE TITLE
Help With the Waypoints

### ISSUE THREAD

**Issue by lordracalas** [EnderMediaDev/The-1.7.10-Pack#817]
Hi.

I know you already responded to this in my other post, but I seem to be too stupid to find it out.

I needed to know where do I manage my waypoints. As English is not my native language, I'll break this down a bit. By waypoint I mean those beacons that I believe most people use to mark terrain (their base, their mining spots and so on). I can place a new waypoint by pressing "B", and I can name it, change color, etc.

However I need to delete some old unused waypoints because it really bugs me to see them, I'm a "keep it clean, keep it simple" kind of guy.

When I asked you about this, you told me I could press "M" and there was a waypoint thing in the bottom left. But when I press "M" in my game, it open some kind of a solar system info screen (galacticraft?) where I can see all planets, the sun, the overworld (Earth) and some asteroid. No waypoint screen to be seen.

Anyways, I'm using the 0.7.9f version of the game.

Thanks and sorry for my stupidity.

**Comment by xJon** [comment]
If you're playing this modpack before a specific build that made 'M' the default button, you'll have to configure the "Minimap Menu" key manually through the controls option :)
