### ISSUE TITLE
Modpack Launches; Won't Let Me Load My World

### ISSUE THREAD

**Issue by heathxboom** [EnderMediaDev/The-1.7.10-Pack#818]
I was actually just playing the 1.7.10 Pack earlier today.  However, after I shut my laptop down, so it could rest, as well as I, when I booted my laptop back up, the modpack won't let me play.  It would get to the main screen where I could choose Singleplayer or Multiplayer, but after I choose my world, it would take me back to the Technic Launcher. 

I'm a total Minecraft noob when it comes to files and stuff that I need to provide, so please, be patient because I probably won't know where to locate the files unless you tell me where it is.  

Thank you for understanding. Help ASAP. (I don't want to start all over again).

**Comment by xJon** [comment]
There's a lot of missing information, please read [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/blob/master/README.md) :)

**Comment by challenger1** [comment]
When it takes you back to the technic launcher, that is a crash. Therefore, you can go into your crash-reports folder and look at the crash or post it on here using a paste-tool. It is found by typing %appdata% in your computer's searchbar. This will bring up a roaming folder, which brings up a .technic and .minecraft folder. Select the .technic folder, then the modpacks folder, then select the folder for the 1.7.10 pack, then open the folder titled crash-reports. You should find the crash report in there.

**Comment by heathxboom** [comment]
@challenger1 Thank you for the step-by-step process you provided.  It's definitely helpful.  @xJon thank you as well. 

Here\s the crash report: http://paste.ubuntu.com/12013760/

**Comment by xJon** [comment]
Does it happen if you generate a new world or just in this specific world?

**Comment by xJon** [comment]
Your quests data is corrupted. Remove the "HardcoreQuesting" folder inside of your save folder to reset it.
