### ISSUE TITLE
Attempting to create custom modpack using this as a base.

### ISSUE THREAD

**Issue by Jardyn** [EnderMediaDev/The-1.7.10-Pack#819]
So, as the name may imply, I'm trying to take the mods that I've installed on my client, (using this modpack as a base,) and repackage them into a private custom modpack, and put them on the technic modpack list under hidden so that only my friends I give the link to can access it. However so far my attempts have been slightly less than successful. Would someone mind helping me out?

A couple of questions I have are,

What all do I need to copy into a new folder and then zip, to be able to do this?

Does anyone know any good direct-link file hosting sites aside from dropbox (because of the bandwith limit)

Any help you can give towards this end would be appreciated!

**Comment by xJon** [comment]
As long as the modpack it's private, okay. Just be sure to provide a link back in the new one to The 1.7.10 Pack and say that it's based on it.
For more tips of how to make a Technic pack, you should see some guides on [youtube](https://www.youtube.com/watch?v=ZJ8PZ1SW0xk).
