### ISSUE TITLE
Malisis Doors awesome mod

### ISSUE THREAD

**Issue by thebalck** [EnderMediaDev/The-1.7.10-Pack#820]
Can you add this mod ?

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076338-malisisdoors-1-7-10-1-9-3-05-08-2015-see-p99-1993

**Comment by xJon** [comment]
Currently the mod won't be added, it doesn't really fit the modpack. There are a lot of ways already to customize doors.
Thanks anyway :)
