### ISSUE TITLE
ProjectRed chips crash game when editing white/blacklist

### ISSUE THREAD

**Issue by Kohlerslave** [EnderMediaDev/The-1.7.10-Pack#821]
Originally found when trying to set up a Stock Keeper chip from ProjectRed.  When I right click with the chip in hand, it opens a GUI.  On the card is one white box to click on, which opens the whitelist area.  When I try to drop an item onto the whitelist area the client completely quits out.  While playing on a server, the server is fine, but the client crashes.  Tested with other chips with same result.  Tested on 0.7.9d and 0.7.9f.

Crash report:  http://pastebin.com/zSd7c3W7

Previous to this report, I used NEI to give myself 1 cobblestone and one Stock Keeper Chip.

This is from an SSP world, but I'm pretty sure its the same error when connected to a server.  If you need the full log, I'll either have to paste it in chunks or find some other way to do it.

**Comment by xJon** [comment]
Fixed in the next release of ProjectRed

**Comment by Kohlerslave** [comment]
Thank you!

**Comment by xJon** [comment]
Should be fixed in v0.8.0 of the modpack.
