### ISSUE TITLE
Starting Issue with new Technic Launcher

### ISSUE THREAD

**Issue by ayrex** [EnderMediaDev/The-1.7.10-Pack#822]
Yesterday all worked fine. Today I wanted to start the 1.7.10 Pack again but the Technic Launcher won't start it.

I tried to delete and reinstall but without any issues fixed.

8GB RAM is for Java reserved.
The 1.7.10 Pack Version: 0.7.9f
Java 8 64 Bit Version

The problem is probably:
[B#310]  [17:41:41] [main/ERROR] [LaunchWrapper]: Unable to launch
[B#310]  java.lang.reflect.InvocationTargetException
[B#310]  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_45]
[B#310]  	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[B#310]  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_45]
[B#310]  	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_45]
[B#310]  	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
[B#310]  	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[B#310]  Caused by: java.lang.NullPointerException
[B#310]  	at net.minecraft.client.main.Main.main(SourceFile:116) ~[Main.class:?]
[B#310]  	... 6 more
[B#310]  Exception in thread "main" [17:41:41] [main/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException
[B#310]  

For more information see the logs attached.

Launcher Logs:
http://paste.ubuntu.com/12021846/

fml-client-latest.log
http://paste.ubuntu.com/12021871/

Hope somebody has a clue where the problem is :) It's maybe a general issue.

**Comment by challenger1** [comment]
I'm having the same issue: Yesterday I was having memory problems that finally got solved, and now today it won't launch.

**Comment by heathxboom** [comment]
Same.  It was working fine for me yesterday, and now, mine won't even get to the minecraft loading screen.  sigh.

**Comment by xerobeagle** [comment]
Having the same issue on my windows machine, since the launcher update.
On my linux machine I get "An error occurred while attempting to reach authserver.mojang.com

**Comment by ayrex** [comment]
I tested Tekkit. Tekkit is working fine. :)

**Comment by challenger1** [comment]
Are other player-made modpacks working?

**Comment by jmattspartacus** [comment]
Same issue here, log is here
http://pastebin.com/TdQwSu19

**Comment by ayrex** [comment]
Installed and tested Official Crafting Dead. (Installed, started, created world and moved a bit)

That one is also working.

**Comment by jmattspartacus** [comment]
Same Issue with several other pack. don't know if this will help but here is a log from trying to start one of those
http://pastebin.com/TdQwSu19

**Comment by challenger1** [comment]
Ultra Modded-Survival (The one with the slime on the front) doesn't work. Same problem as 1.7.10 pack.

**Comment by fabjoueur** [comment]
Same problem here ! :( 

All was fine until this morning :(

I'm running the 1.7.10 pack with the tekkit launcher 0.7.9f with java 1.8.0_51
Windows 10 64 bits - 8Gb ram 
 
Here's my logs : 
FML : http://pastebin.com/dpJ5AbE0
Tekkit launcher log : http://pastebin.com/ydBXB4Wp

Can someone help us please ?!

**Comment by fabjoueur** [comment]
I just test the "FNL - Realistic life" and i have the same problem with it too ! 

It appears that every mod pack running the 1.7.10 version of minecraft is kind of buggin ! Can someone confirm ? 

Thanks

**Comment by heathxboom** [comment]
it works for me now.

**Comment by Binero** [comment]
Using a downgraded version of the launcher did it for me.

**Comment by fabjoueur** [comment]
@Binero  Downgraded in which version ? :)

**Comment by Binero** [comment]
Not sure.

**Comment by fabjoueur** [comment]
the 0.7.9e seems to work here

**Comment by LordThyne** [comment]
I went into Appdata, where the files are, found the .technic folder and ran a file called "temp.exe"
which started the launcher, and loaded 1.7.10 when I ran it.

**Comment by ayrex** [comment]
I restarted the launcher recently. And now the issue seems to be fixed. I think it was not a problem with the mod pack but with the technic launcher.
But thank you all for discussing! :+1: 

If nobody else has an issue with starting the 1.7.10 pack, this thread can be closed :)

**Comment by xJon** [comment]
:+1:
