### ISSUE TITLE
Your os has prevented this relaunch from completing.

### ISSUE THREAD

**Issue by JosephPlayzGamez** [EnderMediaDev/The-1.7.10-Pack#824]
I am having issues starting the launcher. I am on a mac. I have the newest version of java. I try to launch the launcher and i am met with a screen reading: Your OS has prevented this relaunch from completing. You may need to add an exception in your security software. I have no security software. And my firewall is down. I have allowed the download site in java preferences. Any help would be greatly appreciated.

**Comment by xJon** [comment]
So basically you can't even launch the Technic Launcher?

**Comment by xJon** [comment]
Closed due to missing information.
