### ISSUE TITLE
Major FPS issues.

### ISSUE THREAD

**Issue by Jardyn** [EnderMediaDev/The-1.7.10-Pack#825]
Hey, so I'm trying to run a server and a client on my computer, giving each one about 6gbs to work with out of my total 16, leaving 4gb open for other things that my computer needs to do.

In my mind this sounds reasonable but maybe it's not, I don't know.

I'm running optifine, and even on a single player server I'm lucky to get over 20 FPS when I'm moving around. If I stand still it'll go up to 30 or so, but when I move it just tanks back down to about 10-15.

If anyone can give me any ideas as to what to try to boost it, I'd love the help.

Running Java 1.8.0u51

EDIT: Nvidia GeForce 765 m 2gb if that's relevant

**Comment by Jardyn** [comment]
I'm going to go ahead and mark this as closed, for anyone having this sorta problem, I found a temporary fix for it. If you're running windows, (I'm on windows 10 right now) go to your task bar and, at least while you're playing, CLOSE windows explorer. Reason being as long as it's open, windows explorer will reserve a certain amount of ram for running stuff like your desktop.

After you finish playing, just open a task manager instance, create a new task and start explorer.exe and start it back up.

This has created a DRASTIC improvement for me as my FPS went from 10-20 to 50-60 at full graphics.

Hope this helps someone!

**Comment by xJon** [comment]
:+1:
