### ISSUE TITLE
Induction matrix mixup input/output

### ISSUE THREAD

**Issue by Vliro** [EnderMediaDev/The-1.7.10-Pack#826]
In previous version(0.7.9c I think) the induction matrix providers defined the max output of the matrix. Now it also defines how much it can take as input. Is this acting correctly or is it a bug?(0.7.9f it acted like this.)

**Comment by xJon** [comment]
It depends with the way you use it.
Pretty sure it's not a bug, as we didn't update Factorization between those versions of the modpack :)

**Comment by Vliro** [comment]
I mean the Mekanism Induction matrix(is it related to Factorization?). Anyways I tested creative and my fusion reactor could output at 13.1M RF for the ultimate provider, however only 25.6krf/t when it was basic. :<

**Comment by xJon** [comment]
Oh, I'm sorry. The Mekanism Induction Matrix may have changed between v0.7.9c -> v0.7.9f, we did update Mekanism. Still I'm not sure if it's a bug, but it's definitely mod-related.
You can go to the Mekanism GitHub repo to report this :)
