### ISSUE TITLE
Wireless Terminal on powerfists.

### ISSUE THREAD

**Issue by ramorga** [EnderMediaDev/The-1.7.10-Pack#827]
Every time I attempt to access my ME network via a wireless terminal attached to my powerfist, the game simply crashes. I can't attest to whether or not this is happening with a normal wireless terminal.  Thought maybe it was a RAM issue at first, since rain pushes the games ram usage to nearly 3G, and so I doubled the amount of RAM available.  Anyone else having any issues like this?

**Comment by xJon** [comment]
Unfortunately the QMX version of MPS is not updating any more, and it uses an old API of AE2 which may cause crashes. Nothing we can really do about it, but because you pointed this out we'll disable the AE2 module in the config file for the next update. :)
