### ISSUE TITLE
1.7.10 Pack freezing and crashing.

### ISSUE THREAD

**Issue by yoolee** [EnderMediaDev/The-1.7.10-Pack#828]
Hi,

Every time I log onto a whitelisted 1.7.10 pack I go on it starts freezing after a minute or two if I either open my inventory or open a chest or even just walk around, Any ideas why this is happening, sometimes this does not happen but most of the time it does. Also it never gives a crash report.

Thanks.

**Comment by xJon** [comment]
Can you please provide the fml-client-latest.log file?
Use a [paste-tool](http://paste.ubuntu.com/).

**Comment by yoolee** [comment]
Here is the crash report as I managed to find it http://pastebin.com/hdD4mgn8

Here is the latest log for the 1.7.10 pack http://pastebin.com/5ndGRNaK

If none of those are what you asked for them please tell me.

**Comment by xJon** [comment]
Your crash report is due to a missing core mods, did you change anything there?
Your latest log doesn't show any error.

**Comment by yoolee** [comment]
Hi,

I have the latest version of java 8 installed.

The freezing started two days ago, I log on and I just start going through my chests and crafting items and then after a few minutes it will start to freeze and then make my computer extremely laggy. I have been trying to think of any of the causes for this but I am not sure yet.

**Comment by xJon** [comment]
The crash report shows that you're using Java 7.
Anyway, if you were freezing in a specific session, I need that session's log, not just a normal log.
Try to reproduce the freeze and then give me the latest log

**Comment by yoolee** [comment]
Okay, once I can I will log onto that server as it should freeze after a few minutes of being on and then I will give you the log, and I have realized that the java I checked was only for google chrome so I will update that and see if it helps.

**Comment by yoolee** [comment]
Hi,

I just tried to log into the server and it crashed. What happens is that the minecraft world appeared making it look like it worked but then after a few seconds it crashes. Here is the latest crash report.

http://pastebin.com/4Hc7bn5E

**Comment by xJon** [comment]
Did you try to reinstall the modpack?

**Comment by yoolee** [comment]
Actually I stupidly have not tried that yet, I will try it now and then tell you what happens.

**Comment by yoolee** [comment]
Hi, after reinstalling the 1.7.10 pack and also installing java again everything is working fine and I have not been crashing after playing for three hours. Thanks for all the help I appreciate it a lot :+1:

**Comment by xJon** [comment]
:+1:

**Comment by freemanovec** [comment]
I have the same problem, client freezes after a few minutes of playing (server still runs (LAN multiplayer)).
No error in any log.
Reinstalling worked for around one hour, then the crashing started again.
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Any ideas?
