### ISSUE TITLE
The Client has sent too many requests within a certain amount of time.

### ISSUE THREAD

**Issue by Jardyn** [EnderMediaDev/The-1.7.10-Pack#829]
Been struggling with this error for the past day or two, I was exploring one day, my client crashed out, and since then I haven't been able to get into the server and stay on for more than a few seconds at a time.

http://paste.ubuntu.com/12068187/

If anyone has any ideas as to the source of this error, I'd love to hear them.

Thanks in advance!

**Comment by xJon** [comment]
This is not a real error, you'll see this in any modpack that has Morph.
If you are really having trouble try to give me your crash report.

**Comment by Jardyn** [comment]
Hey sorry about the delayed response. I've been doing a lot of troubleshooting on the #technic IRC channel.

We're all stumped.

FML-Client-Latest:

https://www.dropbox.com/s/lfgissyp4v200hw/fml-client-latest.log?dl=1

Latest client crash report:

http://paste.ubuntu.com/12075098/

**Comment by xJon** [comment]
Hah, yes, I'm aware, I was online there :)
- Do you use KCauldron on your server?

**Comment by Jardyn** [comment]
I do not use KCauldron,

I have a couple of additional mods.

- ChocolateQuest 

-Security Craft

I DID have MCA but I uninstalled that.

- Movingworld for archimedes ships, (uninstalled)

- Optfine

- Ruins

- Underground Biomes and Underground Biomes Constructs

And Worldedit.




And the version would probably be 0.7.9f

**Comment by xJon** [comment]
Well it's pretty simple to say that one of your additional mods are giving you trouble in your server. Nothing is too obvious in the log but you should simply remove them one by one until you find it. :)

**Comment by xJon** [comment]
Closed due to inactivity.
