### ISSUE TITLE
server crash after update to 0.7.7f

### ISSUE THREAD

**Issue by imsupermario** [EnderMediaDev/The-1.7.10-Pack#830]
hi , we recently upgraded our server from 0.7.7b to 0.7.9f 
Our friends came and celebrate this great update,we ordered pizza and smoothies ,
then this happened in slow motion.

Please kindly read the crash report 
http://paste.ubuntu.com/12070221/

fml server latest
http://paste.ubuntu.com/12070276/

**Comment by xJon** [comment]
You're missing the Aroma1997 Core mod.
