### ISSUE TITLE
MAC: Click play, bar finishes, crashes before game pops up

### ISSUE THREAD

**Issue by sillysurfer123** [EnderMediaDev/The-1.7.10-Pack#832]
This pack looks so fun but I can't play it. I click play and then the progress bar finishes loading, the icon in the bar at the bottom (in image) of my screen pops up then disappears (crashes) before the game pops up. Please help. I have tried redownloading, it doesn't work.
![screen shot 2015-08-13 at 11 47 00 pm](https://cloud.githubusercontent.com/assets/13791510/9266921/9c72b35e-4215-11e5-98c5-b0ac11b7d6ef.png)

**Comment by xJon** [comment]
Crash log? Please use a paste-tool

**Comment by sillysurfer123** [comment]
There is no crash log, it just doesn't open.

**Comment by xJon** [comment]
Can you please give the fml client latest log?

**Comment by xJon** [comment]
Closed due to missing information.
