### ISSUE TITLE
Chunks rolling back..

### ISSUE THREAD

**Issue by ExillDan** [EnderMediaDev/The-1.7.10-Pack#833]
Hi, i have a problem that one of the chunks in my world "wifes base center chunk" has began to roll back when it becomes unloaded, shes ok to do her thing but if she goes adventuring far away n comes back, previous work to the base has been undone.

all the info i have is ..
we run a 0.7.9f server with a few friends.
awhile ago a chunk with an Applied energistics network became corrupt n had to be deleted, the only AE network on ourserver atm is in the chunk thats now not saving.
a chickenchunks chunk loader has been used there in the past.

**Comment by xJon** [comment]
If it's rolling back it's a corrupted chunk.
Try to remove some of the stuff that you think may cause it, I can't do anything else.
If you want you can provide the fml-server-latest.log file and maybe we'll find more info there, but I don't think we can do more. Closing it for now.
