### ISSUE TITLE
Crashes when finished loading world.

### ISSUE THREAD

**Issue by Vaxorion** [EnderMediaDev/The-1.7.10-Pack#834]
http://pastebin.com/PkRBfXfE

This suddenly started happening. I was the playing the game and decided to stop. After a few days, I came back and I couldn't load the world. Please help.

I tried to load a different world and it worked.

**Comment by Vaxorion** [comment]
This suddenly started happening. I was the playing the game and decided to stop. After a few days, I came back and I couldn't load the world. Please help.

**Comment by xJon** [comment]
You're playing on a server?

**Comment by Vaxorion** [comment]
No.

**Comment by xJon** [comment]
Do you have any additional mods?

**Comment by Vaxorion** [comment]
No.

**Comment by xJon** [comment]
Try to update your Java, it wouldn't hurt :)

**Comment by Vaxorion** [comment]
Why would it be Java if I could load another singleplayer world without a crash?

**Comment by xJon** [comment]
I don't think that Java is crashing you but it's just one more thing that you should do.

**Comment by Vaxorion** [comment]
I have the latest version of Java, Version 8 Update 51.

**Comment by xJon** [comment]
The crash report shows Java 7, did you update now?

**Comment by Vaxorion** [comment]
No, I downloaded the latest version a few weeks ago.

**Comment by xJon** [comment]
In the Technic Launcher, double check that you're using the Java version that you want.

**Comment by Vaxorion** [comment]
I am using the version I want which doesn't work. And the other versions available don't work.

**Comment by xJon** [comment]
Is this still a problem?

**Comment by xJon** [comment]
Will reopen with the required info.

**Comment by Vaxorion** [comment]
Can't find a paste site that won't have an error, or say my paste is too big :/

**Comment by xJon** [comment]
Use [this](http://paste.ubuntu.com/) paste-tool :)

**Comment by Vaxorion** [comment]
http://paste.ubuntu.com/12225562/

**Comment by xJon** [comment]
I can't seem to find the crash in this log, sure it's the right one?
(it should have the crash report AND more information)

**Comment by Vaxorion** [comment]
I copied the text from "fml-client-latest",

**Comment by Vaxorion** [comment]
I think that was the wrong one.

**Comment by Vaxorion** [comment]
If so, where could I find the right file?

**Comment by xJon** [comment]
Try again to load and if you crash, take then the fml-client-latest.log file :)

**Comment by Vaxorion** [comment]
http://pastebin.ubuntu.com/12225674/

Crashed.

**Comment by xJon** [comment]
Can you try to load the world with v0.8.0 of the modpack?

**Comment by Vaxorion** [comment]
I'll try.

**Comment by Vaxorion** [comment]
Crashed again...

**Comment by xJon** [comment]
Same crash report?

**Comment by Vaxorion** [comment]
Not sure what to look for. But you can check.

http://paste.ubuntu.com/12225838/

**Comment by xJon** [comment]
Try to reset the "EnderStorage" folder inside of your save folder (simply delete it).
It might delete your EnderStorage content, but it might make your world launch again :)

**Comment by Vaxorion** [comment]
Still crashed :/

**Comment by xJon** [comment]
Can you provide the crash report now?

**Comment by Vaxorion** [comment]
It worked. Thank you so much!

**Comment by xJon** [comment]
Had to give some credit to @bochen415
Enjoy! :)
