### ISSUE TITLE
InfiniteInvo Suggestion

### ISSUE THREAD

**Issue by PianoManDK** [EnderMediaDev/The-1.7.10-Pack#837]
Hey! Love the modpack, it's awesome. But with sooo many awesome items it's a pain to let go of so many when adventuring. (And it's not very handy to have the hotbar filled up with backpacks...)
So, could you please consider adding the mod "InfiniteInvo" to your glorious modpack?
I realize some players might reckon this mod as "cheating", but they can always disable the mod.
Here's a link:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2336005-infiniteinvo-all-the-inventory-space-a-player

(Sorry if this is the wring way of posting a suggestion... I might be called a noob amongst some. xD

Thanks and much love, 
PianoManDK

**Comment by PianoManDK** [comment]
Thanks xJon. cx

**Comment by xJon** [comment]
Well technically you got it just about right.
Some and maybe a lot can call the mod "cheating" and just as they can always disable the mod manually, you can "enable" the mod manually for your own use.
It is a cool mod but it doesn't really fit such a modpack like ours, that wants to provide the survival aspect while trying to keep it [balanced](https://github.com/EnderMediaDev/The-1.7.10-Pack/issues/812).
Thank you anyway for your suggestion and feedback :)
