### ISSUE TITLE
Compact Solar Panels

### ISSUE THREAD

**Issue by cksantos85** [EnderMediaDev/The-1.7.10-Pack#839]
Suggestions for new mods include 

Advanced Solar Panels Addon : allows for solar panels and other upgrades that make IC2 more enjoyable in the endgame.

And Dartcraft once bluedart finished updates for 1.7.10

Also a map that could view the entire overworld would be nice.

**Comment by xJon** [comment]
Adding "Advanced Solar Panels" is a bit useless, as we have Compact Solar Panels.
Same for a "map" as we have the "VoxelMap".
As for Dartcraft, it's currently not even updated to 1.7.10, so there's not much to talk about anyway.
Thanks for suggesting :)

**Comment by cksantos85** [comment]
Compact solar panels does not have a molecular transformer which is the pinnacle of IC2 add on tech. Extremely useful and just all around cool. I dont really use the solar panels as big reactors is more productive. As an alternative mod to advanced solar compact solar is not as good due to lack of molecular transformer. Please give this serious consideration. Right now you have one of the best mod packs and the only thing i can see missing is the molecular transformer. Will donate for addition.

**Comment by xJon** [comment]
About the map - change the hotkey of "minimap menu" in the controls manu :)

**Comment by cksantos85** [comment]
Got the hotkey changed it was double mapped. Thanks for the tip. What do you think about adding the molecular transformer?

**Comment by cksantos85** [comment]
Ive talked to many on a few 1.7.10 servers and i am hearing a lot of support for the molecular transformers. Quite a few also suggested Chromaticraft. Also the old techworld server is dieing, and your pack is the most similar.

**Comment by xJon** [comment]
Currently won't be added. The mod is cool but its time has pass.
Thanks anyway for suggesting.

**Comment by xJon** [comment]
Advanced Solar Panels has been added in version `0.10.5`!
