### ISSUE TITLE
Not Enough Items (Help Needed)

### ISSUE THREAD

**Issue by lordracalas** [EnderMediaDev/The-1.7.10-Pack#840]
Hi.

So I accidentally deactivated the mod that shows the item names when they are placed in the world, it turned out to be a part of Not Enough Items. I was able to reactivate part of it (the part which shows you the name), but I wasn't able to find out how to reactive the other part, where it shows you which mod it is from and which tool to harvest, and if it is in fact harvestable.

It's important to note I'm not talking about when I press "e", I'm talking about when I'm exploring and I hover the crosshair on any item.

Anyone can tell me where can I reactivate this part? Thanks a lot.

**Comment by xJon** [comment]
Are you talking about WAILA? How did you manage to deactivate it? Did you remove the mod?

**Comment by lordracalas** [comment]
I looked it up and yes, turns out it's not NEI, it's WAILA. I have no idea how I did it but it's not showing up in my game anymore.

Recently I installed PureBDCraft Texture pack for 1.7.10, maybe I messed up some configuration?

**Comment by xJon** [comment]
No. Maybe you just turned it off with the hot key. Check your controls menu.

**Comment by lordracalas** [comment]
Yes, I will.

At least now I know what I'm looking for, as I know the name of the specific mod.

Thanks again for the awesome support you provide for the pack. Better than any company I needed support so far.

Keep up with the brilliant work.

**Comment by xJon** [comment]
:+1:
