### ISSUE TITLE
Server keeps crashing when I attempt to start

### ISSUE THREAD

**Issue by jailbreaker1220** [EnderMediaDev/The-1.7.10-Pack#841]
Upgraded to newest recommended version. Windows 7. Here is what it says in the crash log. It seems to work fine if I make a new world, however I would like to keep the old world as I have a lot of time invested in it.

**EDITED: Please use a paste-tool: http://pastebin.com/DfNypHKL**

**Comment by xJon** [comment]
Your questing data on the server is corrupted. Reset it in your save file :)
