### ISSUE TITLE
Adding Cauldron to 1.7.10 Modpack

### ISSUE THREAD

**Issue by Sayntly** [EnderMediaDev/The-1.7.10-Pack#842]
Attempting to add cauldron to your modpack, after extensive amounts of research, configuring, and many attempts I have been unable to get the server to start after applying cauldron. 

I have moved over libraries, downloaded the correct version of cauldron and tried to launch.
the only message I receive is:

A problem occurred running the server launcher, press any key to contineu. . .

If I remove all mods the server will start and it will create the plugin folder but once I add my mods folder back the server refuses to start. I have 6 G allocated to the server and 8 G allocated to java so I know that is not the issue. Any help at all would be appreciated. Thank you

**Comment by Sayntly** [comment]
I believe I found the issue, there doesn't appear to be a version of cauldron for forge 1488...

**Comment by xJon** [comment]
You need to have Cauldron for the version of Forge that the version of the modpack uses.
Also you need to remove some incompatible mods, such as ColorChat and FastCraft, maybe also NotEnoughResources.

**Comment by Sayntly** [comment]
I actually just did that, I removed Fast craft, and notenough wasnt aware of colorchat BUT when I run the server it says that it needs forge version 1488 

I will delete color chat and repost with results

**Comment by Sayntly** [comment]
Same think, looks like the latest version of Cauldron isnt compatible with Forge 1488 Mods

**Comment by xJon** [comment]
Give me the latest log and I'll tell you what the problem is

**Comment by Sayntly** [comment]
I resolved it! thanks for the help. I ended up needing KCauldron-1.7.10-1492.152

**Comment by Sayntly** [comment]
are there any plugin conflicts or anything I should watch out for?

**Comment by xJon** [comment]
Not sure.

**Comment by TerdyTheTerd** [comment]
I know this was already closed, but I thought I would share some info, if for whatever reason you need to use forge 1448(like for shaders mods on the client) but you still need 1492 features, or specifically the dragonAPI patch that KCauldron introduced after 1448, then you simply need to clone the backport 1448 from github and compile a new branch and then use the 1492 libraries with the jar that you create. Useful for keeping forge at 1448 while running mods that need forge 1492 implementations.

**Comment by Sayntly** [comment]
I understand what your saying but as for actually knowing HOW to do it I'm not actually familiar with that :/

I understand why we use kcauldron and what it does, I just have no experience in changing it.
