### ISSUE TITLE
Server overload

### ISSUE THREAD

**Issue by Neology2k** [EnderMediaDev/The-1.7.10-Pack#846]
Getting a lot of issues since updated to pack_0.7.9f

![Image of lag](http://i.imgur.com/lp2DxT4.png)

System Specs:
2x Intel Xeon E5530 @2.4Ghz
24Gb Ram
2TB 7200RPM HDD
100mbit connection
Usage in screenshot:
![Image of taskman](http://i.imgur.com/ZJXDJrm.png)

Tried tweaking startup file to fix;
http://pastebin.com/yhPWXnd9

World size: 2.42GB

**Comment by xJon** [comment]
I need your fml-server-latest.log file, post it [here](http://paste.ubuntu.com/).

**Comment by xJon** [comment]
Closed due to missing information. Will reopen with the required info.

**Comment by Neology2k** [comment]
Sorry, the log is too big, haha. Will get one soon. Apparently Its something to do with other dimentions, as the issue (kind of) resolves when paying them all a visit. The main message I see in that log is:

[00:47:44] [Server thread/DEBUG] [FML/]: The world 9665164 (world) may have leaked: seen 28710 times.

**Comment by xJon** [comment]
> may have leaked

A casual message by ChickenChunks. I need the log :P

**Comment by Neology2k** [comment]
http://paste.ubuntu.com/12271920

**Comment by Neology2k** [comment]
To be fair, this looks a lot more clean than the original logs. I fixed my console spam by visiting each dimension at loadup..but Now i'm getting complaints of Bad FPS.. works fine for me, so hard to diagnose.

**Comment by xJon** [comment]
I can't see anything wrong in your log.
FPS problems are mostly client-only (unless the server is overloaded - which it isn't, with this log).
You can try to manually install Optifine on your clients to help that :)

**Comment by Neology2k** [comment]
any idea on this log?
http://paste.ubuntu.com/12273044/

**Comment by xJon** [comment]
You do have a repeating error from AromaBackup & CodeChickenLib on saving chunk data.
Try to report it directly to both authors, you might get more information there.
The 1.7.10 Pack uses the latest versions of both mods.

**Comment by xJon** [comment]
Closed due to inactivity.
