### ISSUE TITLE
Need a sugestion

### ISSUE THREAD

**Issue by lordracalas** [EnderMediaDev/The-1.7.10-Pack#847]
Hello.

I'm not a hardcore minecrafter so I don't know how to use most of the mods in the pack. Shame on me.

However I've been trying to learn and I need someone to point me in the right direction with a challenge I'm currently facing.

I want to realocate my whole base to another site, more than 1km far away, without using Mekanism's teleporters (to personally move my items between portals) because they are really expensive to me. I've set up my game to not be able to use cheats.

I tried to use the "mining world dimension" from aurora1997 mod as an anchor, with a fixed portal in my old base and a bed and a portable portal in my hand, so I could fast travel to my two bases. I ended up learning that when you sleep in another location in the Overworld and you use your portable portal there, you spawn in a completely different location in the mining dimension as well, much like using two nether portals.

So I need a suggestion of a way to either move all my s*** to the other base or a way to make cheaper portals. I have a lot of resources and power generation, except for dem diamonds.

Thanks a lot. =)

**Comment by xJon** [comment]
WARP BOOK!

**Comment by lordracalas** [comment]
Thanks brother.

It's not much about lazyness as it is limited resources. hehehe

**Comment by xJon** [comment]
:+1:
