### ISSUE TITLE
getting error - java.lang.RuntimeException:

### ISSUE THREAD

**Issue by ziba1** [EnderMediaDev/The-1.7.10-Pack#848]
Hi, just updated the pack on my server to 0.7.9f which is the recommended version, and haven't been able to start my server at all, with the help of the server owner I found out that I was getting this error message:

"java.lang.RuntimeException: A defective recipe has crashed the game! Another mod is creating recipes with non-existent blocks or items, which is a serious error that will cause item or even world loss when crafting these recipes. Corrupted recipes have been saved in the log with tag [HEE-ORB], please try to find which mod they belong to and report them to the respective modder. Then enable the 'overrideRemoveBrokenRecipes' option in Hardcore Ender Expansion and the game will start."

here are the logs

http://paste.ubuntu.com/12176316/

http://paste.ubuntu.com/12176357/

in the second log, line 31846 shows the hee-orb that the error refers too, but tbh, I have no idea what to do with that, I dont know how you activate that "overrideRemoveBrokenRecipes" that the error suggests I do.

so any help would be fantastic :P

**Comment by xJon** [comment]
Go to the config folder and enable "overrideRemoveBrokenRecipes" in Hardcore Ender Expansion. :)

**Comment by ziba1** [comment]
Ok, that solved the problem of it not starting, but now the server keeps kicking me for a fatal error has occured message, the log tells me this just before I am kicked

[23:18:10] [Server thread/INFO]: zibafu lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Une connexion Ã©tablie a Ã©tÃ© abandonnÃ©e par un logiciel de votre ordinateur hÃ´te], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}

**Comment by xJon** [comment]
Are you playing with KCauldron?

**Comment by ziba1** [comment]
I dont know what that is tbh, so I would assume no

**Comment by xJon** [comment]
Can you please post your full fml-server-latest.log (with a pastetool)?

**Comment by ziba1** [comment]
sure, give me a moment, my friend on the server reckons its his glider somehow, since its happening around the times hes using it

**Comment by ziba1** [comment]
ok here it is

My friend has stopped using the glider for a moment and I seem to be staying online

http://paste.ubuntu.com/12178414/

**Comment by ziba1** [comment]
oh and its the ender io glider upgrade he thinks is the problem

**Comment by xJon** [comment]
If so, try to report it to EnderIO's repo, they'll help you there :)

**Comment by ziba1** [comment]
who what where is that haha, cheers btw

**Comment by xJon** [comment]
https://github.com/SleepyTrousers/EnderIO/issues

**Comment by ziba1** [comment]
Cheers, posted there.

**Comment by xJon** [comment]
Also in v0.8.0 of the modpack we updated EnderIO, you should check that :)

**Comment by ziba1** [comment]
ahh, will do.
