### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by TheLegend714** [EnderMediaDev/The-1.7.10-Pack#849]
So how do you update all the mods since there is like a hundred because since I have a "different" launcher I'd like to update them individually if you don't mind thanks!

**Comment by xJon** [comment]
I'm sorry but there's no support for cracked/modified launchers!

**Comment by TheLegend714** [comment]
But I was wondering how do you update the mods? Like with a updater or something if not its fine.

**Comment by xJon** [comment]
Updating mods is downloading newer versions and replacing the old ones.
