### ISSUE TITLE
Pack will not update

### ISSUE THREAD

**Issue by shellieperry** [EnderMediaDev/The-1.7.10-Pack#850]
There have been a few updates to the 1.7.10 pack and the technic launcher shows that an update is available but for some reason, this pack will no longer update. Can you tell me if there is something new I need to do in order to get the pack to update? It used to be that I would just click the "Play" button and I would get a notification saying that an update is available with the option to install the update. Now, it ignores the update and goes straight to the game.

**Comment by Dommain** [comment]
1. Set to latest version to play 8.0.
2. Ensure you are actually logged in and online in technic launcher
3. If you are blocking certain IP addresses, it will not update in the two spots where it has to download and update.
(54.231.13.136:443)
(107.21.214.189:443)
(107.22.227.179:443)

**Comment by shellieperry** [comment]
Thank you so much. I can't believe it was as simple as setting to the latest version. Have a wonderful day.

**Comment by xJon** [comment]
:+1:
