### ISSUE TITLE
"Khendrel Keght" from Ender Zoo

### ISSUE THREAD

**Issue by Dommain** [EnderMediaDev/The-1.7.10-Pack#851]
http://forum.feed-the-beast.com/threads/1-5-0-1-7-0-dirt-blocks-randomly-spawning-khendrel-keght-from-ender-zoo.105040/

Can we get the amount of spawning monsters "Khendrel Keght" from dirt to 1% or lower compared to default 65%?

**Comment by xJon** [comment]
Where exatly in the config file it's set to 0.65?

**Comment by Dommain** [comment]
C:\Users\##############\AppData\Roaming\.technic\modpacks\the-1710-pack\config\enderzoo\EnderZoo.cfg

D:direSlimeChance=0.2

20% chance it is set to........Just a suggestion to set it lower.....

**Comment by xJon** [comment]
Are you talking abotu Dire Slime or Khendrel Keght?

**Comment by xJon** [comment]
0.2 is the current default, after they lowered it. It's okay for now, if we'd get more reports we'll change it globally.
For now you can change it for yourself.
Thanks anyway for the feedback :)
