### ISSUE TITLE
Possible QuestingData Issue

### ISSUE THREAD

**Issue by XaviorPenguin** [EnderMediaDev/The-1.7.10-Pack#853]
Minecraft Server Crash Report: http://pastebin.com/s2g9QH7t
McMyAdmin Log File w/Error: http://pastebin.com/eQYggt87

Issue: After upgrading from 0.7.9f to 0.8.0, I get a prompt in McMyAdmin of http://pastebin.com/vHerb2XA . (As a note, I did delete the mods, Flan, config directories and extracted those same directories from the 0.8.0 zip file in their places. Did that exact same thing for the other 0.8.x versions with no trouble whatsoever.)
I don't get a chance to say /fml confirm, it goes ahead and does it for me anyway. After a little bit of time passes, the server returns the error above and restarts for up to 5 times per McMyAdmin rules.

OS: Windows Server 2012 Essentials
RAM: 8GB, 4GB Allocated to the 1.7.10 Modpack
Java: Java 8 Update 51 (Using -server switch for McMyAdmin for better performance)
MCMA Version: 2.5.4.0
Modpack version: 0.8.0 Latest

If you need anything else in terms of logs, please let me know what file and where to get it and I will be more than happy to help.

**Comment by XaviorPenguin** [comment]
fml-server-latest.log: http://pastebin.com/cA0GDjTP
Figured I would do this as I saw a request on this from another user on a completely different issue.
I did not run McMyAdmin on this one, I used the included .bat file to run and this is a fresh log file from said execution.

**Comment by xJon** [comment]
http://pastebin.com/vHerb2XA
This is nothing. Also you didn't have the chance to say /fml confirm because it's automatic with the .bat file included.

About your crash - maybe some of the changes to the existing quests did something bad with your specific questing progress. You can just reset it in your save folder :)
Most of the quests are detect quests so it shouldn't be too hard to go back to the point you were in.

**Comment by XaviorPenguin** [comment]
Thank you for the info. I renamed the files in the HardcoreQuesting folder to say, .disabled, and it booted up just fine with no other issues. Thank you again for the assistance.

**Comment by xJon** [comment]
:+1:
