### ISSUE TITLE
carpenter blocks will not craft

### ISSUE THREAD

**Issue by fugufish** [EnderMediaDev/The-1.7.10-Pack#854]
carpenter blocks do not seem to craft. In creative mode I can give them to myself, but as soon as I open the inventory or try to place the block it disappears from inventory.

**Comment by xJon** [comment]
Tested both on client and server and I can craft them normally in a crafting table.
Closing this one.

**Comment by fugufish** [comment]
any idea what would cause this on a fresh install of the server?

**Comment by fugufish** [comment]
tested locally and it works, im starting to think my server is all sorts of messed up, though this is literally a fresh upload. I will try resetting entirely

**Comment by xJon** [comment]
:+1:

**Comment by fugufish** [comment]
it persists on brand new upload, no configuration changes.

**Comment by xJon** [comment]
What version of the modpack?

**Comment by fugufish** [comment]
0.8

**Comment by xJon** [comment]
Can you try anyway to upload a video or something?

**Comment by fugufish** [comment]
i'm running on linux for my client, don't know of any way to do that on that platform, I can however just allow you to access it if that will work.

**Comment by xJon** [comment]
Did it work for you in previous versions?

**Comment by fugufish** [comment]
Yes, however, I haven't run your modpack since 0.5 or so. Just recently returned to it. I can try an run 0.7.9 and see if it exhibits the same.

**Comment by xJon** [comment]
Are you running your old world?

**Comment by fugufish** [comment]
nosir

**Comment by fugufish** [comment]
hah 0.7.9f crashes on linux

**Comment by fugufish** [comment]
re uploaded 0.8, new world all fresh configs. I can give myself the carpenter block in survival mode, I can even place it but as soon as it is placed it disappears as do all other caprenter blocks in inventory.

**Comment by fugufish** [comment]
make that all mod blocks

**Comment by fugufish** [comment]
i am assuming all symptoms combined that the server is not loading the mods, now looking at the logs I can see that none of the mods are loaded for some reason.

**Comment by fugufish** [comment]
bleh, my server wasn't starting forge. it was starting vanilla. My many apologies for my noobishness :D

**Comment by xJon** [comment]
Derp!
