### ISSUE TITLE
Autoswitch and Soul Gems Reborn?

### ISSUE THREAD

**Issue by MrKioFlow** [EnderMediaDev/The-1.7.10-Pack#855]
I personally use both of these mods on a regular basis and would love if they were added in officially. I see no need not to as they are both respectable and appropriate for the theme of this pack, unless you guys like the current method of spawners from other mods.

**Comment by xJon** [comment]
The mods don't really fit the modpack's theme.
Autoswitch totally changes the gameplay and not all players would want that.
Thanks anyway for suggesting :)
