### ISSUE TITLE
Add SecretRoomsMod and MalisisDoors

### ISSUE THREAD

**Issue by blackdevil72** [EnderMediaDev/The-1.7.10-Pack#856]
Hi,
I'd like to suggest you to add both SecretRoomsMod and MalisisDoors. They are both modpack friebdly.

SecretRoomsMod : Particularly interesting in server environement to hide secrets room, can also be very usefull to add architecture friendly technical access to cables  and machine you want to hide.
link : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1276042-v4-7-1-beta-secretroomsmod-malsis-doors-compat

MalisisDoors : Add many newtype of doors, trapdoors, etc with player detector to auto-open doors. Will add many decoration and architecture posibilities.
link : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076338-malisisdoors-1-7-10-1-9-3-05-08-2015-see-p99-1993

I'd like to say much about these mods but my english is not so good sorry.

**Comment by xJon** [comment]
Currently won't be added.
The SecretRoomsMod isn't really needed when we can just hide doors with Carpenters' Blocks.
Same for MalisisDoors. It might have some new doors but it's not really needed.
Thanks anyway for suggesting :)
