### ISSUE TITLE
Issue with the latest build aka. 0.8.0

### ISSUE THREAD

**Issue by Keltti** [EnderMediaDev/The-1.7.10-Pack#857]
Hi! i have been playing singleplayer in the latest version of The 1.7.10-Pack for Minecraft via Technic Launcher (also latest) for some time now, near 2 IRL days for reference on progress in-game.

Just some hours ago i encountered two things.. when i opened the Tinkers Construct Books and checked the recipes and stuff in them, on some of the entries the whole text is painted black and unreadable. Its like every character is a black pillar kind of thing.

This happened after i noticed that i cant smelt Steel Dust into Steel Ingots but they smelt into Refined Iron Ingots instead, might be a coincidence.

Before that the books worked perfectly for the whole game.

Also some of the items belonging to the Thaumaturge mod look like pink/black checkerboards in NEI gui and dont show their recipes when clicked.

I have a decent PC and ive allocated 3G RAM to the game via the launcher settings so it should not be the cause of this.

Also i read the whole readme on this site before posting and the check list is CHECK! :)

**Comment by xJon** [comment]
Can you please provide some pictures or some additional information?

**Comment by Reprium** [comment]
The refined iron ingots issue is not really an issue, as these ingots are IC2 steel equivalent ingots.

**Comment by xJon** [comment]
Pictures of the books. :)

**Comment by Keltti** [comment]
Allright it seems that the books work perfectly again, might be because i reinstalled the latest version because i was playing the older one for a while now. Of course i made backups of the world and save files before switching to the older one and now loaded the same game again which had the problem for the pictures.

There still persists the recipe problem though, i got some pictures from the GUI and actually i got pictures of all the pages that showed the problem with their icons highlighted for identifying from which mods the items are. (Only the Redstone Board showed its recipe even with the checkerboard avatar bug), Thank you for clearing up the ingot misunderstanding :)

**Comment by xJon** [comment]
The recipe thing isn't a real problem, both ingots work - both mods add the recipe. Due to that sometimes you see this and sometimes you see this, but any type would work.

**Comment by Keltti** [comment]
![2015-08-29_23 16 40](https://cloud.githubusercontent.com/assets/14022597/9564245/1e827ee8-4ea9-11e5-8f46-54863b585b3f.png)
![2015-08-29_23 17 48](https://cloud.githubusercontent.com/assets/14022597/9564248/2412f57c-4ea9-11e5-868a-9e7a70d277e8.png)
![2015-08-29_23 17 53](https://cloud.githubusercontent.com/assets/14022597/9564249/292f3944-4ea9-11e5-9b1b-94264de32eb4.png)
![2015-08-29_23 18 15](https://cloud.githubusercontent.com/assets/14022597/9564250/3266efac-4ea9-11e5-986c-4d92cfc87bc6.png)
![2015-08-29_23 19 41](https://cloud.githubusercontent.com/assets/14022597/9564252/3c385ac0-4ea9-11e5-9259-e12ec5527eaa.png)
![2015-08-29_23 19 44](https://cloud.githubusercontent.com/assets/14022597/9564254/42ac64dc-4ea9-11e5-99e7-616ce0d9632c.png)
![2015-08-29_23 20 05](https://cloud.githubusercontent.com/assets/14022597/9564258/492abe3a-4ea9-11e5-811f-7c2551f30d4a.png)

**Comment by xJon** [comment]
You're using Optifine?

**Comment by Keltti** [comment]
Im 99% sure im not using it, ive been playing the modpack just the way it is released so i havent added anything to it or even modified anything except the controls from in-game menu.

**Comment by xJon** [comment]
The blocks you pointed out of NEI with the missing textures are disabled blocks in mods that don't have any use. It's not a mod-bug or a modpack-bug. :)

**Comment by Keltti** [comment]
Allright! :D that took a lot off my shoulders and pixels, thank you very much and lets try our best to keep it fun ;)

**Comment by xJon** [comment]
:+1:
