### ISSUE TITLE
Cursor hidden

### ISSUE THREAD

**Issue by 108998** [EnderMediaDev/The-1.7.10-Pack#858]
When ever i am in my inventory or an inventory of an item i can not see my cursor. i am wondering what mod does this and if it can be turned off. i am on a mac.

**Comment by xJon** [comment]
Why would any mod want to hide your cursor?
Just try to exit and enter your game, it might be a glitch

**Comment by 108998** [comment]
Ok I will try this, I guess it is not intended, thanks for the hasty response.

From Mitch
