### ISSUE TITLE
Updated to 0.8.0, server shuts down; Can you help diagnose?

### ISSUE THREAD

**Issue by arienf** [EnderMediaDev/The-1.7.10-Pack#859]
Just updated from 0.7.9d, started up, then replaced the default generated world folder and server.properties with the ones I'd used on my server yesterday. 

The server starts up, goes through the various mod activities, but then encounters an error and shuts down right starting with this line (from the console log):

30.08 11:33:35 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625) ~[MinecraftServer.class:?]

Logs:
Server console log: http://paste.ubuntu.com/12231265/
Crash Report: http://paste.ubuntu.com/12231282/

After some search on the web, I'm guessing the world file is corrupted, but I'm very much a newb.  Before I try to fix this, any other thoughts on what I can do to get the server up and running?  If the world is corrupted, what would you suggest?

Thank you!!

**Comment by xJon** [comment]
Can you please provide the **full* fml-server-latest.log?

**Comment by arienf** [comment]
latest.log: http://paste.ubuntu.com/12233055/

full fml-server-latest.log: http://paste.ubuntu.com/12233124/

Thank you!

**Comment by arienf** [comment]
latest.log: http://paste.ubuntu.com/12233055/
full fml-server-latest.log: http://paste.ubuntu.com/12233124/
Thank you!

**Comment by xJon** [comment]
Your fml-server-latest.log doesn't show any crash signs. Try to launch and crash the server again so it'll update. Check that the crash report is also included in it and them post it here :)

**Comment by arienf** [comment]
Restarted, here's what I get:
Console log: http://paste.ubuntu.com/12234807/
FML-latest: http://paste.ubuntu.com/12234845/
Latest: http://paste.ubuntu.com/12234859/
Crash-Report...server.txt: http://paste.ubuntu.com/12234955/
FML-junk early startup: http://paste.ubuntu.com/12234889/

Again, thank you for taking the time to look at these.  If there's a resource available for me to learn how to do this, I'm happy to dive in.

**Comment by xJon** [comment]
Something with the Natura mod is having some problems with NBT tags..
If you want, you can try to delete the Natura mod from the server and restart your world.
It might delete all Natura blocks, but it might make the world launch.
If it will launch you could readdd nature after all of its blocks got reset :)

**Comment by arienf** [comment]
I'll give it a shot!  Thank you!

**Comment by arienf** [comment]
I've remove Natura, then started up the server, letting it generate a new world and server.properties.  That worked fine.
Once I substituted the world I've been using on my server for a few months, the start up hangs at the same place each time I re-start.
Console log: http://paste.ubuntu.com/12238316/
FML Latest: http://paste.ubuntu.com/12238356/

Thoughts as to next steps?  New world?

**Comment by xJon** [comment]
When you try to launch your old world, are you launching it with Natura? Try to launch it without Natura.

**Comment by arienf** [comment]
I've left Natura out  (removed the .jar file from the modpack) on my attempts above.  Is there something additional I should be thinking about beyond removing the .jar?

**Comment by xJon** [comment]
And after you removed the .jar you're still crashing?

**Comment by arienf** [comment]
Yep.
Keep in mind, I'm crashing when I add in my server world that likely uses Natura objects.  For example, I'd set up a Minefactory Reloaded farm that harvests Natura cotton.
I suppose if it's busted, it's busted.  I could revert to 0.7.9d, which is what I've been running on for a while now.
Thank you for looking into this, especially over the weekend!  Hopefully you had a chance to get out doors once or twice!

**Comment by xJon** [comment]
Can you please provide the crash report from when the server crashes __without__ the Natura mod?

**Comment by arienf** [comment]
I tried running the server a couple more times, but no crash-report is generated....it doesn't think it's crashing.  The above logs were generated without the natura jar in the server.

**Comment by xJon** [comment]
So if it doesn't crash what's the problem? It just stops automatically?

**Comment by arienf** [comment]
It goes through the startup process, then stops processing at "[Server] INFO [02:01:52] [Server thread/ERROR] [FML]: Unidentified block: Natura:NetherBerryBush, id 476", autosaving and posting to the YAMPST server perdiodically. 
When I send the command to stop the server it receives the command to stop, and then stops gracefully.

**Comment by xJon** [comment]
Oh, I see. You just need to launch the server and type "/fml confirm" in the console when it stops loading, to delete all the old Natura blocks. This will delete them and keep loading the server. :)

**Comment by xJon** [comment]
Shuts down without a crash log?
I always need the fml-server-latest.log to understand what happens in each launch.
Also try to use the default LauncherServer.bat file, provided with the server files.

**Comment by arienf** [comment]
I'm using a multicraft server from Beastnode.  The multicraft setup they use has a 'jar' folder in which I put the minecraft and forge jars, in addition to the library folder.  I've been successfully running the 1.7.10 Pack with 0.7.9b and d so far.

As above, I started up the server (natura.jar not present on the server), it comes up, processes and then shuts down.  I totally overlooked the crash report file folder previously - it's there, and I've pasted in the results below, in addition to the console log and fml latest.

Console log: http://paste.ubuntu.com/12252975/
crash report: http://paste.ubuntu.com/12253007/
FML latest: http://paste.ubuntu.com/12253018/

**Comment by xJon** [comment]
The only think I can recommend you to do is to manually delete the corrupted chunk.
You got its location in the crash report, line 85.

**Comment by xJon** [comment]
Closed due to inactivity.

**Comment by arienf** [comment]
Thanks Jon...I'll try what you suggest.

I'd gone out of town for the long holiday, apologies!

**Comment by xJon** [comment]
It's alright, enjoy your time :)
