### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by germanstorm** [EnderMediaDev/The-1.7.10-Pack#860]
Hello. Whenever I attempt to load my world, it crashes before the world is fully loaded. I have tried re-installing the pack, using different java versions, and even using older versions of the modpack with no success. Is there anyway to fix this?

**Comment by xJon** [comment]
Can you please provide the crash report?

**Comment by germanstorm** [comment]
How do I do that, it wont allow me to copy it as a link.

**Comment by xJon** [comment]
Read [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/blob/master/README.md).

**Comment by germanstorm** [comment]
How does that paste tool work? I made an account

**Comment by xJon** [comment]
No need to make an accout; you just paste your content and publish it - then send here the link.

**Comment by germanstorm** [comment]
http://paste.ubuntu.com/12235339/

**Comment by xJon** [comment]
https://github.com/EnderMediaDev/The-1.7.10-Pack/issues/834#issuecomment-136066610
:)

**Comment by germanstorm** [comment]
It worked!!! Thank you so much. For my knowledge, do you know why it is that file that causes the game to crash?

**Comment by xJon** [comment]
The update of the mod may have caused it to crash.
