### ISSUE TITLE
GalacticCraft needs updated (to fuel Tier 3 rockets)

### ISSUE THREAD

**Issue by kcoop012576** [EnderMediaDev/The-1.7.10-Pack#862]
Currently the version within the pack is 12.350, which broke the ability to fuel Tier 3 rocket.  This last worked in version 12.345.  A couple weeks ago the author updated to version 12.357 to address the issue: https://github.com/micdoodle8/Galacticraft/issues/1778

Thank you!

**Comment by xJon** [comment]
For now you can cheat youself the fueled version from NEI.
It's a minor bug and we'll update Galacticraft in the next update of the modpack.
Thanks for reporting :)

**Comment by kcoop012576** [comment]
Thanks very much, I was able to grab the updated jar files and put them in the mods folder until the next pack update.

 

– just wanted to be sure you knew in case anyone else was having the same issue. 

 

Thanks for such a great mod pack, and for its continued support!
