### ISSUE TITLE
suggestion - oceancraft

### ISSUE THREAD

**Issue by ziba1** [EnderMediaDev/The-1.7.10-Pack#865]
Just saw this mod spotlight on youtube for oceancraft, mod that adds sealife like sharks, whales, turtles and other various fish into the game. As well as the ability to catch them and build aquariums and other stuff

https://www.youtube.com/watch?v=RKisf_WLDoU

Considering I have an underwater glass base going on (think a bad version of gunga city from the phantom menace haha) , it would be pretty epic to see some sharks swimming past :P

**Comment by xJon** [comment]
The mod doesn't really fit the modpack and won't be added.
Thanks anyway for suggesting :)
