### ISSUE TITLE
Addition of Minetweaker

### ISSUE THREAD

**Issue by ShadowOdysseus** [EnderMediaDev/The-1.7.10-Pack#866]
Minetweaker is used in a lot of packs, and would be fantastic for this pack. You can adjust some of the recipes, and fix a bit of progression. On our server, The Enderverse, we have a few issues with things like Magical Crops being too easy to start. It kind of ruins the economy, and players are complaining about us nerfing it. If you add this, it would be greatly appreciated, as people complain about both sides of the issue.

http://minetweaker3.powerofbytes.com/
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2364943-modtweaker-0-7-x

**Comment by xJon** [comment]
We won't add MineTweaker just to change few recipes. It's really not needed that badly.
For your server though I'd recommend to play a bit with MagicalCrops' configuration file.
You can make the mod 10 times harder if you set it so there won't be any additional seeds dropping, and that's just one option.
Good luck :)
