### ISSUE TITLE
Inquiring about mod conflicts 

### ISSUE THREAD

**Issue by Sayntly** [EnderMediaDev/The-1.7.10-Pack#867]
Was wondering if there will be any mod conflicts if I had
Infernal Mobs 
Levels mod
to the already existing mod list.

Additionally I was wondering if you could tell me, or provide a link with information on what was changed with the recent update. Was considering updating to the new version for our server but wanted more information first. 

thank you

**Comment by xJon** [comment]
I can't tell you exactly if you'd have mod conflicts or not. You'll just have to try and see.
About the second one, as v0.8.0 is set to recommended I'll suggest you to update.
If you want to know v0.8.0's mod-list with versions you can see it [there](http://www.technicpack.net/modpack/the-1710-pack.453902/mods). :)
