### ISSUE TITLE
Modpack won't launch

### ISSUE THREAD

**Issue by Gaston1999** [EnderMediaDev/The-1.7.10-Pack#868]
Hello
I have an issue with the 1.7.10 modpack is that when i press play it prepares the modpack to be launched but then the launcher reappears and nothing happens help me find a solution pls 

Here is the log : 
paste.ubuntu.com/12274476/

ps : i have 4 gb of ram

**Comment by Dommain** [comment]
Please paste the crash log. If there is none, It means it cannot complete some of the updating due to certain IP/ports being blocked.

**Comment by Gaston1999** [comment]
Where do i find the crash log ?

**Comment by xJon** [comment]
Are you using the original Technic Launcher?

**Comment by Gaston1999** [comment]
Of course

**Comment by xJon** [comment]
This is an issue of cracked launchers which are missing required libaries.
If you're using the original one try to reinstall it, but I don't have much else to help you with.
Modpacks with outdated Forge version will work, I suppose, but it's not a problem of The 1.7.10 Pack.

**Comment by Gaston1999** [comment]
Okay . i'll try reinstalling it
