### ISSUE TITLE
Enable/Disable Ender IO Dark Steel Armor enhancements boot other players

### ISSUE THREAD

**Issue by Kohlerslave** [EnderMediaDev/The-1.7.10-Pack#869]
Any time a player enables/disables one of the Dark Steel Armor enhancements, such as speed or step assist, it boots other players.  We've only tested with two of us on, but it is consistent. Which ever player enables or disables the enhancement is fine, and the enhancement either enables or disables.  But the other player gets booted every time with a fatal error.  Here's the section of the log that shows the crash.  There is nothing important before this section.  It's all login info, which all appears normal.

http://pastebin.com/gWCJMqsF

**Comment by xJon** [comment]
Why did you name the error "Mekanism crash"? The dark steel armor is from the EnderIO mod.
Anyway, this should be reported directly to the EnderIO repo. Here's the [link](https://github.com/SleepyTrousers/EnderIO/issues).
Update here with what they say there.

**Comment by Kohlerslave** [comment]
I screwed up when I started this thread.  Had Mekanism on the brain.  I will let you know when I find out more.

**Comment by xJon** [comment]
Closed due to missing information. Will reopen with the required.
