### ISSUE TITLE
SAG Mill numbering bug - affects ME Autocrafting

### ISSUE THREAD

**Issue by rastamanfb** [EnderMediaDev/The-1.7.10-Pack#870]
I have just upgraded to 0.80 from 0.7.9f and I tried to make some glass using an autocrafting recipe in applied energistics.
The system didnt recognise the sand as its showing as Sand 12:32767 rather than Sand 12
This worked as normal in 0.7.9f so something is amiss and is appending the extra numbers even though in NEI it does not show the long version.
I have returned back to 0.7.9F and im unsure if the sag mill is doing this with any other items
If you were not automating crafting it would not be an issues but as the ME system is looking for the exact item numbers that are in NEI even if you recode the patterns it will not accept it due to the appended numbers.

Do you know whats causing this?

**Comment by xJon** [comment]
Can't you just refresh the automatic crafting recipe?

**Comment by rastamanfb** [comment]
no that doesnt work as it consolidates Sand 12:32767 into Sand 12 so Applied energistics cannot understand the output that comes from the Sag.
Basically it the pattern terminal resolves all recipes to the correct item number and not the invalid ones.

on 0.7.9 it sags correctly but in 8.0 something has changed. I have not tried with other ores as i reverted to 0.7.9 to test and make sure i was not imagining things
can you confirm that putting cobblestone in the sagmill 0.80 gives  Sand 12:32767?

**Comment by xJon** [comment]
I can check that, but you basically say that you can't make auto AE2 recipes with Sand "12:32767"?

**Comment by rastamanfb** [comment]
yes, it resolves to 12 and cant reconise that its been been made

**Comment by martinegui** [comment]
I noticed the same problem, I was using this sand ( From cobblestone in teh SAG mill ) to autocraft Qaurtz Seeds but the sand 12:32767 cant be used to craft that in the autocraft or in the woekbench. to fiz this i usually compress to compressed sand and then revert the compress and the sand is the sand 12. But this is a little bit annoying.

**Comment by rastamanfb** [comment]
Yeah which kinda negates away from full automation. I worked very had for this setup.
Are you still using 0.80? Do you get any invalid numbers using the sag mill with other ores? 
I don't really want to go back to 0.80 to find out

**Comment by xJon** [comment]
Guys this is a really minor issue. There are tons of more options, other than the Sag Mill, that can make cobblestone into sand.

**Comment by rastamanfb** [comment]
Its a shame we've just read that response. I've used 1.7.10 on the same world since it first came out. I'm.not that bothered about quests but have invest more than 36hrs on automated craving alone and use the sag mill for multiple recipes due to how it deals with multiplication when pulverising ores. Using another pulveriser or system isn't really an option due to how it all interconnects.
What has changed? Was this mod even updated? Maybe there's a conflict.

**Comment by xJon** [comment]
It's a shame to see people not using the quests :)
The mod updated, and it made this slight problem. Nothing more.
You can report it directly to the mod's repo and see what they say.

**Comment by rastamanfb** [comment]
People don't just use your mod packs for quests. I chose it because of the
mods you use. I can report it to the mods repo but you've haven't given me
info on whether its the mod or a conflict of other mods it's working with
that is causing the invalid numbering.
Previous mekanism issues you detected an issue with mekanism and ae. But in
this case we don't know what it is.
I'll quite happily go to the mods repos but I also thinknit should be
investigated as there could be additional compatibility problems. Not only
that I'm.pretty sure automation is a major part of ae  which you include.
Other people will have this issue and within 24 hrs someone else has
reported this problem suggesting that maybe people are actually bothered
about it

**Comment by rastamanfb** [comment]
https://github.com/SleepyTrousers/EnderIO/issues/2751

**Comment by xJon** [comment]
Obviously *almost* always you should report errors first for the modpack. :)
We'll see what they say on EnderIO's repo and go on from there.

**Comment by rastamanfb** [comment]
as above Jon :)

**Comment by xJon** [comment]
Alright, let's hope they'll fix this soon.
In the next update of the modpack we'll update EnderIO so I'll consider this issue closed.
Thanks anyway for reporting @rastamanfb
