### ISSUE TITLE
Mod Request Tainted Magic

### ISSUE THREAD

**Issue by daforsyth** [EnderMediaDev/The-1.7.10-Pack#871]
Tainted Magic

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2437825-tainted-magic-1-1-5-7-a-thaumcraft-addon

A cool mod that touches the dark side of thaumcraft. Pretty much adds a bunch of end game thaumcraft stuff thats amazing like cool foci with upgrades it adds some lore to the last dimension and has arguably the best wand in between all thaumcraft addons. 

And sorry that I dont know how to add labels... if someone could tell me that would be great >.>

**Comment by xJon** [comment]
Currently won't be added.
The mod doesn't really fit the modpack, which has a lot of Thaumcraft addons already.
Thanks anyway for suggesting.
