### ISSUE TITLE
server skipping ticks after updating to 0.8.0  

### ISSUE THREAD

**Issue by Darkenedmaster** [EnderMediaDev/The-1.7.10-Pack#872]
after i updated my server to the new version (0.8.0) it seems as though its saying its missing versions of mods or something like that. sorry in advance for being an idiot on crash logs and what not relitively new to running a server these are the errors i noticed in the console.

05.09 21:40:38 [Server] Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 16684ms behind, skipping 333 tick(s)
05.09 21:39:58 [Server] Server thread/WARN [FML]: [HelpFixer] Command mk incorrectly overrides compareTo: mekanism.common.CommandMekanism
05.09 21:39:58 [Server] Server thread/WARN [FML]: [HelpFixer] Command chant incorrectly overrides compareTo: com.emoniph.witchery.common.ChantCommand
05.09 21:39:58 [Server] Server thread/WARN [FML]: [HelpFixer] Command waypoint incorrectly overrides compareTo: com.panicnot42.warpbook.commands.CreateWaypointCommand
05.09 21:39:58 [Server] Server thread/WARN [FML]: [HelpFixer] Command waypointdelete incorrectly overrides compareTo: com.panicnot42.warpbook.commands.DeleteWaypointCommand
05.09 21:39:58 [Server] Server thread/WARN [FML]: [HelpFixer] Command maxresearch incorrectly overrides compareTo: thaumic.tinkerer.common.core.commands.MaxResearchCommand
05.09 21:39:58 [Server] Server thread/WARN [FML]: [HelpFixer] Command checkwarp incorrectly overrides compareTo: flaxbeard.thaumicexploration.commands.CommandCheckWarp
05.09 21:39:58 [Server] Server thread/WARN [FML]: [HelpFixer] Command AlterRate incorrectly overrides compareTo: flaxbeard.thaumicexploration.commands.CommandAlterRate
05.09 21:39:58 [Server] Server thread/WARN [FML]: [HelpFixer] Command nick incorrectly overrides compareTo: k4unl.minecraft.colorchat.commands.CommandNick
05.09 21:39:58 [Server] Server thread/WARN [FML]: [HelpFixer] Command iskamiunlocked incorrectly overrides compareTo: thaumic.tinkerer.common.core.commands.KamiUnlockedCommand
05.09 21:38:37 [Server] Server thread/ERROR [CoFHWorld]: Error parsing generation entry: "Zinc" > Please check the parameters. It *may* be a duplicate.
05.09 21:38:37 [Server] Server thread/WARN [CoFHWorld]: Template 'uniform' failed to parse its entry!
05.09 21:38:37 [Server] Server thread/ERROR [CoFHWorld]: Invalid block entry!
05.09 21:36:08 [Server] Server thread/WARN [McMultipart]: Mod McMultipart is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.2.0.345
05.09 21:36:08 [Server] Server thread/WARN [ForgeMultipart]: Mod ForgeMultipart is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.2.0.345
05.09 21:36:08 [Server] Server thread/WARN [ForgeMicroblock]: Mod ForgeMicroblock is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.2.0.345
05.09 21:36:08 [Server] Server thread/WARN [WR-CBE|Logic]: Mod WR-CBE|Logic is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.4.1.9
05.09 21:36:08 [Server] Server thread/WARN [WR-CBE|Addons]: Mod WR-CBE|Addons is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.4.1.9
05.09 21:36:08 [Server] Server thread/WARN [WR-CBE|Core]: Mod WR-CBE|Core is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.4.1.9
05.09 21:36:07 [Server] Server thread/WARN [Translocator]: Mod Translocator is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.1.2.15
05.09 21:36:05 [Server] Server thread/WARN [ProjRed|Exploration]: Mod ProjRed|Exploration is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre8.92
05.09 21:36:05 [Server] Server thread/WARN [ProjRed|Transportation]: Mod ProjRed|Transportation is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre8.92
05.09 21:36:05 [Server] Server thread/WARN [ProjRed|Expansion]: Mod ProjRed|Expansion is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre8.92
05.09 21:36:05 [Server] Server thread/WARN [ProjRed|Illumination]: Mod ProjRed|Illumination is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre8.92
05.09 21:36:04 [Server] Server thread/WARN [ProjRed|Transmission]: Mod ProjRed|Transmission is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre8.92
05.09 21:36:04 [Server] Server thread/WARN [ProjRed|Integration]: Mod ProjRed|Integration is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre8.92
05.09 21:36:04 [Server] Server thread/WARN [ProjRed|Fabrication]: Mod ProjRed|Fabrication is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre8.92
05.09 21:36:04 [Server] Server thread/WARN [ProjRed|Compatibility]: Mod ProjRed|Compatibility is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre8.92
05.09 21:36:04 [Server] Server thread/WARN [ProjRed|Core]: Mod ProjRed|Core is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 4.7.0pre8.92
05.09 21:36:04 [Server] Server thread/WARN [PneumaticCraft]: Mod PneumaticCraft is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.11.1-121
05.09 21:36:02 [Server] Server thread/WARN [numina]: Mod numina is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 0.4.0.7-QMX
05.09 21:36:02 [Server] Server thread/WARN [recipemod]: Mod recipemod is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 0.2
05.09 21:36:02 [Server] Server thread/WARN [neiintegration]: Mod neiintegration is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.0.12
05.09 21:36:01 [Server] Server thread/WARN [powersuits]: Mod powersuits is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 0.11.0.7-QMX
05.09 21:36:01 [Server] Server thread/WARN [MagicBees]: Mod MagicBees is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.7.10-2.3.3
05.09 21:35:59 [Server] Server thread/WARN [HardcoreEnderExpansion]: Mod HardcoreEnderExpansion is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.8.3
05.09 21:35:58 [Server] Server thread/WARN [ForbiddenMagic]: Mod ForbiddenMagic is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.7.10-0.57
05.09 21:35:57 [Server] Server thread/WARN [ExtraUtilities]: Mod ExtraUtilities is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.2.10
05.09 21:35:57 [Server] Server thread/WARN [EnderStorage]: Mod EnderStorage is missing the required element 'version' and a version.properties file could not be found. Falling back to metadata version 1.4.7.36
05.09 21:35:56 [Server] Server thread/WARN [debug]: Mod debug is missing the required element 'version' and no fallback can be found. Substituting '1.0'.

thanks for any help in advance

**Comment by xJon** [comment]
It's missing nothing. Simply updated mods, no problemo.
Don't worry!
