### ISSUE TITLE
[Windows 10] I upgraded my OS and now it seems no one can connect to my server.

### ISSUE THREAD

**Issue by Grandox** [EnderMediaDev/The-1.7.10-Pack#873]
Hi there. I have been running a 1.7.10 modpack Technic server for sometime time now on my Windows 8.1 machine. I have since then upgraded to Windows 10 which seems to be causing connection issues. I have restarted both my machine multiple times and the server as well. I have double-checked my IP and the port-forwarding I had set up. Everything looks to be in order. 

The only thing I can give you to work with is that everyone seems to be getting the same ominous message: Timed Out.

Any help is much appreciated!

**Comment by xJon** [comment]
It has nothing related to Windows 10. I'm running Windows 10.
Just be check that the server you are playing on isn't overloaded, because that what makes this problem most of the time.
