### ISSUE TITLE
Server won't start

### ISSUE THREAD

**Issue by TheSphix** [EnderMediaDev/The-1.7.10-Pack#875]
Hello then i start te server it just sendt the stop comand strigth a head.. Help plz
![image](https://cloud.githubusercontent.com/assets/14168550/9722659/50583c64-55b1-11e5-9a8b-aa380ab625f9.png)

**Comment by xJon** [comment]
![image](https://cloud.githubusercontent.com/assets/8945347/9726490/0ac4adc2-55fc-11e5-810b-bfd23b0158db.png)

**Comment by TheSphix** [comment]
Oh stuipid me xD
