### ISSUE TITLE
Not Opening - Need Help!

### ISSUE THREAD

**Issue by Xjela** [EnderMediaDev/The-1.7.10-Pack#876]
http://paste.ubuntu.com/12407169/
Please help!

**Comment by Xjela** [comment]
I deleted things named "logisticpipes", somehow it was working at the beginning but it crashed again!

**Comment by xJon** [comment]
When did this issue start to happen?

**Comment by Xjela** [comment]
I tried to play this modpack about 7 months ago but it didn't worked at that time too. In other words I didn't even able to play it.

**Comment by xJon** [comment]
Did you try to completely reinstall it?

**Comment by Xjela** [comment]
Yeah I re-downloaded it.

**Comment by xJon** [comment]
Try to completely delete the modpack's folder, in .technic/modpacks/the-1710-pack, and then download it again.

**Comment by Xjela** [comment]
It didn't work. :(

**Comment by xJon** [comment]
Still same crash when you try to launch the modpack?
What about other modpacks using latest versions of EnderIO, like [this one](http://www.technicpack.net/modpack/enderx-core-zero.685135)?

**Comment by Xjela** [comment]
Yeah its the same crash and I downloaded Core Zero Mod and I got this crash error: http://paste.ubuntu.com/12430000/ . I didnt understand what causes for error, I can play Blightfall but I can't play those 2 modpacks. Hope we can fix it.

**Comment by xJon** [comment]
It's a problem with your language settings.
> On the launcher go to Options tab
On the Additional Java Parameters box paste in this: -Duser.language=en -Duser.country=US
Have fun!

**Comment by Xjela** [comment]
It worked, thank you!

**Comment by xJon** [comment]
:)
