### ISSUE TITLE
suggestion:more dungeons(ruins mod)

### ISSUE THREAD

**Issue by petruciorex** [EnderMediaDev/The-1.7.10-Pack#877]
this modpack is perfect,but need some more dungeons like the ruins mod what is pretty cool!

i realy love this modpack <3 s2

**Comment by xJon** [comment]
The Ruins mod was in the modpack until not too long ago. Removed due to many reasons, it has some issues. Thanks anyway for suggesting!

**Comment by TheLegend714** [comment]
I added the ruins mod can you infer what was causing problems?

**Comment by xJon** [comment]
Some structures were problematic with them having OP loot and builds, it doesn't really fit the modpack.
