### ISSUE TITLE
Gendustry lag

### ISSUE THREAD

**Issue by imsupermario** [EnderMediaDev/The-1.7.10-Pack#879]
I am getting this message on my server console
"
15.09 17:15:17 [Server] Server thread/WARN [IC2.EnergyNet]: EnergyNet.removeTileEntity: net.bdew.gendustry.machines.apiary.TileApiary@635beed4 (net.bdew.gendustry.machines.apiary.TileApiary@635beed4) doesn't match the registered te net.bdew.gendustry.machines.apiary.TileApiary@436ea33d, skipping
15.09 17:11:13 [Server] Server thread/WARN [IC2.EnergyNet]: EnergyNet.addTileEntity: net.bdew.gendustry.machines.apiary.TileApiary@635beed4 (net.bdew.gendustry.machines.apiary.TileApiary@635beed4) is still conflicting with net.bdew.gendustry.machines.apiary.TileApiary@436ea33d using the same position (overlapping), aborting "

server has been very laggy recently , there is no crash but it used up all CPU usage and causing connection time out.

please can you tell me what is the problem? and how can i fix this

fml server latest
part1
http://paste.ubuntu.com/12423851/
part2
http://paste.ubuntu.com/12423874/
part3
http://paste.ubuntu.com/12423888/
part4
http://paste.ubuntu.com/12423963/
part5
http://paste.ubuntu.com/12424023/
part6
http://paste.ubuntu.com/12424185/

**Comment by xJon** [comment]
This error doesn't suppose to make lag, and as I see from your log the server is not overloaded. If you have a low frame rate, it might be your client and not the server.

**Comment by imsupermario** [comment]
here is a paste after server boot

"Server thread/WARN Can't keep up! Did the system time change, or is the server overloaded? Running 506293ms behind, skipping 10125 tick(s)"

http://paste.ubuntu.com/12425118/

**Comment by imsupermario** [comment]
problem fixed, it is caused by pneumatic craft charging station
pneumatic craft recent version is full of bugs
https://github.com/MineMaarten/PneumaticCraft/issues?utf8=%E2%9C%93&q=lag

By the way, a side note, EnderIO redstone conduit is (signal) not updating in this current version.

**Comment by xJon** [comment]
Alright. Hopefully when we'll update the modpack these minor issues will be fixed.
