### ISSUE TITLE
Apiarist Chest doesnt open.

### ISSUE THREAD

**Issue by Avarones** [EnderMediaDev/The-1.7.10-Pack#882]
Hello.

Earlier I set to my apiarist chest to be private (single player, I dont know why I did that lol). Now I started to play again and it doesnt open, I am receiving the following message: 

Avarones is the owner of this machine and has locked access.

What can I do to solve it? I cant destroy it, even in creative mode =/

**Comment by xJon** [comment]
Hm. You're talking about the chest from Forestry?
You can try to go to there to ask help: https://github.com/ForestryMC/ForestryMC/issues
As for the bug itself, the pack will update soon and there were updates to the Forestry mod. Let's hope they fixed it. If not, they'll fix it after you'll report it.

**Comment by Avarones** [comment]
Hey! Thanks for replying, I will post there, if there is no solution yet, they can launch one in the next update.

**Comment by xJon** [comment]
I saw you got help there! :)
