### ISSUE TITLE
Can't load world 

### ISSUE THREAD

**Issue by biodante** [EnderMediaDev/The-1.7.10-Pack#883]
Hello I'm using window 8 and I've been play just fine but today I could not load my world it just says loading after I click my world the exits to launcher please help

**Comment by biodante** [comment]
I also looked further back into other people problem I found one that had the same as me but what worked for hmm didn't work for me which was delete the logistics folders of his would

**Comment by Bropecee** [comment]
it happens to me too  :(

**Comment by biodante** [comment]
Hey try this go to app data and go into 1.7.10 mod pack there is a folder called back ups after you in go through the all the extension till you get a folder with you world name on it open the zip save it to a folder on your desk top go back to mod pack and go to saves and your world copy them to another folder on desktop (just in case) then put the back up files in and replace all the files it worked for me

**Comment by xJon** [comment]
Please read [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/blob/master/README.md) so you could provide the required information.

**Comment by xJon** [comment]
Closed due to missing information. Will reopen with the required.
