### ISSUE TITLE
Inverted Powered light from EnderIO not working

### ISSUE THREAD

**Issue by broyles** [EnderMediaDev/The-1.7.10-Pack#888]
when i am placing inverted power lights to enderio conduits they are not powering up, they are receiving the power just not lighting up. I have to place other blocks around them to get them to work.

**Comment by xJon** [comment]
This is a **very minor** issue.
It doesn't need other blocks next to it, but just block updates.
You can put a block next to it and then break it and it'd still work.
If you want you can report it at EnderIO's repo, but that's not a modpack issue :)
