### ISSUE TITLE
Block ID issue with EnderIO after Updating to 0.8.1? 

### ISSUE THREAD

**Issue by kingstinger1** [EnderMediaDev/The-1.7.10-Pack#889]
It really sucks being new at this but im slowly figuring things out. I updated to 0.8.1 and when I loaded the server for the first time after I did FML confirm the server crashes Below is the crash report. Please help.. Thanks.
This is not on our dedicated server, just on my PC as a test  run as I have never updated a the server to a new version before.. So at least our live dedicated server is still currently running.

Not sure how to resolve the current issue.

**EDITED: Please use a paste-tool: http://pastebin.com/0J69mjWx**

**Comment by xJon** [comment]
That's an issue from EnderIO. Maybe in the update some blocks got bugged.
Try go to [there](https://github.com/SleepyTrousers/EnderIO/issues) and ask for help, and then comment here to say what you found.

**Comment by xJon** [comment]
They said it's probably world corruption, unfortunately. You can try to maybe remove a single chunk and see if it works or not.

**Comment by kingstinger1** [comment]
Yeah that's what I figured. I tried to post issue on the link you gave me but wouldn't post for some reason. 
Anyways just yesterday I took a new back up of the world and tried again and it was successful. Thanks for your help dude.. And great pack by the way. Players on my server love it.

**Comment by xJon** [comment]
:)
