### ISSUE TITLE
Unknown crash

### ISSUE THREAD

**Issue by Neology2k** [EnderMediaDev/The-1.7.10-Pack#890]
Hello, So updated to 0.8.1 on my server this morning, all seemed great, but then whilst I was out, I had about a million messages saying my server kept crashing (it reboots itself) every time someone joined it.

turned out to be a chunk issue, 
>[Server thread/ERROR]: Chunk file at 163,79 is in the wrong location; relocating. (Expected 163, 79, got 164, 80)

Reverted map back to a backup, played as normal for a while, then "Server Closed".

Got the logs, here's the fml-server log.
http://paste.ubuntu.com/12634810/

and here's the crash-report

http://paste.ubuntu.com/12634817/

My players are going to be annoyed at the 24 hour rollback, but they were warned we always play the "latest" branch.

**Comment by xJon** [comment]
One of your world files got corrupted, may be due to the update.
Why do the backups don't work though?

**Comment by Neology2k** [comment]
see it's already gone to a backup once... will try again.

**Comment by Neology2k** [comment]
alright, reverted to backup, worked fine for a few mins, then same crashes again..

**Comment by xJon** [comment]
Same chunk location in the crash report? Or maybe it's a player doing it?

**Comment by Neology2k** [comment]
I was only one on. Told the others to keep off a few mins.... To be fair Originally I deleted my player dat, went over to the same location and was fine for about 1 minute.. then got hit by the crash.. so reverted 30 mins before and was fine in that location for a good few minutes before the crash... 

Logs coming shortly..

**Comment by xJon** [comment]
If you want, you can just try to delete the corrupted chunk and that's it. Again - locations are in the crash reports.

**Comment by Neology2k** [comment]
quick update, formatted that hard drive, and re-installing modpack, then will copy world across. The annoying part is the world is 5.27 GB

**Comment by xJon** [comment]
Yes, this line. If you want to go the really easy way you can delete the *whole* region file (6,4).
If not, lookup tutorials how to delete only the specific chunk out of this region.

**Comment by Neology2k** [comment]
Lastest error:
http://paste.ubuntu.com/12637674/

Nothing referencing chunks or region (except the spawn location).

**Comment by Neology2k** [comment]
chunk deleted, same errors.

**Comment by xJon** [comment]
I see. It's indeed not chunk related.

**Comment by Neology2k** [comment]
you want access to the server to mess around, let me know.

**Comment by xJon** [comment]
Unfortunately that's a world corruption.
If you have backups, try to test and see what happens before the world corrupts.

**Comment by xJon** [comment]
Closed due to inactivity.
