### ISSUE TITLE
#bug

### ISSUE THREAD

**Issue by Twingrey** [EnderMediaDev/The-1.7.10-Pack#891]
Remember me, a guy who found silver dupe bug? Found another one, this time with diamonds. Since last time dupe bug was classified (who knows who saw it before you removed details), I'm not posting details here, only through secure channels.
Upd: How do you even post something privately here? Can't send private messages, technic platform doesn't have messaging system either, only on forums.

**Comment by xJon** [comment]
You can private message me even when I'm offline in [Discord](https://discord.gg/0XRCFkHskZH0DA3Q), or in the [Minecraft Forums](http://www.minecraftforum.net/members/Jon).

**Comment by Twingrey** [comment]
Sent a message on minecraft forums, check your mailbox there.

**Comment by xJon** [comment]
This bug already got reported.
We think we'll just [code]xreliquary_alkahest_tome = false[/code] it for now.

**Comment by xJon** [comment]
Also, as always, thanks for reporting.

**Comment by xJon** [comment]
Unfortunately, due to an issue with the mod, the item can't be disabled.
