### ISSUE TITLE
0.8.1 server crash

### ISSUE THREAD

**Issue by alemaz84** [EnderMediaDev/The-1.7.10-Pack#895]
Hi, sorry for my english.
I have a problem with 0.8.0, the server run, when i try to connect minecraft crash and return to the launcher.
I try to install the new version but i have a problem.
I download the 0.8.1 server version and i start launchserver.bat.
In the txt file there is a crash report.
Any suggestion? tnx
[Uploading crash report.

txt…]()

**Comment by xJon** [comment]
There's no crash report....

**Comment by xJon** [comment]
Closed due to missing information.
