### ISSUE TITLE
Disconnected when you type in chat.

### ISSUE THREAD

**Issue by Wmul** [EnderMediaDev/The-1.7.10-Pack#896]
Hello there,

I am running the pack on my server, and I have to say.. Im loving it :-)
But I found out 1 problem, if I dont use /say infront of my message, i get disconnected.
Could you pleas tell me if there is a way to remove that, so you can type in chat without typing "/say" infront of everything you want to say?? 

Wmul

**Comment by xJon** [comment]
It's a conflict between KCauldron and the ColorChat mod. Decide who you keep.
