### ISSUE TITLE
Mod suggestion: Malisis doors

### ISSUE THREAD

**Issue by trapbuilder2** [EnderMediaDev/The-1.7.10-Pack#897]
I suggest the malisis doors mod, as it really fits in with the mod. It will also help on servers with the ability to lock doors with a passcode. I added it to the modpack on my PC, but then it does not work on servers, as the doors disappear. It would be cool to use it on multiplayer as well.

**Comment by xJon** [comment]
People suggested this mod a lot already.
It doesn't really fit the pack, and it's not needed.
There are a lot of ways to lock doors even with our current setup.
Thanks anyway for suggesting :)
