### ISSUE TITLE
Mod Suggestion: DrZhark's Mo' Creatures

### ISSUE THREAD

**Issue by Ukelelechris** [EnderMediaDev/The-1.7.10-Pack#898]
I feel like this mod really does add a ton of variety to minecraft, and I'd love to see it in this modpack. Not only the animals, but the increased number of pets and mounts. I'm really not sure if it would be difficult to implement or not, but I'd thought I'd suggest it anyways.

**Comment by xJon** [comment]
Mo' Creatures doesn't let any public modpack permissions to use the mod.
