### ISSUE TITLE
Archimede's Ships

### ISSUE THREAD

**Issue by Ethnw2** [EnderMediaDev/The-1.7.10-Pack#899]
Hey, just a short little request to add Archimedes ship to the game. It would make the "Adventures of Columbus" quest line a whole lot more fitting and there's just a lot you can do with them, though I'm unsure if they still cause server issues.

**Comment by Ethnw2** [comment]
The mod forum is http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289952-archimedes-ships-v1-7-banking-ships

**Comment by xJon** [comment]
People suggested this mod already many times.
It's not that stable and the ships are glitchy with many mod's items.
Currently won't be added.
Thanks anyway for suggesting.

**Comment by Ethnw2** [comment]
Yeah, I knew it was possible that was still an issue.
