### ISSUE TITLE
latest ender IO seems to have issues with visuals

### ISSUE THREAD

**Issue by rastamanfb** [EnderMediaDev/The-1.7.10-Pack#900]
This has been reported to enderIO but i only found out because the bug was making it very difficult as i use Item conduits for automation.
https://github.com/SleepyTrousers/EnderIO/issues/2812

please see an example on my attached images.
There doesn't seem to be a direct acknowledgement of the issue from their dev team
http://i.imgur.com/9FrmIWA.jpg
http://i.imgur.com/trLkikf.png

**Comment by xJon** [comment]
Unfortunately there's nothing I can do. This is a mod-bug and should be reported directly to the mod authors.

**Comment by rastamanfb** [comment]
It has. Its more to make you aware.
Is there a reason you use the beta compiles over the release versions?

**Comment by xJon** [comment]
The latest release version of EnderIO don't have support for latest versions of other mods.

**Comment by rastamanfb** [comment]
Thanks the the reply
Hopefully this will get resolved. They have had reports of this since 415
