### ISSUE TITLE
Another cool mod- Extra TiC

### ISSUE THREAD

**Issue by Masterindisguise** [EnderMediaDev/The-1.7.10-Pack#902]
A cool mod that I think should be looked into is Extra Tic. It basically allows for you to make Tinker's Construct tools out of materials from other mods, like Pink Slime ( Really good for bows) from MFR and Thaumium ingots ( Like paper, but stronger) from Thaumcraft.

**Comment by xJon** [comment]
Currently the mod won't be added.
It doesn't really fit the modpack.
Thanks anyway for suggesting!
