### ISSUE TITLE
morph mod not allowing me to aqquire new morphs on server

### ISSUE THREAD

**Issue by djandy** [EnderMediaDev/The-1.7.10-Pack#903]
finally got my server up but morph isnt working i can kill anything and it never gives me it as a morph is this intentional or is it a bug of some sorts or something i havent done in setting up my server?

**Comment by djandy** [comment]
update to that all the mods seem to be there but i cant place or use any thing out of any mod

**Comment by xJon** [comment]
There's no such bug. Maybe you installed the server wrong. Try to reinstall it.

**Comment by djandy** [comment]
yeh i started my server via minecraft server after starting it with forge works loverloy im just crap at this

**Comment by xJon** [comment]
:+1:
