### ISSUE TITLE
Server doesn't start

### ISSUE THREAD

**Issue by NeutronS21** [EnderMediaDev/The-1.7.10-Pack#904]
Hi, my server doesn't start:
![image](https://cloud.githubusercontent.com/assets/6967153/10394881/41616c92-6e9a-11e5-9c21-fa8a5ffeb656.png)

**Comment by xJon** [comment]
Can you provide the latest-server-fml.log file? Please use a paste-tool.

**Comment by NeutronS21** [comment]
Oh yea, srry:
http://mc.cyberlegion.eu/fml-server-latest.log
I used my server cuz this log is too heavy 4 pastebin or others paste-tool

**Comment by xJon** [comment]
I see some errors from Flan's Mod but nothing that stops the server. Is this the full log? The server didn't crash.

**Comment by xJon** [comment]
Closed due to inactivity.
