### ISSUE TITLE
Version 0.8.1 not updating.

### ISSUE THREAD

**Issue by natebreh** [EnderMediaDev/The-1.7.10-Pack#905]
Hello,

I am trying to update the 1.7.10 pack to 0.8.1 and it comes up with the following error - Error unzipping a file for the following pack: The 1.7.10 Pack

Attempting to extract file the-1710-pack-0.8.1.zip, but it did not exist.

Please consult the modpack author.

Thanks in advance.

**Comment by rastamanfb** [comment]
This this might be an issue with Technic as I cannot view the page and when i try to play (mine was already updated) im getting the following error
![image](https://cloud.githubusercontent.com/assets/12107215/10404331/d1ca65ca-6ec9-11e5-922c-74dfdab16b01.png)

**Comment by SunshineHunter** [comment]
This will be resolved as soon as Jon is awake or back, it's 1 am for him already so I guess he's sleeping.

**Comment by Boehrsi** [comment]
Got the same error as rastamanfb. It's quite strange because all other mod packs are there, only this pack is gone. Either it is a Technic error or the pack is removed at least currently from the launcher / page for what ever reason.

**Comment by xJon** [comment]
Solder was silly, had wrong modpack version at recommended and a wrong mod version picked.
Everything should work now for clean installs.
Sorry.
