### ISSUE TITLE
Lost My World

### ISSUE THREAD

**Issue by ChiknNRiceGaming** [EnderMediaDev/The-1.7.10-Pack#907]
Ok, so when I tried to play the modpack, the game put up an error. So, I delted the modpack and reinstalled it. The good news is that the pack is working again, but the bad news is I lost my world. I know the modpack has Aroma1997, so is there any way to get my world back?

**Comment by xJon** [comment]
How did you delete the modpack? The backups are located in the modpack folder.

**Comment by ChiknNRiceGaming** [comment]
I delted by pushing the delete button on the technic launcher

**Comment by xJon** [comment]
That might deleted the whole modpack folder, with the saves. Sorry!
