### ISSUE TITLE
ProjectRed Transportation Bug

### ISSUE THREAD

**Issue by Gharth** [EnderMediaDev/The-1.7.10-Pack#908]
I think I found a bug with the upgraders. I cant crafte them (the xl and rx stuf plus the Null Logic Upgrade Chip's), ther is no recipe for them noer can I use the Router Utiity tool to get even in the update menu. I dont know if it is inactive for some reason, but it would be nice, if you would let me know what is the deal with it.

-lg. Gharth

**Comment by xJon** [comment]
What version of the modpack are you playing in?

**Comment by Gharth** [comment]
Well in the 0.8.1.

and i think its cool that you react so farst, realy cool to se that the dev of the modpack is so active :3

**Comment by xJon** [comment]
I can confirm this but I don't think it's an issue. Pretty sure ProjectRed changed few stuff.
The best thing would be you hop on and ask them yourself though, [there](https://github.com/MrTJP/ProjectRed/issues).
Closing this for now!
