### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by Ukelelechris** [EnderMediaDev/The-1.7.10-Pack#909]
This morning my server started crashing on startup. 

This is the crash report
http://paste.ubuntu.com/12757555/

Hope you can help me :(

**Comment by xJon** [comment]
Your questing data is invalid. You can reset in inside of your world save :)

**Comment by Ukelelechris** [comment]
Hey jon, I know this is closed, but I dont know where to ask and I was wondering how I would go about doing this. I tried messing with the hardcorequesting folder inside the world folder but it didnt work...

**Comment by xJon** [comment]
Did you try to reset it?

**Comment by Ukelelechris** [comment]
yeah, I tried deleting the folder, replacing the folder with a fresh one, and just deleting the files contents. gave me the same error every time

**Comment by xJon** [comment]
How do you start the server? Do you double click the "LaunchServer.bat" file?

**Comment by Ukelelechris** [comment]
Yep.

**Comment by Ukelelechris** [comment]
By the way, thanks for continuing to help me :)

**Comment by xJon** [comment]
It makes no sense that your server is crashing with clean installs. Are you sure you did everything right? eula.txt is set to true?

**Comment by Ukelelechris** [comment]
Yeah, Im absolutely sure except for the HardcoreQuesting thing. When I get home I'll try doing what i did again, and check the crash report to see if it matches. Already done, but no harm in making sure

**Comment by Ukelelechris** [comment]
Sorry I forgot to reply. anyways, feel free to close this. I got the same error, and I think I just want to give up and start over I suppose
