### ISSUE TITLE
Get Kicked Once Users Talk

### ISSUE THREAD

**Issue by Junius1001** [EnderMediaDev/The-1.7.10-Pack#910]
Every time a user talks, they get kicked. 

Since I host a 1.7.10 pack server, I wanted to get bukkit installed aswell. In order to get bukkit to also cooperate, I was told I had to download cauldron to enable bukkit plugins, however, there's a twist. When I do download the zip file for cauldron, and follow the directions, the zipped file itself causes a problem that kicks people from the server when they attempt to talk. Here's the website I got the file from: https://nitrous-networks.com/support/article/93/how-to-install-plugins-on-ftb-infinity-and-direwolf. One of the staff from the website told me that cauldron might not have an update for Forge v157, the version this pack runs on. 

What should I do?

**Comment by xJon** [comment]
First you indeed need KCauldron that fits the Forge version, but your problem comes from the ColorChat mod. Remove it as it doesn't work with Cauldron.
