### ISSUE TITLE
Crash on crafting Mekanism's Induction Port

### ISSUE THREAD

**Issue by Annih7** [EnderMediaDev/The-1.7.10-Pack#911]
I've tried crafting Mekanism's induction port in bot Project Red's project table, and in MineFactory Reloaded's liquicrafter.

When using the Project Table, the server crashed, and couldn't start until backups were written over the region. When using the liquicrafter, the client crashed, and after restarting, attempting to use the liquicrafter would cause further client crashes.

I don't believe i was able to place the full recipe with either attempt; the cause may be placing one of the two components (induction casing & elite control circuit) in the crafting grid.

I've worked around the problem by generating the item, which worked fine.

The server crash logs appear to have been deleted overnight, but the error occured when ticking the project bench, as I recall. I ran the world in single player, which also crashed, so i do have some logs to post from that.

Client log (project bench): http://pastebin.ubuntu.com/12766847/
A different message: http://pastebin.ubuntu.com/12766934/
crash w/ liquicrafter: http://pastebin.ubuntu.com/12766960/

**Comment by xJon** [comment]
I can confirm the issue.
Anyway it's a mod-bug, this should be reported directly to [ProjectRed](https://github.com/MrTJP/ProjectRed/issues) or [MinefactoryReloaded](https://github.com/skyboy/MineFactoryReloaded/issues).

**Comment by Annih7** [comment]
I tried it in a fresh world on a vanilla table, and that crashed; on heading to mekanism's page to post, I found this: https://github.com/aidancbrady/Mekanism/issues/2938
Seems this is a mekanism thing. A shame their development is stalled.

**Comment by Nillecram** [comment]
Yep same here but from : https://github.com/aidancbrady/Mekanism/issues/2938

aidancbrady commented 9 days ago
Fixed in dev.
aidancbrady closed this 9 days ago

Hope the 1.7.10 team will update the mudpack soon.
Thank you for you hard work.
