### ISSUE TITLE
Crash Report (hoping it can help make the pack more stable)

### ISSUE THREAD

**Issue by ShikuTeshi** [EnderMediaDev/The-1.7.10-Pack#914]
Crash Report: http://pastebin.com/kWhmPAcm
This is a reoccurring crash that happens a couple times a day.
From what I was told, my friends were fighting Twilight bosses when the crash happened. This has happened at least 8 times today.

What have I done to the mod-pack?
I've added "Superheroes Unlimited" into the pack. I don't believe it is the issue because the server has had the same crash a couple of times before adding the mod.

**Comment by xJon** [comment]
It doesn't relate to *modpack* stability but to *mods* stability.
As hard as I'd want to make everything work perfectly - I can't, tons of people built this modpack together :)
Anyway, I'd suggest you go to [there](https://github.com/Thaumic-Tinkerer/ThaumicTinkerer/issues/639) to get help, some other people got the same crash.

**Comment by xJon** [comment]
Closed due to inactivity.
