### ISSUE TITLE
Massive Lags which are making the gameplay unplayable.

### ISSUE THREAD

**Issue by Addolin** [EnderMediaDev/The-1.7.10-Pack#915]
**Hello there.**

I recently downloaded the 1.7.10 Pack, because I saw it on YouTube and thought, that it would be such a great pack. But it came different, it's impossible to play it, because I get constantly massive lags in different worlds. I tried to re-install the pack, re-install java, remove/add some mods and, and, and. Nothing worked, the lags are still here. It's also not about my graphics settings/card, because I tested to play the pack also in the worst settings and the lags were still there. I made for you a video (https://youtu.be/LUcPh4w6D8U), where you can better see, what I mean. Probably you'll know the issue? I just really want to play the pack, it would be extremely sad, when I could not get rid of the lags, because it's a great pack! I also tried to install OptiFine, but it didn't helped. I need really help and I really have  no idea, why this is happening. I tried also to give Minecraft only 4GB of RAM, but I got still the same lags like with 8GB of RAM. I don't made a video about that again, because the lags were the same like in the first video, so I only made a screenshot, that shows, that I have 0 FPS. (http://i.imgur.com/yke624A.png)

*Basic System Informations: Windows 8.1 Pro
Processor: AMD Phenom(tm) II X6 1100T Processor @ 3.30 GHz 
RAM: 16GB (15,1GB usable - 8GB given to Minecraft)
Type of system: 64-bit
Graphics Card: NVIDIA GTX 980 Ti (6GB)
fml-client-latest.log (I was a few minutes in the world) File: http://paste.ubuntu.com/12824018/*

**Thanks in advance!**

**Comment by xJon** [comment]
- Try to give Minecraft just 4GB of RAM
- Please provide the fml-client-latest.log file, using a [paste-tool](http://paste.ubuntu.com/).

**Comment by Addolin** [comment]
**Hello xJon.**

*I have updated the ticket with the needed informations and I posted them also in this comment.*

I tried to give Minecraft only 4GB of RAM, but I got still the same lags like with 8GB of RAM. I don't made a video about that again, because the lags were the same like in the first video, so I only made a screenshot, that shows, that I have 0 FPS. (http://i.imgur.com/yke624A.png)

Here's the provided fml-client-latest.log file. I was just a few minutes in the world, because the massive lags. (http://paste.ubuntu.com/12824018/)

**Comment by xJon** [comment]
Can't find any special error on your log.
Can you please check in your task manager what's your CPU usage when you run the game and experience 0 fps?

**Comment by Addolin** [comment]
I've made a short picture (http://i.imgur.com/36eRPfl.png) for you, that is showing the CPU utilization when I'm running or not running the 1.7.10 Pack. The windows are in German, so you may translate some words using [Google Translator](https://translate.google.com/#de/en). I've just translated the most needed words in my opinion. The screenshots of the windows were made in 1 minute intervals, so the CPU utilization and RAM utilization may be higher each screenshot.

**Comment by xJon** [comment]
Your RAM is fine, same for CPU usage, and you said that your GPU is NVIDIA GTX 980 Ti.
Sure that the 0fps issue isn't just with some silly-first-world-creation or something?
I have a PC with lower specs than you and after I first create my world I can stabilize between 100-200fps.

**Comment by Addolin** [comment]
I can surely say that this is legit, you saw it in the video. It's everytime like in the video, doesn't matter whether I go in an old world or whether I create a new one. Honestly I never saw something more strange like that in the TechnicPack and I got absolutely no clue how to fix it. I tried also to wait over 10 minutes after the world loading, but it doesn't helped.

**Comment by xJon** [comment]
Did you try to play in servers and see how your client performs there?

**Comment by Addolin** [comment]
I've tried to log in on some servers, that you've listed above. The same lags started after a few seconds like in a normal singleplayer world, unfortunately. Maybe a single Mod is buggy? But I'm asking myself why there are no other complaints like this on GitHub.

**Comment by xJon** [comment]
What version of the modpack are you playing in?

**Comment by Addolin** [comment]
I'm playing on the Modpack version 0.8.1.

**Comment by Addolin** [comment]
Should I try to change the version?

**Comment by SunshineHunter** [comment]
Hello/Hallo! :) Jon called me here, try this:
1. Try other packs like Tekkit Legends Same issue. Do you experience problems in other games too? 
2. How new is your system? Did you upgrade to Win8.1? Reinstall your graphic driver cards. Run the GPU stresstest "FutMark" for 1 hour and mention oddities (FPS drop, stutter, crashes, temperature increase)

Short: My guess is that your GPU drivers are acting up, since CPU and Java seems to be fine

**Comment by Addolin** [comment]
**Hello SunshineHunter!**

- I've tried SkyFactory 2, Tekkit Legends, Blightfall and Refuge and some other packs and I do not experienced this issue. This issue is also not avialable in other games than Minecraft.

- The Graphics Card is pretty new. Maybe a code/script in the modpack is incompatible with it? I'm absolutely not a pro at this, but maybe you know more detail. I have Windows 8.1 by the way, so it's the newest version.

*I'll update this comment soon, after I've re-installed my GPU drivers and after I've runned the FutMark test.*

**Comment by xJon** [comment]
@Addolin You're the only one experiencing the problem. Thousands of players play the modpack everyday.
I'd suggest you to try playing with [this](www.technicpack.net/modpack/enderx-core-zero.685135) modpack that has a lot of The 1.7.10 Pack's mods, and post here the results.

**Comment by Addolin** [comment]
@xJon Thanks for suggesting me this modpack, there were no lags of this kind like I showed in the video, but unfortunately it doesn't fit my originally wishes. The world generation was also terrible, to be honest. Some chunks were not loaded and some blocks were just invisible for some reason. The quest book was also buggy. I'd really wish to play the original 1.7.10 Pack. Let's give it one more try, maybe it'll work, when not, then bad luck.

**Comment by xJon** [comment]
I just wanted to check if it lagged too like The 1.7.10 Pack.
Anyway that's very weird.
Try to go to .technic/modpacks and completely delete "the-1710-pack" folder. The install it again.

**Comment by Addolin** [comment]
I've done this over 5 times I guess. I even tried to re-install the whole launcher, but - you may know the answer - it didn't helped. :P

**Comment by xJon** [comment]
Unfortunately I have no idea what's your problem.
Thousands of players play the modpack everyday without a problem.
I can just recommend you to test the modpack on a different computer and maybe then figure out what's wrong.
