### ISSUE TITLE
Crash on startup with 0.8.0.

### ISSUE THREAD

**Issue by Lintesrion** [EnderMediaDev/The-1.7.10-Pack#916]
Heho folks! 

For some reason the modpack is crashing on startup. A few days ago everything worked fine. Even after I reinstalled it, the same crash bugs me. Like I said, the crash happens even after a clean install. It works fine when I update to 0.8.1. though. But Our server still runs on 0.8.0, so yeah. :l

Here's the crashlog. I read something about Project Red, but no clue why it should crash on a clean install. Thanks in advance!

http://pastebin.com/sxzPHtJz

**Comment by xJon** [comment]
Just reinstall your client and it'd work. Some things are problematic with downgrading modpack versions.
