### ISSUE TITLE
Can't craft Unstable Induced items, Tinkers' Construct - Extra Utilities problem

### ISSUE THREAD

**Issue by Twingrey** [EnderMediaDev/The-1.7.10-Pack#917]
The name says it all, I can melt the Unstable Ingots from ExtraUtils, but I can only pour the resulting metal into Casting Basin to get a block, but can't pour it into any other mold on Casting Table. NEI says I can't do this as well (screenshot included).
![screen](https://cloud.githubusercontent.com/assets/14851619/10561757/22784f0a-7541-11e5-819a-9b6f25de3057.jpg)

Bug already discussed in this thread, so it's nothing new:
https://www.reddit.com/r/feedthebeast/comments/3iqgdb/extra_utilities_tinkers_construct_cant_create/

**Comment by xJon** [comment]
It's not a big issue and it's not under my control, what can I do?
I won't downgrade Extra Utilities to an older version because the newer ones have bug fixes.
Thanks anyway for reporting. :)
