### ISSUE TITLE
Incompletable Quest?

### ISSUE THREAD

**Issue by DJPBnJ** [EnderMediaDev/The-1.7.10-Pack#918]
In the "Top of the Food Chain" quest, the final stage (or what I assume is the final stage) requires the user to kill a Shibe, aka Doge. However, I haven't been able to find a single Shibe in my world, nor how to spawn one. I've checked in creative, and there doesn't seem to even be an entity by the name of "Shibe". Is this just a minor bug?

**Comment by xJon** [comment]
The spawn eggs are removed from from NEI to not flood it. The shibes do spawn, but only on the "plains" biome. As you can see in my profile picture, I am a shibe, communist one, actually.
