### ISSUE TITLE
Galacticraft - Extra Planets

### ISSUE THREAD

**Issue by badgernz** [EnderMediaDev/The-1.7.10-Pack#919]
This is currently in beta but plays very well, I think it would be a great addition to the pack especially for those interested in space exploration!

http://forum.micdoodle8.com/index.php?threads/1-7-10-extra-planets-beta-update-v0-10-out.5294/

Features of the addon:​
4-8 Tier Rockets​
Dungeons Tier 4 -8(Currently all Creeper Bosses, Custom Bosses will be added soon!) ​
Tools​
Custom Ores​
Custom Config options(Not finished)​
Armor​
Villages on all of the Planets​
Custom Batteries​
Custom Mobs(Entities)​
Custom Achievements​

Planets included in addon:​
Mercury
Venus
Ceres
Jupiter
Saturn
Uranus
Neptune
Pluto
Eris
Kuiper Belt(Coming Soon)
Main Moons for each of the planets(Coming soon)

**Comment by xJon** [comment]
As this type of Galacticraft addon is cool, we don't want to have too many types of planets and tiers of rockets.
Thanks anyway for suggesting :)
