### ISSUE TITLE
Shader installation issues

### ISSUE THREAD

**Issue by Krantorum** [EnderMediaDev/The-1.7.10-Pack#920]
Hello everyone, I'm having trouble with shaders. I'm in stalling it correctly as I have followed multiple tutorials and have installed it previously on other versions but it does not appear to be functioning properly. When I open my options the shaders tab simply isn't there! I've reinstalled multiple times but I have the same effect. Any assistance would be greatly appreciated.
![help](https://cloud.githubusercontent.com/assets/15204657/10594396/6b709bd4-7692-11e5-875e-b9fe714c669d.PNG)
![23rs1](https://cloud.githubusercontent.com/assets/15204657/10594397/6e34bdf0-7692-11e5-911a-d49e555aa503.PNG)

**Comment by Krantorum** [comment]
Those are my screenshots, is anything set up wrong?

**Comment by kmgt08** [comment]
I have the same issues. any help or how did the user resolve the error?

**Comment by Krantorum** [comment]
I've been told that they do not currently work on this version of the
mod-pack, so I took all of the mods I liked (plus a bit more) and made my
own custom mod-pack that I could use with shaders. I could maybe upload it
to Technic, but I really don't feel like asking all the mod creators for
permission atm.

**Comment by kmgt08** [comment]
Ah, Ok. Well thank you for the response. Makes sense I suppose. I guess
I'll try and do what you did. Thanks!

**Comment by Krantorum** [comment]
Yeah, I've tried to install shaders multiple times but with no prevail,
Then the developer told me himself the didn't work with the version of
forge on the mod-pack. You could try downgrading it if you want.

**Comment by kmgt08** [comment]
If possible, can you send list of your mod pack in text form, simply naming
them, I'll try and do the rest.

**Comment by Krantorum** [comment]
I can do that when I get home in about 8 hours or so.

**Comment by kmgt08** [comment]
Hooray. Have a great day. Ttyl.

**Comment by Krantorum** [comment]
You too.

**Comment by Krantorum** [comment]
Alright here are all the mods I am using that I know are comparable, AS
LONG as you follow all of the installation instructions.
I am using version 1.7.10 as most mods are updated for that version.
Download forge V1456 as all versions above that are not compatible with
shaders. NOTE I do not know what order to install these in I just kinda
rolled with it. I'm sorry but you'll have to figure it out.

http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html

SHADERS ----> http://www.shadersmod.net/downloads/

The rest are a list of mods I have installed and is very similar to the
1.7.10 pack, but not the same.

http://www.railcraft.info/releases/

http://www.curse.com/mc-mods/minecraft/treecapitator/2218771

http://www.curse.com/mc-mods/minecraft/animationapi/2221721

http://www.curse.com/mc-mods/minecraft/forge-backpacks

http://www.curse.com/mc-mods/minecraft/balkons-weaponmod/2216459

http://www.mod-buildcraft.com/pages/download.html

http://www.curse.com/mc-mods/minecraft/222213-codechickencore/2207568

http://minecraft.curseforge.com/projects/cofhcore/files/2246919

http://www.computercraft.info/download/

http://minecraft-forum.net/minecraft-mods-downloads/1-7-2-custom-mob-spawner-mod-download-2-2/#.ViqkAvmrSUk

http://www.curse.com/mc-mods/minecraft/231232-deep-sea-diving-mod/2241262

http://www.curse.com/mc-mods/minecraft/224942-dense-ores

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294168-doge-mod-perfect-for-shibes-around-the-world

http://mocreatures.org/downloads

http://www.curse.com/mc-mods/minecraft/225247-ender-zoo

http://flansmod.com/download    (AND ALL CONTENT PACKS)

http://www.9minecraft.net/glsl-shaders-mod/

https://inventory-tweaks.readthedocs.org/en/latest/

http://www.curse.com/mc-mods/minecraft/224535-ivtoolkit

http://www.liteloader.com/download

http://www.curse.com/mc-mods/minecraft/mantle/2215235

http://aidancbrady.com/mekanism/download/        (Download Mekanism,
Generators, and tools)

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2141720-minemenu-v1-2-0-radial-menu-nuff-said

http://www.planetminecraft.com/mod/11-furniture-mod-v10-simple-addtion/

http://www.9minecraft.net/mutant-creatures-mod/

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294968-natura

http://www.curse.com/mc-mods/minecraft/netherores/2233919

http://www.9minecraft.net/not-enough-items-mod/

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293018-opencomputers-v1-5-19

http://openmods.info/      (Only LIB)

http://optifine.net/downloads

http://www.curse.com/mc-mods/minecraft/221857-pams-harvestcraft/2217022

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076388-progressive-automation-upgradeable-machines

http://www.curse.com/mc-mods/minecraft/223150-recurrent-complex

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293062-refined-relocation-1-0-8-solves-your

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2234220-xenos-reliquary

http://www.curse.com/mc-mods/minecraft/221585-roguelike-dungeons/2230658

http://www.curse.com/mc-mods/minecraft/223173-steves-workshop

http://www.curse.com/mc-mods/minecraft/223628-thaumcraft/2227552

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2237271-1-6-4-1-7-10-thaumcraft-nei-plugin-nei

http://www.curse.com/mc-mods/minecraft/227443-thermal-dynamics/2246949

http://www.curse.com/mc-mods/minecraft/222880-thermal-foundation

http://www.curse.com/mc-mods/minecraft/227639-the-twilight-forest/2238492

http://www.9minecraft.net/wild-caves-mod/

My recommended shader pack
http://www.9minecraft.net/sildurs-shaders-mod/

**Comment by Krantorum** [comment]
If you need any help email me, I might try making a modpack soon but I
don't really feel like it.

**Comment by kmgt08** [comment]
Your a great guy. Thanks. I'll kinda try and figure it out as well, have a
good evening. You've been a great help this far.

**Comment by Krantorum** [comment]
I'm making the modpack now Ill email you it when it's up (IF I get it
working).

**Comment by Krantorum** [comment]
Currently exploring file sharing options will be up in about 20 minutes.

**Comment by Krantorum** [comment]
Well I got sick of looking for file sharing options, Iv'e been doing it for
about 3 hours. Good luck with installing your mods.

**Comment by kmgt08** [comment]
Wow, you decided to try and do it. No pressure or anything.... But ppl
depend on you! Jk. Good luck, if I can somehow help out, let me know.

**Comment by queenizzy** [comment]
I have this same issue, what exactly is making the shaders not compatatible?
