### ISSUE TITLE
Modpack with shaders crashes after initializing. 

### ISSUE THREAD

**Issue by Krantorum** [EnderMediaDev/The-1.7.10-Pack#921]
After the game initializes, the game crashes.
Specs and crash report listed below, and help is greatly appreciated.
Specs:
Msi Gtx 960 2gb gddr5 @1400MHZ

i5 4460 @ 3.33GHZ
12 RAM (6 dedicated to launcher)
1TB HDD

**EDITED: Please use a paste-tool: http://pastebin.com/87S89jhc**

**Comment by xJon** [comment]
The 1.7.10 Pack doesn't support Shaders, as a lot of mods don't work with it.

**Comment by Krantorum** [comment]
Thank you.

**Comment by Krantorum** [comment]
Thanks
