### ISSUE TITLE
Client crash on loading into a server

### ISSUE THREAD

**Issue by Annih7** [EnderMediaDev/The-1.7.10-Pack#922]
crash report: http://pastebin.ubuntu.com/12897469/
disabled mods (on both client and server): https://puu.sh/ko3QE/960816baf3.png

Sometimes, my client will crash within a few seconds of loading into the world. It's inconsistent, and I really have no guesses as to what's causing it. I'll start loading chunks, I'll be able to move, but then minecraft will revert to its black/gray loading screen, and then closes.

**Comment by xJon** [comment]
Can you try to remove Fastcraft?

**Comment by kmgt08** [comment]
O, thanks for replying. I was trying to add shaders but soon figured out
some mods are incapable of working with them and is the cause of my issue.
Thanks anyway!

**Comment by xJon** [comment]
Closed due to inactivity.
