### ISSUE TITLE
Game stops responding before title screen

### ISSUE THREAD

**Issue by MCSerf** [EnderMediaDev/The-1.7.10-Pack#923]
Trying to run this pack, but it seems to lock up and I have to force it to close before it ever gets to the main screen, usually after waiting 20+ minutes. I am not using Optifine. I have attached my log below:

http://pastebin.com/qq3sQXa1

Edit: adding my Technic log as well

http://pastebin.com/WTP0v6tD

Also this is not while trying to run or connect to a server. This happens when clicking "play" inside the Technic Launcher.

**Comment by kmgt08** [comment]
Always forever: use a clean minecraft.jar

Make sure you got the pack from a reputable site, if not re download one.

Looks like your configuration is wrong for your mods. Hence I I say re
download, reinstall the entire pack. What's your specs? And has it worked
previously?

**Comment by MCSerf** [comment]
I am using the Technic Launcher, just downloaded the mod today. I also went in and deleted all my old Minecraft files (haven't played for about 1 year) and got the new launcher, let it run and downloaded all the new files. Vanilla 1.8 works fine.

Per your advice I uninstalled the pack, went into the .technic folder and deleted the modpack itself as well. Redownloaded and reinstalled. Same error.

My specs are:
Intel i5-2500k 3.30 GHz
8 GB RAM
Nvidia Geforce GTX 970

Windows 7 Ultimate 64-bit

This pack has never worked for me, but I did just start trying to use it today.

**Comment by xJon** [comment]
There's some missing information required. Please read [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/blob/master/README.md) :)

**Comment by MCSerf** [comment]
I edited to original post to include my Technic logs as well. Apologies.

**Comment by kmgt08** [comment]
https://www.java.com/en/download/installed.jsp go to this link, its a java
link to tell me which v you are using. Click run, and tell me your V.

http://www.technicpack.net/modpack/the-1710-pack.453902 just so i'm sure,
this is the modpack you are trying to use i assume? can you also check to
see if Technic is running x64 of java and not x86 with i think 3 or 4 gb
ram.??

**Comment by MCSerf** [comment]
I attempted to run that first link in Firefox (I usually use Chrome) and it doesn't seem to want to work for me. When I check my Java version using the Configure Java program on my computer it tells me that it is Version 8 Update 65. Technic Launcher tells me the same thing.

For the second link, yes that is the pack I am attempting to run. I have it set to 64-bit, with 4 GB of RAM allocated to it via the launcher.

**Comment by kmgt08** [comment]
it looks like it should be working. im at work for the next 10 hours, ill
try and think of other reasons why its not working. atm im out of ideas.

**Comment by xJon** [comment]
I couldn't find any special error. Did you try to just let it load?

**Comment by xJon** [comment]
Closed due to inactivity.
