### ISSUE TITLE
Lag spikes of the death

### ISSUE THREAD

**Issue by TRICKYRapsody** [EnderMediaDev/The-1.7.10-Pack#924]
Hello world !
I play this modpack since 1 day and i have some lag spikes of the death (Lag spikes like hearthbeat). I haven't this problems in other modpack (like resonant rise).
I installed optifine, and i have a good PC (Not the best but GTX 770, I5 3570 3.2Ghz, 8 Gb RAM..).
I assign 4GB RAM.
Help me please :+1:

**Comment by xJon** [comment]
Could you please provide the fml-client-latest.log file using a [paste-tool](http://paste.ubuntu.com/)? Thanks

**Comment by xJon** [comment]
Closed due to inactivity.
