### ISSUE TITLE
Mod request

### ISSUE THREAD

**Issue by Kilian57** [EnderMediaDev/The-1.7.10-Pack#925]
Hello,
First i habe to say Thank You for this awesome Modpack!
I'm playing with my friends and I noticed that the Addon for the Modular Powersuit is missing. It will add some awesome features to the Suit and it would be brilliant if you could add it.

Another small request would be that you could maybe add Draconic Evolution.

Greetings
Kilian

Sorry for my Bad english

**Comment by xJon** [comment]
Currently the modular powersuits addon is unavailable, there's no updated version of it unfortunately.
About Draconic Evolution - it doesn't really fit the pack and won't be added.

Thanks anyway for suggesting!

**Comment by Kilian57** [comment]
Thank you for your answer.
I found a Version for Minecraft 1.7.10 maybe you can test it.
Here is the link:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1293401-modular-powersuits-addons-mpsa-requires-modular

Its a updated third Party Version.

I hope this link helps you.
Thank you very much.
Am 26.10.2015 12:00 schrieb "Jon" <notifications@github.com>:

**Comment by xJon** [comment]
Its latest version is one year old. :)
