### ISSUE TITLE
Minor Issue 

### ISSUE THREAD

**Issue by TheLegend714** [EnderMediaDev/The-1.7.10-Pack#926]
When I play your modpack I lag quite a bit and have the video settings on max, I'm sure that I can run the game at max without Issues at 60 FPS. Also I add optifine which shouldn't effect me lagging.
My Specs.
http://pcpartpicker.com/p/8qCrkL
Any help is appreciated 8)
P.S. I put more than 8 GB of RAM

**Comment by xJon** [comment]
Can you screenshot your video settings in-game?

**Comment by kmgt08** [comment]
sure, but I have sli gtx 980, every setting i like has been maxed out for
best possible graphics display. unfortunately, my settings presence may not
help you. Have you tried running there game w/o optifine and see if in fact
there is a difference. One other thing, this isn't my modpack, can you send
me a link as to where you found my contact info? thanks.

**Comment by TheLegend714** [comment]
How do I post a screenshot?

**Comment by xJon** [comment]
Google :)

**Comment by TheLegend714** [comment]
Do you want the screenshot with optifine settings or without?

**Comment by xJon** [comment]
Without, try to remove Optifine

**Comment by TheLegend714** [comment]
Here they are.
![capture](https://cloud.githubusercontent.com/assets/12505671/10856832/8cffbbfe-7f07-11e5-8c05-91b4ab3cf949.PNG)

**Comment by xJon** [comment]
- Turn down the render distance to 12
- Put up the max framerate to unlimited 
- Turn off VSync
This should drastically affect your FPS :)

**Comment by TheLegend714** [comment]
Really?

**Comment by ciak2009** [comment]
You should also note Minecraft doesn't support SLI, so its only using one of your 980's.

**Comment by xJon** [comment]
@ciak2009 Where do you see he has two 980s?
