### ISSUE TITLE
Crash when Loading save file

### ISSUE THREAD

**Issue by Solid-Metal** [EnderMediaDev/The-1.7.10-Pack#928]
hey, it's been quite a while since i play MC, thats including this modpack

so i wanna go back, i updated the modpack and when i load my save file, it crash when loading world

heres the crash log : http://pastebin.com/Ba8yGq3A

is there any way to fix this?

**Comment by xJon** [comment]
That's a small problem, try to reinstall your modpack version and it should work :)

**Comment by Solid-Metal** [comment]
yep, it fix, i need to redownload the modpack completely
using reset modpack button on launcher didnt help

thanks!
