### ISSUE TITLE
Running a server with 1.7.10

### ISSUE THREAD

**Issue by drschplatt** [EnderMediaDev/The-1.7.10-Pack#929]
I've been playing the pack now for several months client side by myself.  My friends and I would like to host a private server for ourselves. I have all the hardware/bandwidth I'll need, but I'm brand new to the whole server hosing process.  After googling for a good hour, I'm a bit lost on how I'd actually run a sever with the 1.7.10 pack.  Could someone either give me some basic steps, or point me towards a guide that would instruct me on how to do this?  I downloaded the server zip files from the mod section at technicpak.net but when I run launchserver.bat quite a bit of text scrolls through the cmd window and then it just shuts off.  I really have no idea what I'm doing so I'm not even sure how to troubleshoot it.

**Comment by xJon** [comment]
Did you actually read what's the error? Did you set the "eula.txt" file to true? :)

**Comment by drschplatt** [comment]
I didn't get a change to read the error as the window just closed.   It came about 2 min into the process of various texts scrolling through.   I'll try it again and see if I can catch it before it closes and get an idea of where the problem is happening. 

As to eula.txt, I didn't change anything on it, as I wasn't aware I needed to do that.  I'll give that a shot too.  That's the kind of information I'm looking for though if anyone has some basic "do these things" information they could share with me.  

For example, is the server zip set up so that all I have to do is downloading, unzip it somewhere (even the desktop) and then run the .bat?  Or is there more to it? Also, I know I'm going to need to forward some ports.  My google searching found some information regarding a vanilla server and the ports I would need, will that be the same with 1.7.10?

**Comment by drschplatt** [comment]
Clarification, I downloaded a zip titled, "the-1710-pack_0.8.1" and once decompressed, I'm not finding an eula.txt file anywhere.

**Comment by drschplatt** [comment]
So, I tried running it again and this time it didn't just shut down, but it got to the following point where it says, "Press Any Key To Continue" and when I do, it just closes down.  See the attachment for a screenshot of what I'm talking about. 
![1_7_10_server_error](https://cloud.githubusercontent.com/assets/10793689/10874244/134d8fd2-815c-11e5-8352-c49ec98f6a26.jpg)

**Comment by drschplatt** [comment]
So I re-downloaded the server file, and this time I was able to discover the eula and change it to "true"  Now, after running bat, the following image is what I get.

![1_7_10_screen_grab](https://cloud.githubusercontent.com/assets/10793689/10878862/7857f14a-818b-11e5-9309-8a2197164171.jpg)

**Comment by xJon** [comment]
This means that your server is running but overloaded. No issue though.
