### ISSUE TITLE
Suggestion: Add thaumic energistics to the mod.

### ISSUE THREAD

**Issue by alesandreo** [EnderMediaDev/The-1.7.10-Pack#930]
We have both AE and thaumcraft in the mod, it would be convenient to be able to use this addon mod to interact between the two. 

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2150151-1-7-10-tc4-ae2-thaumic-energistics

**Comment by xJon** [comment]
Currently won't be added, has been suggested a lot already,
Thanks anyway!
