### ISSUE TITLE
Can't start/download Modpack

### ISSUE THREAD

**Issue by Sessha** [EnderMediaDev/The-1.7.10-Pack#932]
I'm using version 0.8.0 for my server and until recently all went fine. Suddenly I get the following message: An error was raised while attempting to read pack info for modpack the-1710-pack, build 0.8.1: connect timed out

After thinking it was an Issue with my Java i went and got the newest again. Deleted the Cache beforeheand and after.
Since that did not help either I deinstalled the Modpack and tried reinstalling, but it always stops now at 1% when loading witchery 0.24.1 zip and gives now a similar error message: An error was raised while attempting to read pack info for modpack the-1710-pack, build 0.8.1: Read timed out

A friend told me the Modpack server might be down but im not sure so im asking =/

**Comment by Sessha** [comment]
Problem solved, can download it now without problems

**Comment by xJon** [comment]
:+1:
