### ISSUE TITLE
game doesnt finish loading screen in over 1 hour 

### ISSUE THREAD

**Issue by Phinix7** [EnderMediaDev/The-1.7.10-Pack#933]
Minecraft got 4GB ram to work with and java version 8 and Im not using the recommended version im using version 0.8.0 without additional mods and Im using original minecraft and technic launcher
my pc specs: 8GB Ram,i7-4702MQ GTX 760m so I think it should run on my pc .... here is the latest log http://paste.ubuntu.com/13115414/

**Comment by Phinix7** [comment]
so I fixed the crash but now it is loading for over 10 minutes and nothing happens

**Comment by Phinix7** [comment]
so I opened my console and after it says Tada it just doesnt respond any more

**Comment by xJon** [comment]
You don't need to allocate more than 3-4GB. Try with that.
Also read [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/blob/master/README.md) to see what missing information you have.

**Comment by Phinix7** [comment]
Java 8 64 bit

**Comment by Phinix7** [comment]
not the recommendeed 0.8.0

**Comment by Phinix7** [comment]
[B#328] 2015/11/05 20:02:11 [INFORMATION] Starting download of http://cdn.technicpack.net/platform2/pack-icons/453902.png?1445183506, with 3 tries remaining
latest launcher log

**Comment by Phinix7** [comment]
client sided

**Comment by Phinix7** [comment]
no optifine

**Comment by Phinix7** [comment]
allocated 4 GB and gave all the missing information. Thanks for help inbefore

**Comment by Phinix7** [comment]
[B#328]  [20:12:11] [Client thread/INFO] [EnderCore]: Removed 0 missing texture stacktraces. Tada! last message in console

**Comment by xJon** [comment]
To get real useful information I need you to post your fml-client-latest.log file with a [paste-tool](http://paste.ubuntu.com/)

**Comment by Phinix7** [comment]
how does this paste tool work :S

**Comment by Phinix7** [comment]
do I just have to copy the latest client log into it ? because I just did and I cant do sth for about 5min... 
and if you need my pc specs: 8GB Ram,i7-4702MQ GTX 760m so I think it should run on my pc ....

**Comment by Phinix7** [comment]
I think I got it hope it helps *.,.*
http://paste.ubuntu.com/13115414/

**Comment by Phinix7** [comment]
I think I reinstalled it about 5 times ...

**Comment by Phinix7** [comment]
So I added all the missing information what now ?

**Comment by Phinix7** [comment]
so it works again my Java version 8. ?? was to new installed 7.?? and now it works ^^

**Comment by xJon** [comment]
Well, if it works it works! :)
