### ISSUE TITLE
Game keeps crashing 

### ISSUE THREAD

**Issue by QuarantinedHobo** [EnderMediaDev/The-1.7.10-Pack#934]
When ever i go on to singleplayer the game crashes. I dont know how to fix it so if someone can help me I would love that.

The report is at the following link: http://pastebin.com/NRTBEtJL

**Comment by xJon** [comment]
Do you have any additional mods?
What's the modpack version used?
When did it start to happen?

**Comment by xJon** [comment]
Closed due to missing information.
