### ISSUE TITLE
IC2 and Universal Cables

### ISSUE THREAD

**Issue by DatsiK96** [EnderMediaDev/The-1.7.10-Pack#935]
I'm having issues with IC2 compact solar arrays and Mekanism Universal Cables.

I'm sure this has been mentioned before and I'm wondering is there's some simple thing I'm missing... but I can't figure it out.

Basically... this...

https://youtu.be/p4yMtFFn0Ug?t=25s

He's got solar arrays directly connected to UC. Great... but I can't achieve the same thing... he then has an MFSU connected to the cables and rigged to output on a redstone signal... great...

Except I can't get it to output at anytime with UC.

I'm pulling hairs out on this. Am I missing something?

**Comment by xJon** [comment]
Maybe, possibly. I'll have to test it myself.

**Comment by DatsiK96** [comment]
Thanks, you rock!

**Comment by xJon** [comment]
Well I do believe you, and if there's a workaround that's perfect.
Unfortunately if Mekanism-IC2 support is not working now there's nothing I can really do.
Thanks for commenting again and investigating yourself :)
