### ISSUE TITLE
GraviSuite Hoving Ability

### ISSUE THREAD

**Issue by DatsiK96** [EnderMediaDev/The-1.7.10-Pack#936]
I'm having trouble with GraviSuite hoving ability.

I know it uses the IC2 mode button, which I've cleared all keys except for those needed to play and made sure none are conflicting.

I've also change the mode key from M to something like 1, or J, etc. But nothing works.

I press mode key then the space bar or vise versa, it doesn't change.

I've read there's incompatibilities with railcraft, because the default key they use is M which is used by default for IC2 mode... But that should be cleared because I changed the key...

Is there something I'm doing wrong?

Edit: it seems to be an issue in general with changing modes.... I can't find any support other than mod key conflicts anywhere else... Anyone have ideas?

**Comment by xJon** [comment]
Maybe a problem with GraviSuite. Basically the issue is that you can't change it to hover mode? and in what mode you're stuck?

**Comment by DatsiK96** [comment]
Sorry, to clerify... I can change IC2 tools mode just fine... it's plainly just GraviSuite tools that I cannot change modes on in general...

And yes, basically, this is causing me being unable to change to hover mode... and I'm stuck in regular flight mode.. Thanks for the quick response! :+1: :)

**Comment by xJon** [comment]
Alright, I'll try to test it myself when I'll be able to.

**Comment by xJon** [comment]
I was able to make it work after I pressed the button configured in here:
![image](https://cloud.githubusercontent.com/assets/8945347/11116864/f1eb3440-893d-11e5-9012-5547cf9eea31.png)

**Comment by DatsiK96** [comment]
This is the fly function, not the hover function. It's the hover function that doesn't work.

It's supposed to work when you press the IC2 Mode button, which is defaulted to M. I've read some places that Railcraft conflicts with that, however, when I change the IC2 Mode button to something other than M, I still can't get it to work.

**Comment by xJon** [comment]
It is the fly function but it enables the hovering mode - I can fly like creative :)
Anyway I understand those issues you mentioned but they're not in my control. This is a problem with the [GravitationSuite mod](http://forum.industrial-craft.net/index.php?page=Thread&threadID=6915) and should be reported directly to it.
