### ISSUE TITLE
Hardcore questing mode

### ISSUE THREAD

**Issue by blackthijs0** [EnderMediaDev/The-1.7.10-Pack#937]
*maybe this is different in the 0.8.1 version*

Currently running 0.8.0
The hardcore questing book has 3 categories. The first one (with technical quests) has one called "Melt it all down". To complete it a player need a few filled drums (in order):
Molten Iron Drum
Liquid XP Drum
Drum
Molten Obsidian Drum
Water Drum
Blood Drum
Lava Drum

The third item on this list appears to be a normal empty drum (since all other drum have the fluid they hold in their name). However having an empty drum in ones inventory is not enough to complete this quest.

Second minor issue:
In looking for a fix I went into edit mode, to see what is behind the quests and I saw there is a quest that comes after "Powered Tools!?". However that is not unlocked, even though I have said quest completed.

**Comment by xJon** [comment]
It got fixed in v0.8.1, you can see in the changelog that some quests have changed. :)
