### ISSUE TITLE
Server crashing due to RAM, Cannot OP self

### ISSUE THREAD

**Issue by erichaknowles** [EnderMediaDev/The-1.7.10-Pack#938]
Hi, i just made an account to ask about this, I have been hosting Minecraft servers for me and my friends for a long time now and can set one up with no hassle at all, the previous version of the 1.7.10 pack worked fine but this time I cannot give myself OP using the ops file given and after running the server for 2-5 minutes it will shutdown and crash most other programs e.g. chrome & Technic launcher. My friends and I cannot play this brilliant mod pack because it isn't so brilliant after all. If you could please help me it would be appreciated. If you need crash reports or anything just ask.

**Comment by xJon** [comment]
Can you please provide the crash report using a paste-tool?

**Comment by erichaknowles** [comment]
Yeah sure, it will be later  on today though I am not at my computer until 4



Sent from Samsung Galaxy S4 powered by Three


-------- Original message --------

**Comment by xJon** [comment]
Closed due to missing information. Will reopen with the required info.
