### ISSUE TITLE
Modpack crashes when i join server/singleplayer!!!

### ISSUE THREAD

**Issue by spideroh1** [EnderMediaDev/The-1.7.10-Pack#940]
this is what the error is!! 
20:24:54 Player spideroh1 disconnected (TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: Connection reset by peer], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}) 20:24:41 hello 20:24:28 Player spideroh1 connected

here is the latest crash code!!!

[crash-2015-11-15_20.34.47-client.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/35654/crash-2015-11-15_20.34.47-client.txt)

**Comment by xJon** [comment]
This means that you don't have Flan's Mod in the server side or something like that.
Anyway you should try to get help directly from [here](https://github.com/FlansMods/FlansMod/issues).

**Comment by xJon** [comment]
That's a modded server? Everyone is playing The 1.7.10 Pack with the same version?

**Comment by spideroh1** [comment]
Yes its modded... and yes we all have the latest version here is the ip 173.236.100.218:39418

**Comment by spideroh1** [comment]
Hello?

**Comment by xJon** [comment]
So try to get support [there](https://github.com/FlansMods/FlansMod/issues). I don't know what's the issue but I know it's relaetd to Flan's Mod, just never encountered it before.
Also try to reinstall the modpack.

**Comment by spideroh1** [comment]
I posted it and this is what they say "Hmm, the mods you have installed may be conflicting with each other. First try loading up Flan's by itself, to see if it crashes again. If not, it is a mod conflicting.

**Comment by xJon** [comment]
So try to reinstall the modpack :)

**Comment by spideroh1** [comment]
I did and having the same problem... Could we skype? so i could show you whats going on!

**Comment by xJon** [comment]
Try to completely delete the modpack (after you create a backup from the "saves" folder) and install it again.

**Comment by spideroh1** [comment]
i do that when you say reinstall... i delete everything

**Comment by xJon** [comment]
Where? from `.technic/modpacks/the-1710-pack` folder?

**Comment by spideroh1** [comment]
Yeah

**Comment by spideroh1** [comment]
Nothings working..

**Comment by spideroh1** [comment]
Please find a fix fast... this is pissing me off i cant join my own server

**Comment by xJon** [comment]
So try to reinstall the server. It should work. It works for everyone else.
When did the problem start? I never heard of it.

**Comment by spideroh1** [comment]
started about a week ago... nothing unusual...

**Comment by spideroh1** [comment]
It is kinda hard to re install the server... but ill try...

**Comment by spideroh1** [comment]
I found the prblem!!!! i accidently had a flans addon in my file... i guess i spawned the flans item in and i couldnt join cause i had it on.... i just reset the map and it worked!!! thanks for the help!

**Comment by xJon** [comment]
Awesome! I don't think I could've find this issue, but good that you troubleshooted it yourself.
