### ISSUE TITLE
Game won't launch

### ISSUE THREAD

**Issue by Smitherington** [EnderMediaDev/The-1.7.10-Pack#942]
Hi there, I'm having issues with launching the mod pack. Every time I launch I get the minecraft window to open but it just stays black and says not responding a couple of times, then closes after about 15 mins and returns to technic window. So far I've tried reinstalling the mod pack, reinstalling technic launcher, reinstalling minecraft and deleting liteloader like suggest in a previous issue post. nothing so far has help but I am able to play it on all my other OSX devices. I put the latest FML log in but if you need other info let me know. 

Running Windows 10 with the latest Java 64-bit and I've had the RAM set to 3Gb 4Gb and 6Gb out of the 8Gb available 

http://paste.ubuntu.com/13359137/

**Comment by xJon** [comment]
Try to set it to 3GB and wait about 10 minutes maximum.
Your log doesn't show anything special, just 6 minutes of loading, which may occur due to your HDD or CPU.

**Comment by xJon** [comment]
Closed due to inactivity.
