### ISSUE TITLE
ME system not working

### ISSUE THREAD

**Issue by ThisTNTSquid** [EnderMediaDev/The-1.7.10-Pack#943]
I cannot right those ME system components when the ME system is online. What the **** is happening?!?!   It's only happening to me!!

**Comment by xJon** [comment]
Hello,
If you ME system doesn't work you probably did something wrong.
You should ask for help from other players knowing how to play with the mod, or directly from the [mod's repo](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues). Just be sure to give them more information :)
