### ISSUE TITLE
Savefile won't open

### ISSUE THREAD

**Issue by Sirtain** [EnderMediaDev/The-1.7.10-Pack#944]
Hello! I have a problem with my game. It opens up like usual and i can access the menu fine, but when i load my world, the window goes white juste after the ''loading world'' text appears. it doesn't crash or anything but it stays white forever. help plz

**Comment by Sirtain** [comment]
[plain.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/40916/plain.txt)

**Comment by xJon** [comment]
'[B#328] 2015/11/21 13:19:07 [INFOS]  [13:19:07] [Server thread/FATAL] [FML]: The world state is utterly corrupted and this save is NOT loadable
[B#328] 2015/11/21 13:19:07 [INFOS]  
[B#328] 2015/11/21 13:19:07 [INFOS]  There is a high probability that a mod has broken the
[B#328] 2015/11/21 13:19:07 [INFOS]  ID map and there is
[B#328] 2015/11/21 13:19:07 [INFOS]  NOTHING FML or Forge can do to recover this save.
[B#328] 2015/11/21 13:19:07 [INFOS]  
[B#328] 2015/11/21 13:19:07 [INFOS]  If you changed your mods, try reverting the change
[B#328] 2015/11/21 13:19:07 [INFOS]  java.lang.IllegalStateException: Can't map item ThermalFoundation:tool.fishingRodLead to id -1 (seen at: 4096), already occupied by null, blocked false, ItemBlock false
[B#328] 2015/11/21 13:19:07 [INFOS]  	at cpw.mods.fml.common.registry.GameData.injectWorldIDMap(GameData.java:525) ~[GameData.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at cpw.mods.fml.common.FMLContainer.readData(FMLContainer.java:277) [FMLContainer.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:403) [FMLCommonHandler.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:124) [ayq.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.world.World.<init>(World.java:220) [ahb.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) [mt.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62) [bsx.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]'

**Comment by xJon** [comment]
> [B#328] 2015/11/21 13:19:07 [INFOS]  [13:19:07] [Server thread/FATAL] [FML]: The world state is utterly corrupted and this save is NOT loadable
[B#328] 2015/11/21 13:19:07 [INFOS]  
[B#328] 2015/11/21 13:19:07 [INFOS]  There is a high probability that a mod has broken the
[B#328] 2015/11/21 13:19:07 [INFOS]  ID map and there is
[B#328] 2015/11/21 13:19:07 [INFOS]  NOTHING FML or Forge can do to recover this save.
[B#328] 2015/11/21 13:19:07 [INFOS]  
[B#328] 2015/11/21 13:19:07 [INFOS]  If you changed your mods, try reverting the change
[B#328] 2015/11/21 13:19:07 [INFOS]  java.lang.IllegalStateException: Can't map item ThermalFoundation:tool.fishingRodLead to id -1 (seen at: 4096), already occupied by null, blocked false, ItemBlock false
[B#328] 2015/11/21 13:19:07 [INFOS]  	at cpw.mods.fml.common.registry.GameData.injectWorldIDMap(GameData.java:525) ~[GameData.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at cpw.mods.fml.common.FMLContainer.readData(FMLContainer.java:277) [FMLContainer.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:403) [FMLCommonHandler.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:124) [ayq.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.world.World.<init>(World.java:220) [ahb.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) [mt.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62) [bsx.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]

**Comment by xJon** [comment]
`[B#328] 2015/11/21 13:19:07 [INFOS]  [13:19:07] [Server thread/INFO] [FML]: Injecting existing block and item data into this server instance
[B#328] 2015/11/21 13:19:07 [INFOS]  [13:19:07] [Server thread/FATAL] [FML]: The world state is utterly corrupted and this save is NOT loadable
[B#328] 2015/11/21 13:19:07 [INFOS]  
[B#328] 2015/11/21 13:19:07 [INFOS]  There is a high probability that a mod has broken the
[B#328] 2015/11/21 13:19:07 [INFOS]  ID map and there is
[B#328] 2015/11/21 13:19:07 [INFOS]  NOTHING FML or Forge can do to recover this save.
[B#328] 2015/11/21 13:19:07 [INFOS]  
[B#328] 2015/11/21 13:19:07 [INFOS]  If you changed your mods, try reverting the change
[B#328] 2015/11/21 13:19:07 [INFOS]  java.lang.IllegalStateException: Can't map item ThermalFoundation:tool.fishingRodLead to id -1 (seen at: 4096), already occupied by null, blocked false, ItemBlock false
[B#328] 2015/11/21 13:19:07 [INFOS]  	at cpw.mods.fml.common.registry.GameData.injectWorldIDMap(GameData.java:525) ~[GameData.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at cpw.mods.fml.common.FMLContainer.readData(FMLContainer.java:277) [FMLContainer.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at cpw.mods.fml.common.FMLCommonHandler.handleWorldDataLoad(FMLCommonHandler.java:403) [FMLCommonHandler.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:124) [ayq.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.world.World.<init>(World.java:220) [ahb.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.world.WorldServer.<init>(WorldServer.java:97) [mt.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:62) [bsx.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:92) [bsx.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387) [MinecraftServer.class:?]
[B#328] 2015/11/21 13:19:07 [INFOS]  	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]`

**Comment by Sirtain** [comment]
so what can i do? i havent change anything in the mods and i didn't touch or change anything...

**Comment by xJon** [comment]
`The world state is utterly corrupted and this save is NOT loadable`
`There is a high probability that a mod has broken the ID map and there is NOTHING FML or Forge can do to recover this save.`

**Comment by Sirtain** [comment]
so my save is basically fucked? and do you have any idea why it happened?

**Comment by xJon** [comment]
The game can't load the `ThermalFoundation:tool.fishingRodLead` item. Did you change anything related to it?

**Comment by Sirtain** [comment]
no i dont even know how to change that...
would removing the item would fix the problem?

**Comment by xJon** [comment]
You **try** to go to `.technic\modpacks\the-1710-pack\config\cofh\thermalfoundation` and in `common.cfg` change:
`    Lead {
        B:Armor=true

        Tools {
            B:Axe=true
            B:Bow=true
**            B:FishingRod=false**
            B:Hoe=true
            B:Pickaxe=true
            B:Shears=true
            B:Shovel=true
            B:Sickle=true
            B:Sword=true
        }

    }`

**Comment by Sirtain** [comment]
ok im gonna try

**Comment by Sirtain** [comment]
if it works, will crafting the fishing rod thingy crash my game or no

**Comment by xJon** [comment]
It won't be enabled as an item.

**Comment by Sirtain** [comment]
oh ok :)

**Comment by Sirtain** [comment]
it didn't work it did the exact same thing

**Comment by Sirtain** [comment]
do you need the new log?

**Comment by xJon** [comment]
Sure, just post in a [paste-tool](http://paste.ubuntu.com/).

**Comment by Sirtain** [comment]
yeah wait a sec

**Comment by Sirtain** [comment]
[techniclauncher_2015-11-21.log.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/40920/techniclauncher_2015-11-21.log.txt)

**Comment by xJon** [comment]
It gives the same item again, are you sure you disabled it in the configuration file?

**Comment by Sirtain** [comment]
yes but ill try again

**Comment by Sirtain** [comment]
only in lead or in all?

**Comment by xJon** [comment]
Only in lead.

**Comment by Sirtain** [comment]
i deleted the log from today and i will run it again

**Comment by Sirtain** [comment]
[techniclauncher_2015-11-21.log.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/40922/techniclauncher_2015-11-21.log.txt)

**Comment by xJon** [comment]
Same issue. You can try to ask [there](https://github.com/CoFH/Feedback/issues), just be sure to give them your log. Not sure what else I can do - it's a mod-bug.
