### ISSUE TITLE
Severe Lag, vanilla 1.7.10 Pack

### ISSUE THREAD

**Issue by Firstyminator** [EnderMediaDev/The-1.7.10-Pack#945]
Having severe lag with my vanilla 1.7.10 Pack. 

Java updated to 1.8.0_66 ( 64 bit )

Memory usage ingame is around 17-35 % ( 2700mb of 13000mb )

Using Pure BD Craft with Patch actually lowers ram usage, but offers greater lag. ( F3 menu shows me fps is 70+ )

Only added mod to the server-pack is ForgeEssentials. And lag occurrs with and without it.

Herobrine not located... could be tho!

**Comment by xJon** [comment]
Can you please provide the fml-server-latest.log file using a [paste-tool](http://paste.ubuntu.com/)?

**Comment by Firstyminator** [comment]
Gonna be a killer FML :) 

http://paste.ubuntu.com/13477578/

**Comment by xJon** [comment]
The server is running perfectly fine, the lag is on your client.
I doubt something is wrong there though. What's your setup?

**Comment by Firstyminator** [comment]
Thats good news indeed! Well im running: 

Intel I5 2500k @ 4.5Ghz
16GB of ram ( allocated 7GB to Java - Game telling me atm that its using 38% of it )
Windows 10 with newest 64 Bit java (.66 )

Actually now, it's running a bit more smooth. But i've disabled the Natura tree spawning.

When i do enable PureBDCraft, the fps stays the same ( around 120 ) and memory usage ups about 10% but the lag spikes are horrible and making the game pretty unplayable.

Could it be the Java memory allocation?

**Comment by Firstyminator** [comment]
Installed Optifine, and the results are pretty weird. Seems like Tick lagspikes, mixed with ChunkLoading. Could be just 1.7.10 trolling ?

https://www.dropbox.com/s/3cwp5rc59b34m36/TickLag.png?dl=0

**Comment by xJon** [comment]
Try to allocate only 3-4GB of RAM and see if anything changes.

**Comment by Firstyminator** [comment]
Removed the Pure BD texture pack completely. and allocated 4GBs of ram. Seems to have a stable decent FPS at 177, but still with some tick spikes on chunk loading. Much lower CPU usage tho :) :)

Logfile for reference:
http://paste.ubuntu.com/13497533/

**Comment by xJon** [comment]
Well I don't see any special error and I wouldn't call that severe lag anymore :)
