### ISSUE TITLE
[HELP] Minecraft closes after 'Mojang' loading screen and technic launcher comes up again

### ISSUE THREAD

**Issue by EisTeeEis** [EnderMediaDev/The-1.7.10-Pack#946]
Hi I would like the modpack The 1.7.10 play with friends involving only with me not always when I start the game is the sceen charging and then comes the tech launcher again please help

I play the version 0.8.0

with the addition of mods :
Immibiss Micro Blocks v1.7.10
advanced genetics v1.7.10
immibis -core v1.7.10
portalgun v4.0.0

even without the mods is not I have the java update 66 strikes so the newest game I start with 3 GB to 5 GB
I use 8GB RAM
I despair

**Comment by xJon** [comment]
Please read [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/blob/master/README.md) to understand the crash-report I need you to provide so I'd be able to help you :)

**Comment by EisTeeEis** [comment]
Here the crash report 
[crash-2015-11-26_18.15.12-client.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/45139/crash-2015-11-26_18.15.12-client.txt)

Here are the other additional mods
Immibiss-Microblocks-Mod-1.7.10 which comes into minecraft.jar
and in the mdos folder
advancedgenetics-1.7.10-1.5.7
iChunUtil-4.2.2
Immibis-Core-1.7.10
PortalGun-4.0.0-beta-4

I have java 8 Update 66 64Bit
and the tech launcher gets 3 to 5 GB of RAM and 8 GB are installed

**Comment by xJon** [comment]
Logistics Pipes has some issues, not sure why.
If you have a modified version of the modpack you can try to update Logistics Pipes, or remove one of the added mods.
