### ISSUE TITLE
Single player world crashes

### ISSUE THREAD

**Issue by Magentafuschine** [EnderMediaDev/The-1.7.10-Pack#947]
Hiya

I have built a world and now it won't load.  I have no crash reports it just pops me back at the technic 1.7.10 page.  can any one help?

**Comment by xJon** [comment]
> Please read [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/blob/master/README.md) to understand the crash-report I need you to provide so I'd be able to help you :)

**Comment by Magentafuschine** [comment]
Please excuse my ignorance lol.  How do i get the logs?

**Comment by xJon** [comment]
`.technic/modpacks/the-1710-pack/crash-reports`

**Comment by Magentafuschine** [comment]
Thanks, I found them.  I think i managed to do the paste tool.  not sure
how you send it as there is only a paste button.  hope you got it.

On Thu, Nov 26, 2015 at 6:29 PM, Jon <notifications@github.com> wrote:

> .technic/modpacks/the-1710-pack/crash-reports
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnderMediaDev/The-1.7.10-Pack/issues/947#issuecomment-159973274>
> .
>



-- 
Ivy West

**Comment by xJon** [comment]
You need to send here the link of the paste.

**Comment by Magentafuschine** [comment]
http://paste.ubuntu.com/13540557/

On Fri, Nov 27, 2015 at 12:34 AM, Jon <notifications@github.com> wrote:

> You need to send here the link of the paste.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EnderMediaDev/The-1.7.10-Pack/issues/947#issuecomment-160011518>
> .
>



-- 
Ivy West

**Comment by xJon** [comment]
You have a problem with the harvester block.
You'll have to remove this block from your save with a program or something like that to fix the ticking block entity :)
