### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by asmenasa** [EnderMediaDev/The-1.7.10-Pack#949]
So I've been having this crash since 2 days ago. Can somebody help me pls

[crash-2015-11-29_12.16.55-server.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/46647/crash-2015-11-29_12.16.55-server.txt)

**Comment by xJon** [comment]
Your questing data is invalid. You can reset in inside of your world save :)
