### ISSUE TITLE
Suggestion- Adding mods with mobs

### ISSUE THREAD

**Issue by crazyarms** [EnderMediaDev/The-1.7.10-Pack#951]
First and foremost I just want to say thank you for the best modpack I've ever played.

I don't really have a particular mod in mind mostly because I'm kind of outdated (just started back on minecraft and haven't played since 1.4?)

I noticed that the mod does not have as many mobs as I would have expected given the magnitude of everything else.

My hands down favorite was Mo' Creatures because of the shear number of mobs added, but I also enjoyed smaller ones like Elemental Creepers as well. even something like Exotic Birds mod sounds cool.

I also just enjoy anything with just NPCs period. Millenaire was awesome and I enjoyed Minecolony (now MineColonies but not even updated to 1.7.10). Evil Minions seems like a fun addition as well (although seemed abit buggy when I tried playing)

Also on a side note,
I did enjoy Battle Towers mod as well.

Like I said though, I'm alittle out of the loop, so if you know that any/all of these would just complicate the modpack, just forget I even mentioned it.

Thanks,

Crazyarms

**Comment by spideroh1** [comment]
I +1 this! but also!!!!! the Farlanders mod is a must!!!

**Comment by Smalfinn** [comment]
Defo +1

**Comment by TANGOjPANDA** [comment]
I think this is a great idea maybe you could consider Grimoire of Gaia it adds a few mobs that are not overly op. 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1284614-grimoire-of-gaia-3-1-2-7-updated-10-03-2015-mobs

**Comment by xJon** [comment]
So what's the list of mods you guys are suggesting exactly?

**Comment by Smalfinn** [comment]
Mo's Creatures is the only mod that we need.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1272337-mo-creatures-v8-0-1-with-ghost-wyverns-minecraft-1

**Comment by xJon** [comment]
Unfortunately Mo Creatures does not let public modpacks the required permissions, so we couldn't add the mod even if we wanted to.
Thanks anyway for suggesting!

**Comment by Smalfinn** [comment]
Wow that sucks :/
