### ISSUE TITLE
Client crash when putting Mekanism Induction Casing into crafting grid

### ISSUE THREAD

**Issue by Nillecram** [EnderMediaDev/The-1.7.10-Pack#953]
Version 0.8.1.
Mac OSX 10.10.5
Java 1.8.0_60-b27 (64 bit)
Technic Launcher build 4.328

As the title say, when putting the induction casing block (1785:1) into a crafting grid (ME Crafting terminal, ME Pattern terminal, Crafting station, ...), the client crash.

Hope it will help.

[Crash.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/50225/Crash.txt)

**Comment by xJon** [comment]
https://github.com/EnderMediaDev/The-1.7.10-Pack/issues/911
Nothing we can do about it unfortunately. You can try to report it again directly to the mod authors.
Thanks anyway for reporting!
