### ISSUE TITLE
HOW TO DELETE CB's DepLoader 

### ISSUE THREAD

**Issue by sbjetsetter** [EnderMediaDev/The-1.7.10-Pack#955]
I didnt download CB's Deploader that I think of. Im trying to find it in my files to get rid of it because it keeps messing up my minecraft by downloading baubles wrong version but when I go to find it its NO WHERE its really  frustrating so please help. i took a pic of it with my phone when this little application pops up but I cant get to it and i think its java by the little icon at the top left corner of the pop up

**Comment by sbjetsetter** [comment]
please anyone?

**Comment by xJon** [comment]
You don't need to download any additional files to play the modpack. If you messed things up, try to backup your saves and reinstall.

**Comment by sbjetsetter** [comment]
no I dont want the mod pack anymore im trying to get rid of CB's Deploader xJon

**Comment by xJon** [comment]
That's an automatic action to download required libaries
