### ISSUE TITLE
Project Red OreGen

### ISSUE THREAD

**Issue by Sovreign** [EnderMediaDev/The-1.7.10-Pack#956]
Hey Jon,

Possible issue with Project red, it seems the Ore generation for everything has been set to False by default (I assume to limit duplicate ores) But there is one ore, 'Electrotine' that is needed for a lot of ProjectRed devices, and progression is not possible without it. Was this turned off for a reason? i have re-enabled it on my server, and no issues so far. 
May want to change that config line

Cheers, 
Sov

Also, fantastic work on the modpack, thanks for all your hard work.

**Comment by xJon** [comment]
What devices require that ore specifically?

**Comment by xJon** [comment]
The ingot is used mostly only for ProjectRed's jetpacks. As a whole ore generation isn't really required for one item which a lot of mods already provide, the generation has been disabled.

**Comment by Sovreign** [comment]
Unless the mod has been changed significantly--

http://ftb.gamepedia.com/Electrotine_Alloy_Ingot

From ftb, but still relevant i believe, the ingot is quite important
-Sov

**Comment by xJon** [comment]
I'll check that again later.

**Comment by xJon** [comment]
Currently all the uses available for electrotine are related to items that are pretty much duplicates, and due to that we don't want this ore generation enabled.
If you want, you can enable it yourself manually.
Thanks anyway for reporting! :)

**Comment by Sovreign** [comment]
Just curious, whats the duplicate block for frame motors?

**Comment by xJon** [comment]
Basically all the [Funky Locomotion](http://minecraft.curseforge.com/projects/funky-locomotion) mod.

**Comment by Sovreign** [comment]
alright cheers, havn't used FL yet
