### ISSUE TITLE
Can't talk in servers

### ISSUE THREAD

**Issue by MrBringBacon** [EnderMediaDev/The-1.7.10-Pack#957]
Currently hosting a minecraft  server with this pack, the only issue is that whenever you try to talk, it kicks you.
I thought it was the server hosters fault at first, or the plugins
I removed all plugins and the problem persists. 

console log: 14.12 09:41:52 [Server] INFO BringBacon left the game.
14.12 09:41:52 [Disconnect] User BringBacon has disconnected, reason: Internal Exception: java.lang.ArrayIndexOutOfBoundsException: -1

Any help would be great.
Thank you in advance.
-Bacon

**Comment by xJon** [comment]
ColorChat is incompatible with KCauldron. Remove the mod if needed.
