### ISSUE TITLE
Magical Crops Platinum Seeds

### ISSUE THREAD

**Issue by Ukelelechris** [EnderMediaDev/The-1.7.10-Pack#958]
Hey,

This issue has been brought up before on the internet, but the last I can find anyone talking about it is from last year. Platinum seeds in magical crops currently take "Nickel Crop" instead of nickel seeds, and as far as I can tell Nickel Crop is unobtainable. Can supply a screenshot if needed. I even tried using precision shears on them, but sadly it just outright destroys the crop. I know this isn't the packs fault, I just thought that you guys would know how to get this fixed because I have no idea.

Thanks.

**Comment by xJon** [comment]
Nothing we can do, really, about the issue. This got reported already many times.

**Comment by martinegui** [comment]
This is a MOD problem, the author is already working at Magical Crops 4, so I think he will not fix this issue.
