### ISSUE TITLE
Batch Error

### ISSUE THREAD

**Issue by StumpySequoia** [EnderMediaDev/The-1.7.10-Pack#960]
I believe it would be a server overload, but my server once it reaches dimension 6, after I load the batch file, my CPU usage goes from 60%~ to 12%~ and the batch just stops right there and begins to give time out errors.

Currently 4GB are allocated for RAM and I've gotten the same results every time.

Is there anyway I can fix server overload?
_________________
After doing further testing it got past all of the dimensions but then Flans mod loaded a new file and then overload/time out error.

**Comment by xJon** [comment]
Can you provide your fml-server-latest.log file using a [paste-tool](http://paste.ubuntu.com/)?

**Comment by StumpySequoia** [comment]
Here you go: http://paste.ubuntu.com/14100279/

**Comment by xJon** [comment]
Try to remove the Chisel mod and launch again. Does it work?

**Comment by xJon** [comment]
When did the issue start to happen? Did it work before?

**Comment by StumpySequoia** [comment]
It hasn't worked once, and the halt would always occur within a couple lines of the same point. I have re-downloaded it a couple times, but it continues to halt in the same spot.

**Comment by xJon** [comment]
What's your version of Java? it's something related to that and security.

**Comment by StumpySequoia** [comment]
The java file that came with the server download is 1.7.10-10.13.4.1517 for forge
I personally use any version 64-bit version

**Comment by xJon** [comment]
It's not a Java file. You need to have Java installed on your computer.

**Comment by StumpySequoia** [comment]
Ah okay.
If it is Java Runtime I haven't updated that in AGES. Would that be what I need to update, correct?

**Comment by xJon** [comment]
Just make sure you're using Java 8 in its latest version.

**Comment by StumpySequoia** [comment]
It's up to date but no cigar

**Comment by xJon** [comment]
Wait, I checked again the log and I think there was a misunderstandment.
You're world is launching until it randomly closes, possibly by the `/stop` command.
If you think that messages like `[10:53:13] [Server thread/DEBUG] [FML/]: The world 33ab7038 (world) may have leaked: seen 10 times.` are errors, they aren't, you can keep playing :)

**Comment by StumpySequoia** [comment]
However my issue is server overload I believe. It overloads apparently and stops going anywhere with loading. I once attempted leaving it be for a few hours but it kept going on about overload.

**Comment by xJon** [comment]
Couldn't find any overloading reports on your log.

**Comment by StumpySequoia** [comment]
That's weird. It logs say the error you mentioned, but the CMD just gives me the whole nine yards about a time out, and that the world may have overloaded. Also if I just leave it running the server just has a red X instead of a golden V.

**Comment by xJon** [comment]
Can you at least provide a screenshot?

**Comment by StumpySequoia** [comment]
I let it sit for about half an hour, and now it works. AKA all I had to do was wait it out until it started doing the server back up stuff. Thanks much!

**Comment by xJon** [comment]
:+1:
