### ISSUE TITLE
Client ram leakage?

### ISSUE THREAD

**Issue by Yorick1234** [EnderMediaDev/The-1.7.10-Pack#965]
I'm running my client and our server on my freshly installed computer, using java 7 64 bit, as I did before. I'm running 1.7.10 modpack servers for some good months now, we really enjoy it. 

My client is giving me issues though, memory related, since i reinstalled from scratch and migrated to 0.8.1. (I also run the 64pix editions of pure bd and the 1.7.10 modpack textures packs.) My client is running in the 9 gigs upon fresh start and runs in the 12 gigs upon one hour of gameplay approximatly. This all reaches my computer limits, which is at 16gb, and although i have an additional storage as windows dump cache, it all freezes down, kicking all players from the server, my computer not responding for some time after, not even using task manager. One on my co-players runs the same client with packs as i do, and only runs under 5 gb, no leakage over time either. Only difference is that he uses java 8. I turned the technic launcher settings to use 8 gb max, but that does no difference. I've tried both the 0.7.9 and 0.8.1 servers to run in a java 8 64 bit environment, but that didn't work, that's why i reverted back to java 7. 

First question: Is it correct i cannot run the server with java 8?

Second question: Any idea what is wrong with my client that it runs so high in memory or may even have a leakage?

**Comment by xJon** [comment]
What happens if you allocate "just" 3GB to the modpack?
Also I need your latest log, using a paste-tool.

**Comment by Yorick1234** [comment]
Yeah sure, i included two logs in this post.

When I set my technic launcher to just use 3 GB it remains at about 4,5 GB. Which is fine for me. Im gonna keep that setting.

[techniclauncher_2015-12-23.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/71165/techniclauncher_2015-12-23.txt)
[techniclauncher_2015-12-20.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/71166/techniclauncher_2015-12-20.txt)

**Comment by xJon** [comment]
So everything is okay?

**Comment by Yorick1234** [comment]
Yes it is, thank you.
