### ISSUE TITLE
Incompatibility

### ISSUE THREAD

**Issue by TheLegend714** [EnderMediaDev/The-1.7.10-Pack#966]
The version of forge in this mod pack does not work with the newest version of optifine.

**Comment by xJon** [comment]
Can you provide a crash report or something?

**Comment by TheLegend714** [comment]
ya there you go!
http://pastebin.com/QQrDEcSp

**Comment by xJon** [comment]
It's an issue with FpsPlus.

**Comment by TheLegend714** [comment]
Thank you!
