### ISSUE TITLE
Suggestion - new mods Rotary and Reactor craft

### ISSUE THREAD

**Issue by rosoch1** [EnderMediaDev/The-1.7.10-Pack#967]
Hi, I'm not sure, if my question is better to ask at this forum or at GitHub, anyway I'll try it here: I definitely love this modpack, it's the best one I've tried so far! :) 

Has the author heard or thought about adding rotarycraft, eventually about reactorcraft? These two are really good mods, where is tried to make some processing very realistic, and a lot of new ways of getting energy, I guess that author of these two must have given part of his soul into them :D 
I guess that these can really add some more new features to this pack... If you'd be interested, here is very well made tutorial series: https://www.youtube.com/playlist?list=PLOWJFCNCQEFg76tqfb9n3PaJ6Ygb-NWXU 

Thanks for the answer, even negtive :)

**Comment by xJon** [comment]
These mods have been suggested already many times and we decided not to add them. They just don't fit the modpack.
Thanks anyway for suggesting :)
