### ISSUE TITLE
Save Issues?

### ISSUE THREAD

**Issue by SimplyHatted** [EnderMediaDev/The-1.7.10-Pack#968]
I do not know if the problem is with with my Mc but I'll post this anyway. 

I have experienced that after I make decent progress in the pack the save just dissapears. Today I decided to come on my world and it wasn't there, I went into the folder where the save files are & it was there; But it was not showing up on Mc. I cant play the modpack if that keeps happening. 

I don't think that this is a problem with the memory, I've allowed my mc to use 6-7gb. 

Any help?

**Comment by xJon** [comment]
You really shouldn't allocate more than 3-4GB of RAM for your MC client.
Anyway, I'll need your fml-client-log.latest file of yours to get more information. Please use a paste-tool.

**Comment by SimplyHatted** [comment]
Alright, I will try to do it get it soon; Where would I find that? I don't want to search a good half-an-hour for that file.

**Comment by xJon** [comment]
Read [this](https://github.com/EnderMediaDev/The-1.7.10-Pack/blob/master/README.md).

**Comment by xJon** [comment]
Closed due to missing information.
