### ISSUE TITLE
Server?

### ISSUE THREAD

**Issue by Eogy** [EnderMediaDev/The-1.7.10-Pack#969]
Hello, I want to play the modpack with a friend but - I do not know how to make the server, any help?

EDIT

I did something but every time I try to go on it it says 'Incompatible FML modded server'

**Comment by xJon** [comment]
You need to start the server with the "LaunchServer.bat" file.

**Comment by Eogy** [comment]
I am, now it shows the 'vanilla' sign and wherether I click on the server it tells me 'Failed to login-

**Comment by xJon** [comment]
So try to reinstall the server, it shouldn't happen :)
