### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Jakorosin** [EnderMediaDev/The-1.7.10-Pack#970]
I came back to the modpack after being gone for a few months. I updated, and went to load my last save game... and it crashed out.

Here's the error report: http://paste.ubuntu.com/14216547/

It looks, to my admittedly inexperienced eyes, like the issue is with Numina. Is there a way to fix this, either by disabling that mod selectively or removing it altogether?

**Comment by Jakorosin** [comment]
UPDATE: This is not a problem specific to my saved world. I attempted to start a new world and got the exact same crash.
See here: http://paste.ubuntu.com/14217317/

**Comment by xJon** [comment]
First of all, it's a very nice picture you got there.
Now for your issue, simply reset MachineMuse's configuration files in the modpack's folder to fix the issue.
