### ISSUE TITLE
random ctds

### ISSUE THREAD

**Issue by ziba1** [EnderMediaDev/The-1.7.10-Pack#971]
Hi, playing a modified version of this pack on my server.  For the past two hours been getting random ctd's, but no one else is, makes me think its a client issue, but not sure what it could be.  Game just closes completely no error message first or anything.

Its happened, when Ive teleported (via server admin teleport - not modded) to another point, when I teleported back to where I was originally, and when Ive died, with also 4-5 times just completely random - killed a cow, ctd, sprinted, ctd, opened inventory, ctd, just random.

 I'm wondering if the extra mods we have might be causing an issue, but noone else has randomly ctd as of yet The extra mods we play with are:
ars magica
chococraft
thaumic warden
thamaturgical knowledge
animation api - ars magica requires
minions mod
archimedes ships
oceancraft
zombie awareness 
falling meteors

Heres my client log, but I cant make heads or tails of this stuff haha.

http://pastebin.com/ycjTcM4H

My java is up to date, so I dont think it could be that

Any help would be fantastic

**Comment by xJon** [comment]
> falling meteors

**Comment by ziba1** [comment]
in what sense ? cheers for the fast response btw haha ?

**Comment by xJon** [comment]
No idea, just know what's the mod causing it.

**Comment by ziba1** [comment]
ok, sucks, love that mod haha, cheers man

**Comment by ziba1** [comment]
well the world didnt corrupt at least, managed to log back in without any issue, but now one of my friends logs in and immediately ctd's, shes deleted the mod from the mods folder herself, dont get why she'd now have an issue :o
