### ISSUE TITLE
unable to start world

### ISSUE THREAD

**Issue by Legomax98** [EnderMediaDev/The-1.7.10-Pack#972]
Hi, for some reason, when I try and launch my world, it gets to the point that it starts to load the world, but then crashes. It has run perfectly fine several times before today. I can't figure out why.

http://pastebin.com/KkquEVt9

**Comment by xJon** [comment]
Did you add or change any of the mods yourself?

**Comment by Legomax98** [comment]
Nope, I've only played with the mods already in the pack

**Comment by xJon** [comment]
When did the issue start to happen? any idea?

**Comment by xJon** [comment]
Closed due to inactivity.
