### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Ukelelechris** [EnderMediaDev/The-1.7.10-Pack#973]
Hey, thought I'd report this. I just randomly started crashing when breaking relocators, but it didnt used to happen.

http://pastebin.com/ds7BwcQt

**Comment by xJon** [comment]
We're using the latest version of RefinedRelocation, so this should be reported [there](https://github.com/Dynious/RefinedRelocation/issues).
As for fixing your issue, you'll have to manually delete the ticking entity using [NBTExplorer](https://www.youtube.com/watch?v=fWUUsdp3pJ8).

**Comment by Ukelelechris** [comment]
Thanks for pointing me in the right direction!
