### ISSUE TITLE
Game corrupted?

### ISSUE THREAD

**Issue by ajkros** [EnderMediaDev/The-1.7.10-Pack#974]
I created a new world and my game froze. I closed it out then when i tried to log back in it said "The modpack The 1.7.10 Pack does not appear to be installed or is corrupted, and is not available for Offline Play. I have tried reinstalling it multiple times and I dont know what else to do. Maybe the technic platform servers are down I dont know.

**Comment by xJon** [comment]
Technic servers indeed were down. You can try again now, or try to provide more information in order for me to help you.

**Comment by ajkros** [comment]
thanks man!

**Comment by ajkros** [comment]
yep it works now!

**Comment by xJon** [comment]
:+1:
