### ISSUE TITLE
Suggestion-Immersive Engineering

### ISSUE THREAD

**Issue by Richard-001** [EnderMediaDev/The-1.7.10-Pack#975]
I know that there are assorted ways to power things already, such as the Big Reactors, but I think that immersive engineering would be a very cool thing to add into the modpack, to have giant windmills, water wheels, diesel engines, electric wires that hang down and telephones poles... I think it would be fantastic, maybe not the best thing for power necessarily, but it would certainly be amazing to have, especially if you want something with an earlier kind of electricty-generation feel to it.

**Comment by xJon** [comment]
Sorry but the mod won't get added.
Although it's indeed nice, it got too many duplicates and doesn't really fit the modpack's style.
Thanks anyway for suggesting!
