### ISSUE TITLE
COuple of craft recipies not working

### ISSUE THREAD

**Issue by Gazla** [EnderMediaDev/The-1.7.10-Pack#976]
Platinum seeds, asking for nickel crops (not seeds)

There also seems to be a numbering issue with creating Cooling Core from Gravitation Suites, The advanced heat exchanger is known as 4223:1 when crafting but in the recipe for the Cooling core is asking for 4223. (that in theory is 4223:0, and that doesn't exist)

Are either of these things changes that have been made to the mod pack or genuine bugs in the mods? I don't want to trade these items if they have been put in as natural advancement blockers in the mod pack.

**Comment by xJon** [comment]
These are all mods bugs unfortunately, nothing we can do about them.
If you want, you can report the GraviSuite bug directly to the author, although it doesn't seem like there's really support. As for MagicalCrops, there's a new version of it and you can read more [there](https://github.com/EnderMediaDev/The-1.7.10-Pack/issues/512).
