### ISSUE TITLE
Not recieving the Quest Book on a multiplayer server

### ISSUE THREAD

**Issue by ZacTheAcorn** [EnderMediaDev/The-1.7.10-Pack#977]
I set up a server, and when I logged on to it, I didnt get any of the books you would normally spawn with in a Singleplayer world, I tried to spawn one in but it said the item didn't exist.

**Comment by xJon** [comment]
Just cheat it in with NEI.
It should work and it works for other people, maybe you changed some of the configuration files :)

**Comment by ZacTheAcorn** [comment]
I legit just downloaded the server opened it, did all the regular set up. Got into a game and didnt spawn with one. And when I said "I tried to spawn one in" using NEI is what I did
