### ISSUE TITLE
Problem Entering SinglePlayer (Connection Lost A fatal error has occurred, this connection is terminated)

### ISSUE THREAD

**Issue by ShaDoW179** [EnderMediaDev/The-1.7.10-Pack#978]
Here are the details my problem started when i first downloaded it i just found the modpack and it was looking pretty good i just downloaded it yesterday and thinked about recording videos of this modpack when i first created a new world it opened the game i tested mods on a creative world then created a survival world then menu came when i clicked back to game it just told me Connection Lost A fatal error has occurred, this connection is terminated i tryed to enter the creative world it did the same then i tryed to reinstall it few times still the same i am not using optifine i didn't messed with mods or any file the problem is on singleplayer here are the logs 
[TechnicLauncher 2016-01-10.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/85145/TechnicLauncher.2016-01-10.txt)
[fml-client-lastest.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/85146/fml-client-lastest.txt)
[2016-01-10-7.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/85147/2016-01-10-7.txt)
[Lastest.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/85148/Lastest.txt)
so any more needed information ? if no help me please

**Comment by ShaDoW179** [comment]
When i enter a server it kinda enters it but on singleplayer the problem is there i tryed to reinstall the pack it didn't work and i didn't see any crash log or any thing new added to the folder help please because i am going to record videos of this modpack

**Comment by xJon** [comment]
Did you make any progress in this world? did you consider just making a new one?

**Comment by ShaDoW179** [comment]
I just opened a flat world and tested mods like flan's then i thinked i tested all the mods so i created a survival world then i got in creative to make sure i tested all but i didn't test mech's then i tested them on the world but i messed up my spawn so i decided to create a new one but that one did gave me  Connection Lost A fatal error has occurred, this connection is terminated so i said screw it then returned to the world that i messed the spawn but it gave the problem then i tryed to enter the flat world but the same then i came here for help thats all i have (Mech's are the flans mod pack)

**Comment by ShaDoW179** [comment]
YES FINALLY i just closed my internet then i entered my world then enabled back now it runs and servers runs 2 nice :D

**Comment by xJon** [comment]
:+1:

**Comment by NetGearM** [comment]
I want a help too, I just downloaded the mod and went to create a world and gave the same error !
What do I do?

**Comment by ImoKeidis** [comment]
> I want a help too, I just downloaded the mod and went to create a world and gave the same error !
> What do I do?

Delete Morph MOD, and it will be good c:
