### ISSUE TITLE
Forestry backpacks no longer working in 0.8.2

### ISSUE THREAD

**Issue by kevintoombs** [EnderMediaDev/The-1.7.10-Pack#979]
Specifically, the basic Miner's Backpack and Digger's Backpack.

No mods customized, nothing changed, freshly updated. I was able to remove the contents of the backpacks but couldn't put anything in them, and they wouldn't auto fill like normal. The Backpacks Backpack still functions normally.

**Comment by xJon** [comment]
Can you please try to report the issue [there](https://github.com/ForestryMC/ForestryMC/issues)?
