### ISSUE TITLE
Can't craft some IC2 items

### ISSUE THREAD

**Issue by Gifftron** [EnderMediaDev/The-1.7.10-Pack#982]
Hi, 
Some IC2 item recipes seem to be broken, including the one for advanced electric jetpack. We're running 0.8.2

**Comment by xJon** [comment]
The advanced electric jetpack is from the GraviSuit IC2 addon.
Anyway it works for me:
![image](https://cloud.githubusercontent.com/assets/8945347/12298650/e071d0a2-ba1b-11e5-92d3-5a17606630e4.png)

**Comment by Gifftron** [comment]
That recipe works but the booster engine does not, I had to cheat to add it
in to make the jet pack

**Comment by xJon** [comment]
That's may be a problem with the Gravitation Suite mod which isn't supported currently so there's nothing we can do. Thanks anyway for reporting!
