### ISSUE TITLE
Furnaces (cooking) do NOT work. (kCauldron)

### ISSUE THREAD

**Issue by I-cee-sharp** [EnderMediaDev/The-1.7.10-Pack#983]
I have a server (kCauldron, tested: 1614-174, unofficial-1614, unofficial-1566, all from Yive's mirror.) with a few plugins: Essentials (for /home /tpa /spawn), PermissionsEx (for rank owner, player, vip), worldguard (protecting spawn area) and worldedit (required for worldguard).

Now, eveything works fine, after removing the colorchat mod. (This has issues with essentials and loads of other plugins)

But after some time (2-3 days) of playing, furnaces didn't wanted to work anymore.
I tried OP permissions, creative mode, survival, eveything.
All furnaces are affected (all the modded ones too)
All cooking recipes are affected.
Just put the coal and supply in, and it does not start cooking. I have tried multiple versions, but no diffrence. 

Anybody knows how to fix this? Thanks. Thanks a lot.

**Comment by xJon** [comment]
KCauldron issue I suppose.
