### ISSUE TITLE
Ae2 issues

### ISSUE THREAD

**Issue by djdarkstorm** [EnderMediaDev/The-1.7.10-Pack#984]
Hello! I updated my dedicated server and my client side to 0.8.2 of the 1.7.10 pack, and now when I go to access any ME system terminal, it shows everything for about one second, but if I scroll down, or just sit there, all the little thumbnails for all the items in the system disappear. The little quantity still displays, and the word "craft" remains for the crafting items in the system. But no pictures, makes the system pretty much unusable. Any ideas? Everything else works smoothly

**Comment by xJon** [comment]
Does this happen in a fresh world too?

**Comment by djdarkstorm** [comment]
I haven't tried that, we have a year and a half old server with ridiculously large ae2 setups throughout it, all functional prior to update. I'll try a fresh offline world and try to set everything up with some drives and see if it displays normal but that wouldn't really be a fix, though maybe useful for troubleshooting?

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Thu, Jan 14, 2016 at 5:14 AM -0800, "Jon" <notifications@github.com<mailto:notifications@github.com>> wrote:


Does this happen in a fresh world too?

-

**Comment by djdarkstorm** [comment]
Ok, loaded a fresh world in single player and I could not seem to duplicate the issue. What information do I need to provide? (saw your tag) I really wasn't sure what all I would need to mention when I first posted my question so, sorry if I was short. This started post updating the server, so I assume the issue would be in the server folder, rather than client since the single player thing worked. I really don't want to start over, it is a really developed world at this point and that'll probably just lead me to uninstall minecraft in general, lol. This modpack is my favorite to date. I guess worst case I can just revert back to the old server version, if technic lets me re-download the older version of the 1.7.10 pack like FTB does for other packs.

**Comment by djdarkstorm** [comment]
So the issue is, I have items in my ME system that are from the previous forestry mod. How do I delete them from the world? I am 100% certain this is the issue after isolating the drives, but most of my long time acquired goods are on the same drives.


________________________________

**Comment by xJon** [comment]
You can just remove all Forestry items from your drives.

**Comment by djdarkstorm** [comment]
xJon, not really. When you click on them, the game will crash. The items aren't in the world except what you have in your ME system. I did fix the problem though by setting up two new ME systems side by side, isolating which drives had the bad items, putting them into the first new system. Then shift+space clicking to fill my inventory with the items I wanted to keep and transferring them to clean drives in new system 2. Repeated until all that was left in new system 1 were the bad items. Put the old drives into a trash can and done. I saw others had this issue on other forums so I figured I would explain so they may do the same thing. You could also use an AE2 IO but that would probably only help for the massive stack items. I just used an import bus for the things I had 100k+ of while I manually did the random nonsense stacks.

**Comment by xJon** [comment]
Did all Forestry items make your game crash? can you provide a crash report? also could you try update Forestry manually to [its latest version](http://jenkins.ic2.player.to/job/Forestry/) to see if it helps?

**Comment by djdarkstorm** [comment]
That's the thing. The 1-710 modpack was just updated, and the big deal about it was that he went from forestry version 3.6.3.20 to version 4.2.1.48. It was the items that either changed IDs between the two version, or something the mod dev removed completely when they released the new version. There''s no way to know because when I would hover over the blank item in the ME, it just said "unknown item" with the forestry mod label under it. There were only three types of forestry items in my ME from my ender quarry running for a month, though - so either there are only three items you can get via quarry from forestry or I don't know what. 

I honestly couldn't make heads or tails of this mess of a crash log. But if I clicked on the item, it was done. Also, at one point my friend was helping me and accidentally grabbed one of the forestry item into his inventory and he immediately crashed. Joined again, tried to trash can it, crashed. Joined three more times before I doused him with lava so he could lose his inventory. The mod that gives you a tombstone, of course created a tombstone. He broke the tombstone from afar (without collecting ANY of the items) and it crashed both of us AND the server - had to roll it back to the last backup. It was ridiculous - I'm just glad I got it sorted out, lol.

[crash-2016-01-16_09.56.47-server.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/93069/crash-2016-01-16_09.56.47-server.txt)

**Comment by xJon** [comment]
Do you still have a copy of your world with the issue so we can test it with the latest versions of Forestry and AE2?
Here's also a video: https://www.youtube.com/watch?v=eaY0RnYIK1M

**Comment by rastamanfb** [comment]
I have exactly the same problem. i run a hosted server for me and my friends and i cannot delete the item from my drive as if i click it, it immediately crashes my game.
not sure if this is whats also causing the invisible items on ae2 but it does seem to be related

**Comment by rastamanfb** [comment]
update,
Not so simple to sort out.
Latest version of Forestry requires an update to forge

**Comment by rastamanfb** [comment]
where would you like me to upload my world? its 860mb

**Comment by xJon** [comment]
We hope it got fixed in v0.8.3. If not there's not much to do, unfortunately.
