### ISSUE TITLE
Turning Table

### ISSUE THREAD

**Issue by Kinichie** [EnderMediaDev/The-1.7.10-Pack#985]
Having an issue with the IC2 turning table in both Multiplayer and Singleplayer. Any support able to be lent? The button's don't work to allow us to be able to change the 5/5 settings to reduce them.

![tt](https://cloud.githubusercontent.com/assets/16710355/12338565/1bd8e26a-bb08-11e5-9339-e80928443f29.png)

**Comment by Kinichie** [comment]
Seems this is an issue with IndustrialCraft 2 2.2.808-experimental. Updating to 2.2.811-experimental will fix this.

**Comment by xJon** [comment]
So I suppose you'll have to wait until the next update. Thanks for reporting though. :)
