### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by al100100** [EnderMediaDev/The-1.7.10-Pack#986]
I am having trouble opening my world, I simply cannot open the world without the game crashing. It all happened when I broke a chest, the game crashed and now every time I try to connect it crashes before I can even move. Is there anything I can do to restore the file?
[crash-2016-01-14_18.14.25-server.txt](https://github.com/EnderMediaDev/The-1.7.10-Pack/files/91138/crash-2016-01-14_18.14.25-server.txt)

**Comment by xJon** [comment]
It's some issue with Forestry and ExtraBees. You can try to reach these mods to get help, so maybe they can fix the issue with their mod.
Anyway I suppose you'll have to edit the item out of your player's inventory to be able to fix the save!
