### ISSUE TITLE
Help removing Galacticraft

### ISSUE THREAD

**Issue by thebalck** [EnderMediaDev/The-1.7.10-Pack#988]
Can you help me removing this mod from the modpack?
I want to add rotarycraft and other mods and they aren't compatible with galacticraft so i want to remove it, but every time i delete all files when i press play the files go back into the folders, i dont know how to remove them permanently, plz help

**Comment by xJon** [comment]
Just remove the .jar files from the mods folder.
Galacticraft Core, Galacticraft Planets, Micdoodle Core.
