### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Gazla** [EnderMediaDev/The-1.7.10-Pack#989]
Following update to most recent version we have started having issues on our server with users crashing out when using Bees in chests and have had some instances of AE stuff disappearing.

**Comment by xJon** [comment]
There is indeed an issue with bees and visual glitches with AE2 terminals. Currently no idea if there's a fix.

**Comment by xJon** [comment]
Please post if your have more info about the bees in a different issue, but the AE2 terminals problem is already reported.
