### ISSUE TITLE
The pack takes about 50mins to start

### ISSUE THREAD

**Issue by TheBadOne33** [EnderMediaDev/The-1.7.10-Pack#990]
http://paste.ubuntu.com/14575522/

Here is the log from the launcher. It stays on initialising for a long time.
I'm not using optifine, it happens on the client.
The log is when it's loading and stuck on the initialising .

**Comment by xJon** [comment]
This log shows a loading time of 1 minute and 20 seconds

**Comment by TheBadOne33** [comment]
As i said it's still loading, currently i've got the initialising screen with a hourglass.

**Comment by TheBadOne33** [comment]
Nevermind, using the Nvidia processor seems to solve the problem !
Have a good day !

**Comment by xJon** [comment]
You too!
