### ISSUE TITLE
Golden chests crashes my game

### ISSUE THREAD

**Issue by Sirtain** [EnderMediaDev/The-1.7.10-Pack#992]
I updated to 1.8.2 recently and my game that i had in 1.8.1 opens fine, but everytime i open a chest it crashes my game... I know it's because of forestery stuff but I don't wanna loose my game i spent like 35+ hours in it

**Comment by xJon** [comment]
Crash report? Please use a paste-tool.

**Comment by xJon** [comment]
Closed due to missing information.
