### ISSUE TITLE
Game taking 1 Hour 20 Minutes to load

### ISSUE THREAD

**Issue by TheWierdWalrus** [EnderMediaDev/The-1.7.10-Pack#994]
So, I try to launch the game with v8 java update 66, 4gb dedicated RAM and it just gets stuck on the initialising screen. It will load, but takes around 1 and a half hours. Anyone know what to do???

**Comment by xJon** [comment]
Latest log? also please use a paste-tool.

**Comment by xJon** [comment]
Closed due to missing information.
