### ISSUE TITLE
Game Crashes When Loading Save File

### ISSUE THREAD

**Issue by bobbyhead333** [EnderMediaDev/The-1.7.10-Pack#997]
I have played on this single-player world for about a month or so now, but when I try to load it up now, it says "Loading World", waits a few seconds, flashes back to the world selection screen, and then my game crashes. It's happened quite a few times now, and I honestly don't know what the problem is. When I attempted to create another world, it worked fine, so it must be something wrong with the world. I also tried manually reinstalling the entire pack, but that didn't seem to work, either.
Here is the crash log: http://paste.ubuntu.com/14668627/

Thanks very much!,
Bobby

**Comment by xJon** [comment]
Don't you have backups?

**Comment by xJon** [comment]
Closed due to inactivity.
